## yaml-language-server: $schema=https://www.schemastore.org/openapi-3.X.json
# vim: ft=yaml.openapi
openapi: 3.0.4

components:
  parameters:
    limitQuery:
      $ref: ./components/parameters/limitQuery.yaml
    orderQuery:
      $ref: ./components/parameters/orderQuery.yaml
    pageQuery:
      $ref: ./components/parameters/pageQuery.yaml
  responses:
    BadRequestError:
      $ref: ./components/responses/BadRequestError.yaml
    ForbiddenError:
      $ref: ./components/responses/ForbiddenError.yaml
    InternalServerError:
      $ref: ./components/responses/InternalServerError.yaml
    NotFoundError:
      $ref: ./components/responses/NotFoundError.yaml
    UnauthorizedError:
      $ref: ./components/responses/UnauthorizedError.yaml
  schemas:
    Error:
      $ref: ./components/schemas/Error.yaml
    Pagination:
      $ref: ./components/schemas/Pagination.yaml
