language: en-GB
reviews:
  profile: assertive
  poem: false

  tools:
    ruff:
      enabled: false
    markdownlint:
      enabled: false
    biome:
      enabled: false
    tflint:
      enabled: false
    flake8:
      enabled: false
    prismaLint:
      enabled: false
    oxc:
      enabled: false
    pylint:
      enabled: false

  path_instructions:
    - path: internal/note/**
      instructions: |
        - Strictly applying clean architecture, DDD, CQRS, Event Driven Architecture
    - path: internal/authorization/**
      instructions: |
        - Loosely applying layered architecture

  path_filters:
    - '!api/bundled/**'
    - '!packages/api-gen/**'
    - '!packages/api-document-nestjs-server/**'
    - '!packages/pb/**'
    - '!pkg/api/**'
    - '!pkg/pb/**'
