---
# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json
version: '2'

linters:
  enable:
    - exhaustive
    # - exhaustruct
    - tagalign
    - unparam
    - testifylint
  disable:
    - unused
  exclusions:
    generated: strict
  settings:
    staticcheck:
      dot-import-whitelist:
        - github.com/go-jet/jet/v2/postgres
    tagalign:
      align: true
      sort: true
      strict: true

formatters:
  enable:
    - gofumpt
  settings:
    gofumpt:
      module-path: github.com/notopia-uit
  exclusions:
    generated: strict

run:
  build-tags:
    - integration
