---
# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json
version: '2'

linters:
  enable:
    - exhaustive
    - exhaustruct
    - tagalign
    - unparam
    - testifylint
  disable:
    - unused
  settings:
    staticcheck:
      dot-import-whitelist:
        - github.com/go-jet/jet/v2/postgres
    tagalign:
      align: true
      sort: true
      strict: true
    exhaustruct:
      allow-empty: false
      allow-empty-returns: false
      allow-empty-declarations: true
      include:
        - github\.com/notopia-uit/notopia/.*\.*
      exclude:
        - github\.com/notopia-uit/notopia/.*/errs\.Err
        - github\.com/notopia-uit/notopia/internal/note/infra/persistence/pgsqlc\..*Params
  exclusions:
    generated: strict
    rules:
      - linters:
          - exhaustruct
        path: _test\.go

formatters:
  enable:
    - gofumpt
  settings:
    gofumpt:
      module-path: github.com/notopia-uit
  exclusions:
    generated: strict

run:
  build-tags:
    - integration
