---
# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json
version: '2'

linters:
  enable:
    - exhaustive
    - exhaustruct
    - tagalign
  disable:
    - unused
  exclusions:
    generated: strict
  settings:
    tagalign:
      align: true
      sort: true
      strict: true

formatters:
  enable:
    - gofumpt
  settings:
    gofumpt:
      module-path: github.com/notopia-uit
  exclusions:
    generated: strict

run:
  build-tags:
    - integration
