#:schema https://raw.githubusercontent.com/jdx/mise/refs/heads/main/schema/mise.json

[env]
REDOCLY_TELEMETRY = "off"
REDOCLY_SUPPRESS_UPDATE_NOTICE = "true"
NEXT_TELEMETRY_DISABLED = 1
MISE_EXPERIMENTAL = 1
OPENCODE_EXPERIMENTAL = "true"
OPENCODE_EXPERIMENTAL_OXFMT = "true"
OPENCODE_EXPERIMENTAL_EXA = "true"
COMPOSE_FILE = "./deploy/compose/compose.yaml"
'_'.path.paths = ["./bin/", "./scripts/", "./node_modules/.bin/"]

[tools]
"github:pressly/goose" = "3.27.1"
"go:github.com/goforj/wire/cmd/wire" = "1.2.0"
"go:github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen" = "2.7.0"
buf = "1.65.0"
pnpm = "10.33.4"
sqlc = "1.31.1"
java = "26.0.1"
mockery = "3.7.0"
"github:go-delve/delve" = "1.26.3"
d2 = "0.7.1"
"npm:@tailwindcss/language-server" = "0.14.29"
"npm:skills" = "latest"

[tools."http:plantuml"]
version = "1.2026.2"
url = "https://github.com/plantuml/plantuml/releases/download/v{{ version }}/plantuml.jar"

[tools."http:kroki"]
url = "https://github.com/yuzutech/kroki/releases/download/v{{ version }}/kroki-standalone-server-v{{ version }}.jar"
version = "0.30.1"
bin = "kroki-server.jar"

[shell_alias]
shadcn = "pnpm exec shadcn"
tsgo = "pnpm exec tsgo"
compose = "docker compose"
p = "pnpm"
pi = "pnpm install"
plantuml = "./bin/plantuml"
kroki = "./bin/kroki"
oxlint = "pnpm exec oxlint"
oxfmt = "pnpm exec oxfmt"
lazydocker = "lazydocker -f ./deploy/compose/compose.yaml"
css-language-server = "mise exec npm@tailwindcss/language-server -- css-language-server"

# [deps.pnpm]
# auto = true
#
# [deps.go]
# auto = true
#
# [deps.buf]
# auto = true
# sources = ["./buf.yaml"]
# outputs = ["./buf.lock"]
# run = "buf dep update"
# description = "Manage buf dependencies"
