packages:
  - docs
  - api
  - page
  - api/*
  - packages/*
  - apps/*

catalog:
  "@types/react": ^19.2.10
  "@types/react-dom": ^19.2.3
  openapi-typescript: ^7.10.1
  next: ^16.1.6
  react: ^19.2.4
  react-dom: ^19.2.4

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@swc/core"
  - core-js
  - esbuild
  - less
  - nx
  - protobufjs
  - sharp
  - unrs-resolver
  - vue-demi
