packages:
  - docs
  - api
  - page
  - api/*
  - packages/*

catalog:
  react: ^19.0.0
  react-dom: ^19.0.0

onlyBuiltDependencies:
  - "@swc/core"
  - core-js
  - esbuild
  - nx
  - protobufjs
  - vue-demi
