packages:
  - docs
  - api
  - page
  - api/*
  - packages/*

catalog:
  '@types/react': ^19.2.10
  '@types/react-dom': ^19.2.3
  openapi-typescript: ^7.10.1
  react: ^19.2.4
  react-dom: ^19.2.4

onlyBuiltDependencies:
  - '@swc/core'
  - core-js
  - esbuild
  - nx
  - protobufjs
  - vue-demi
