packages:
  - docs
  - api
  - page
  - api/*
  - packages/*
  - apps/*

catalog:
  '@bufbuild/buf': ^1.64.0
  '@bufbuild/protobuf': ^2.11.0
  '@connectrpc/connect': ^2.1.1
  '@connectrpc/validate': ^0.2.0
  '@tailwindcss/postcss': ^4.1.18
  '@types/react': ^19.2.10
  '@types/react-dom': ^19.2.3
  '@vitejs/plugin-react': ^5.1.2
  eslint: ^9.39.2
  eslint-config-next: ^16.1.6
  eslint-config-prettier: ^10.1.8
  eslint-plugin-better-tailwindcss: ^4.1.1
  eslint-plugin-import: ^2.32.0
  eslint-plugin-jsx-a11y: ^6.10.2
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^7.0.1
  next: ^16.1.6
  openapi-typescript: ^7.10.1
  prettier: ~3.8.1
  react: ^19.2.4
  react-dom: ^19.2.4
  tailwindcss: ^4.1.18
  tslib: ^2.8.1
  typescript: ^5.9.3
  typescript-eslint: ^8.54.0
  vite: ^7.3.1
  vitest: ^4.0.18

onlyBuiltDependencies:
  - '@bufbuild/buf'
  - '@parcel/watcher'
  - '@swc/core'
  - core-js
  - esbuild
  - less
  - nx
  - protobufjs
  - sharp
  - unrs-resolver
  - vue-demi
