packages:
  - docs
  - api
  - page
  - api/*
  - packages/*

catalog:
  react: ^19.0.0
  react-dom: ^19.0.0
  "@types/react": ^19.0.0
  "@types/react-dom": ^19.0.0
  "openapi-typescript": ^7.10.1

onlyBuiltDependencies:
  - "@swc/core"
  - core-js
  - esbuild
  - nx
  - protobufjs
  - vue-demi
