direction: right

vars: {
  d2-config: {
    layout-engine: elk
    theme-overrides: {
      N1: "#4c4f69"
      N2: "#5c5f77"
      N4: "#acb0be"
      N5: "#ccd0da"
      N7: "#eff1f5"
      B1: "#4c4f69"
      B2: "#6c6f85"
      B3: "#bcc0cc"
      B4: "#ccd0da"
      B5: "#dce0e8"
      B6: "#eff1f5"
      AA4: "#1e66f5"
      AA5: "#7287fd"
      AB4: "#8839ef"
      AB5: "#dc8a78"
    }
  }
}

classes: {
  notUsed: {
    style: {
      opacity: 0.4
      stroke-dash: 5
      fill: "#9ca0b0"
      stroke: "#4c4f69"
    }
  }
}

user: User {
  browser: Browser {
    icon: https://cdn.simpleicons.org/googlechrome/e64553
  }
}

gateway: Gateway {
  icon: https://cdn.simpleicons.org/traefikproxy/04a5e5
}

apps: Apps {
  web: Web {
    icon: https://cdn.simpleicons.org/nextdotjs/4c4f69
  }
}

services: Services {
  identity_provider: Identity Provider {
    icon: https://cdn.simpleicons.org/authentik/fe640b
  }

  object_storage: Object Storage {
    icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/rustfs.svg
  }

  document: Document Service Group {
    document_service: Document Service {
      icon: https://cdn.simpleicons.org/nodedotjs/40a02b
    }
    database: Database {
      icon: https://cdn.simpleicons.org/postgresql/7287fd
    }
    pub_sub: Pub/Sub {
      icon: https://cdn.simpleicons.org/redis/d20f39
      class: notUsed
    }
    document_service -> database
    document_service -> pub_sub: {
      class: notUsed
    }
  }

  note: Note Service Group {
    note_service: Note Service {
      icon: https://cdn.simpleicons.org/go/04a5e5
    }
    database: Database {
      icon: https://cdn.simpleicons.org/postgresql/7287fd
    }
    pub_sub: Pub/Sub {
      icon: https://cdn.simpleicons.org/redis/d20f39
    }
    note_service -> database
    note_service -> pub_sub
  }

  authorization: Authorization Service Group {
    authorization_service: Authorization Service {
      icon: https://cdn.simpleicons.org/go/04a5e5
    }
    database: Database {
      icon: https://cdn.simpleicons.org/postgresql/7287fd
    }
    authorization_service -> database
  }

  search: Search Service Group {
    search_service: Meilisearch {
      icon: https://cdn.simpleicons.org/meilisearch/ea76cb
    }
    search_sync_worker: Sync Worker {
      icon: https://cdn.simpleicons.org/nodedotjs/40a02b
    }
    search_sync_worker_database: Sync Database {
      icon: https://cdn.simpleicons.org/redis/d20f39
      class: notUsed
    }
    search_sync_worker -> search_service
    search_sync_worker -> search_sync_worker_database: {
      class: notUsed
    }
  }

  event_bus: Event Bus {
    message_broker: Message Broker {
      icon: https://raw.githubusercontent.com/redpanda-data/redpanda/d17f36726370db7c7044cb12ecc1c46841e8bfa6/docs/icon-redpanda.svg
    }
  }

  monotoring: Monitoring {
    alloy: Alloy {
      icon: https://raw.githubusercontent.com/grafana/alloy/refs/heads/main/docs/sources/assets/alloy_icon_orange.svg
    }
    prometheus: Prometheus {
      icon: https://raw.githubusercontent.com/prometheus/prometheus/refs/heads/main/documentation/images/prometheus-logo.svg
    }
    loki: Loki {
      icon: https://raw.githubusercontent.com/grafana/grafana/refs/heads/main/public/app/plugins/datasource/loki/img/loki_icon.svg
    }
    tempo: Tempo {
      icon: https://raw.githubusercontent.com/grafana/grafana/refs/heads/main/public/app/plugins/datasource/tempo/img/tempo_logo.svg
    }
    grafana: Grafana {
      icon: https://raw.githubusercontent.com/grafana/grafana/refs/heads/main/public/img/grafana_icon.svg
    }
    alloy -> prometheus
    alloy -> loki
    alloy -> tempo
    prometheus <- grafana
    loki <- grafana
    tempo <- grafana
  }
}

user.browser -> gateway

apps -> services.identity_provider
apps -> services.object_storage

gateway -> apps
gateway -> services.document
gateway -> services.note
gateway -> services.identity_provider
gateway -> services.object_storage
gateway -> services.search
gateway -> services.monotoring

services.document -> services.note
services.document <-> services.event_bus
services.document -> services.authorization
services.document -> services.object_storage

services.note <-> services.event_bus
services.note -> services.authorization

services.authorization <- services.event_bus

services.search <- services.event_bus

style.border-radius: 15
*.style.border-radius: 15
*.*.style.border-radius: 15
*.*.*.style.border-radius: 15
