@startuml Note
title Note

!$rosewater = "#dc8a78"
!$flamingo  = "#dd7878"
!$pink      = "#ea76cb"
!$mauve     = "#8839ef"
!$red       = "#d20f39"
!$maroon    = "#e64553"
!$peach     = "#fe640b"
!$yellow    = "#df8e1d"
!$green     = "#40a02b"
!$teal      = "#179299"
!$sky       = "#04a5e5"
!$sapphire  = "#209fb5"
!$lavender  = "#7287fd"
!$blue      = "#1e66f5"
!$text      = "#4c4f69"
!$subtext1  = "#5c5f77"
!$subtext0  = "#6c6f85"
!$overlay2  = "#7c7f93"
!$overlay1  = "#8c8fa1"
!$overlay0  = "#9ca0b0"
!$surface2  = "#acb0be"
!$surface1  = "#bcc0cc"
!$surface0  = "#ccd0da"
!$base      = "#eff1f5"
!$mantle    = "#e6e9ef"
!$crust     = "#dce0e8"

skinparam backgroundColor $base
skinparam defaultFontColor $text
skinparam roundcorner 16
skinparam classFontStyle bold

skinparam ArrowColor $subtext0
skinparam packageStyle rectangle

skinparam package {
    BackgroundColor $mantle
    BorderColor $surface1
    FontColor $mauve
}

skinparam class {
    BackgroundColor $base
    BorderColor $surface1
    HeaderBackgroundColor $surface0
    AttributeFontColor $text
}

!define RepoInterface(name) interface "name" as Domain.name <<(I, $pink) Repo Interface>>
!define ServiceInterface(name) interface "name" as Domain.name <<(I, $rosewater) Service Interface>>
!define Enum(name) enum "name" as Domain.name <<(E, $flamingo) Enum>>
!define ValueObject(name) class "name" as Domain.name <<(S, $yellow) Value Object>>
!define AggregateRoot(name) class "name" as Domain.name <<(S, $sky) Aggregate Root>>

package "Domain" as Domain <<Frame>> {
    Enum(TrashedBy) {
        UNSPECIFIED
        PURPOSE
        PARENT
    }

    AggregateRoot(Workspace) {
        id uuid.UUID
        name string
        slug string
        rootFolderID uuid.UUID
        deletedAt *time.Time

        Rename(name string)
        Delete()
    }

    AggregateRoot(Folder) {
        id uuid.UUID
        name string
        icon *string
        workspaceID uuid.UUID
        folderHierarchy FolderHierarchy
        trashed *Trashed

        Rename(name string)
        SetIcon(icon string)
        ParentID() *uuid.UUID
        IsRoot() bool
        MoveToFolder(folderID uuid.UUID)
        Trash(trashedBy TrashedBy)
        Restore()
    }

    ValueObject(FolderHierarchy) {
        parentID *uuid.UUID

        ParentID() *uuid.UUID
        IsRoot() bool
    }

    AggregateRoot(Note) {
        id uuid.UUID
        name string
        icon *string
        tags []string
        size uint
        folderID uuid.UUID
        outgoingLinks uuid.UUIDs
        trashed *Trashed

        Rename(name string)
        SetIcon(icon string)
        SetTags(tags []string)
        SetSize(size uint)
        MoveToFolder(folderID uuid.UUID)
        SetOutgoingLinks(outgoingLinks uuid.UUIDs)
        Trash(trashedBy TrashedBy)
        Restore()
    }

    ValueObject(Trashed) {
        by TrashedBy
        at time.Time
    }

    class "NoteService" as Domain.NoteService {
        UpdateNoteSizeBasedOnContent(note *Note, content any) error
    }

    Domain.Workspace "1" *... "1..*" Domain.Folder : contains
    Domain.Folder "1" *-- "1" Domain.FolderHierarchy : has
    Domain.Folder "1" *... "0..*" Domain.Note : contains
    Domain.Note "0..*" .. "0..*" Domain.Note : links

    RepoInterface(WorkspaceRepo) {
        GetBySlug(ctx context.Context, slug string, forUpdate bool) (*Workspace, error)
        GetIDBySlug(ctx context.Context, slug string) (*uuid.UUID, error)
        CheckSlugExists(ctx context.Context, slug string) (bool, error)
        Save(ctx context.Context, workspace *Workspace) error
    }

    RepoInterface(FolderRepo) {
        GetByID(ctx context.Context, id uuid.UUID, forUpdate bool) (*Folder, error)
        GetByIDs(ctx context.Context, ids uuid.UUIDs, forUpdate bool) ([]Folder, error)
        Save(ctx context.Context, folder *Folder) error
        SaveMany(ctx context.Context, folders []Folder) error
        AreAllInWorkspace(ctx context.Context, ids []uuid.UUID, workspaceID uuid.UUID) (bool, error)
        GetTrashedByWorkspaceID(ctx context.Context, workspaceID uuid.UUID, trashedBy TrashedBy) ([]Folder, error)
        PermanentlyDeleteByID(ctx context.Context, id uuid.UUID) error
        PermanentlyDeleteByIDs(ctx context.Context, ids uuid.UUIDs) error
    }

    RepoInterface(NoteRepo) {
        GetByID(ctx context.Context, id uuid.UUID, forUpdate bool) (*Note, error)
        GetByIDs(ctx context.Context, ids uuid.UUIDs, forUpdate bool) ([]Note, error)
        Save(ctx context.Context, note *Note) error
        SaveMany(ctx context.Context, notes []Note) error
        AreAllInWorkspace(ctx context.Context, ids []uuid.UUID, workspaceID uuid.UUID) (bool, error)
        GetTrashedByWorkspaceID(ctx context.Context, workspaceID uuid.UUID) ([]Note, error)
        PermanentlyDeleteByID(ctx context.Context, id uuid.UUID) error
        PermanentlyDeleteByIDs(ctx context.Context, ids uuid.UUIDs) error
    }
}
@enduml
