// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { EditBundledWsEditsDocumentData, EditBundledWsEditsDocumentErrors, EditBundledWsEditsDocumentResponses, NoteBundledCreateNoteData, NoteBundledCreateNoteErrors, NoteBundledCreateNoteResponses, NoteBundledDeleteNoteData, NoteBundledDeleteNoteErrors, NoteBundledDeleteNoteResponses, NoteBundledGetNoteData, NoteBundledGetNoteErrors, NoteBundledGetNoteResponses, NoteBundledGetWorkspaceEventsData, NoteBundledGetWorkspaceEventsErrors, NoteBundledGetWorkspaceEventsResponses, NoteBundledListNotesData, NoteBundledListNotesErrors, NoteBundledListNotesResponses, NoteBundledPatchNoteData, NoteBundledPatchNoteErrors, NoteBundledPatchNoteResponses, NoteBundledUpdateNoteData, NoteBundledUpdateNoteErrors, NoteBundledUpdateNoteResponses } from './types.gen';
import { zEditBundledWsEditsDocumentData, zNoteBundledCreateNoteData, zNoteBundledCreateNoteResponse, zNoteBundledDeleteNoteData, zNoteBundledDeleteNoteResponse, zNoteBundledGetNoteData, zNoteBundledGetNoteResponse, zNoteBundledGetWorkspaceEventsData, zNoteBundledGetWorkspaceEventsResponse, zNoteBundledListNotesData, zNoteBundledListNotesResponse, zNoteBundledPatchNoteData, zNoteBundledPatchNoteResponse, zNoteBundledUpdateNoteData, zNoteBundledUpdateNoteResponse } from './zod.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * WebSocket for editing a document
 *
 * Establish a WebSocket connection for real-time collaborative editing of a document.
 */
export const editBundledWsEditsDocument = <ThrowOnError extends boolean = false>(options: Options<EditBundledWsEditsDocumentData, ThrowOnError>) => (options.client ?? client).get<EditBundledWsEditsDocumentResponses, EditBundledWsEditsDocumentErrors, ThrowOnError>({
    requestValidator: async (data) => await zEditBundledWsEditsDocumentData.parseAsync(data),
    url: '/ws/edits/{documentId}',
    ...options
});

/**
 * List notes
 *
 * Retrieve a paginated list of all notes with optional filtering and sorting
 */
export const noteBundledListNotes = <ThrowOnError extends boolean = false>(options?: Options<NoteBundledListNotesData, ThrowOnError>) => (options?.client ?? client).get<NoteBundledListNotesResponses, NoteBundledListNotesErrors, ThrowOnError>({
    requestValidator: async (data) => await zNoteBundledListNotesData.parseAsync(data),
    responseValidator: async (data) => await zNoteBundledListNotesResponse.parseAsync(data),
    url: '/note/notes',
    ...options
});

/**
 * Create note
 *
 * Create a new note
 */
export const noteBundledCreateNote = <ThrowOnError extends boolean = false>(options: Options<NoteBundledCreateNoteData, ThrowOnError>) => (options.client ?? client).post<NoteBundledCreateNoteResponses, NoteBundledCreateNoteErrors, ThrowOnError>({
    requestValidator: async (data) => await zNoteBundledCreateNoteData.parseAsync(data),
    responseValidator: async (data) => await zNoteBundledCreateNoteResponse.parseAsync(data),
    url: '/note/notes',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete note
 *
 * Delete a note by its unique identifier
 */
export const noteBundledDeleteNote = <ThrowOnError extends boolean = false>(options: Options<NoteBundledDeleteNoteData, ThrowOnError>) => (options.client ?? client).delete<NoteBundledDeleteNoteResponses, NoteBundledDeleteNoteErrors, ThrowOnError>({
    requestValidator: async (data) => await zNoteBundledDeleteNoteData.parseAsync(data),
    responseValidator: async (data) => await zNoteBundledDeleteNoteResponse.parseAsync(data),
    url: '/note/notes/{noteId}',
    ...options
});

/**
 * Get note
 *
 * Retrieve a single note by its unique identifier
 */
export const noteBundledGetNote = <ThrowOnError extends boolean = false>(options: Options<NoteBundledGetNoteData, ThrowOnError>) => (options.client ?? client).get<NoteBundledGetNoteResponses, NoteBundledGetNoteErrors, ThrowOnError>({
    requestValidator: async (data) => await zNoteBundledGetNoteData.parseAsync(data),
    responseValidator: async (data) => await zNoteBundledGetNoteResponse.parseAsync(data),
    url: '/note/notes/{noteId}',
    ...options
});

/**
 * Patch note
 *
 * Update specific fields of a note (only provided fields will be updated)
 */
export const noteBundledPatchNote = <ThrowOnError extends boolean = false>(options: Options<NoteBundledPatchNoteData, ThrowOnError>) => (options.client ?? client).patch<NoteBundledPatchNoteResponses, NoteBundledPatchNoteErrors, ThrowOnError>({
    requestValidator: async (data) => await zNoteBundledPatchNoteData.parseAsync(data),
    responseValidator: async (data) => await zNoteBundledPatchNoteResponse.parseAsync(data),
    url: '/note/notes/{noteId}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Put note
 *
 * Replace an existing note with new data (all fields are required)
 */
export const noteBundledUpdateNote = <ThrowOnError extends boolean = false>(options: Options<NoteBundledUpdateNoteData, ThrowOnError>) => (options.client ?? client).put<NoteBundledUpdateNoteResponses, NoteBundledUpdateNoteErrors, ThrowOnError>({
    requestValidator: async (data) => await zNoteBundledUpdateNoteData.parseAsync(data),
    responseValidator: async (data) => await zNoteBundledUpdateNoteResponse.parseAsync(data),
    url: '/note/notes/{noteId}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * SSE workspace updates
 */
export const noteBundledGetWorkspaceEvents = <ThrowOnError extends boolean = false>(options: Options<NoteBundledGetWorkspaceEventsData, ThrowOnError>) => (options.client ?? client).sse.get<NoteBundledGetWorkspaceEventsResponses, NoteBundledGetWorkspaceEventsErrors, ThrowOnError>({
    requestValidator: async (data) => await zNoteBundledGetWorkspaceEventsData.parseAsync(data),
    responseValidator: async (data) => await zNoteBundledGetWorkspaceEventsResponse.parseAsync(data),
    url: '/note/workspaces/{workspaceId}/events',
    ...options
});
