// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateNoteData, CreateNoteErrors, CreateNoteResponses, DeleteNoteData, DeleteNoteErrors, DeleteNoteResponses, GetNoteData, GetNoteErrors, GetNoteResponses, GetWorkspaceEventsData, GetWorkspaceEventsErrors, GetWorkspaceEventsResponses, ListNotesData, ListNotesErrors, ListNotesResponses, PatchNoteData, PatchNoteErrors, PatchNoteResponses, UpdateNoteData, UpdateNoteErrors, UpdateNoteResponses, WsEditsDocumentData, WsEditsDocumentErrors, WsEditsDocumentResponses } from './types.gen';
import { zCreateNoteData, zCreateNoteResponse, zDeleteNoteData, zDeleteNoteResponse, zGetNoteData, zGetNoteResponse, zGetWorkspaceEventsData, zGetWorkspaceEventsResponse, zListNotesData, zListNotesResponse, zPatchNoteData, zPatchNoteResponse, zUpdateNoteData, zUpdateNoteResponse, zWsEditsDocumentData } from './zod.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * WebSocket for editing a document
 *
 * Establish a WebSocket connection for real-time collaborative editing of a document.
 */
export const wsEditsDocument = <ThrowOnError extends boolean = false>(options: Options<WsEditsDocumentData, ThrowOnError>) => (options.client ?? client).get<WsEditsDocumentResponses, WsEditsDocumentErrors, ThrowOnError>({
    requestValidator: async (data) => await zWsEditsDocumentData.parseAsync(data),
    url: '/ws/edits/{documentId}',
    ...options
});

/**
 * List notes
 *
 * Retrieve a paginated list of all notes with optional filtering and sorting
 */
export const listNotes = <ThrowOnError extends boolean = false>(options?: Options<ListNotesData, ThrowOnError>) => (options?.client ?? client).get<ListNotesResponses, ListNotesErrors, ThrowOnError>({
    requestValidator: async (data) => await zListNotesData.parseAsync(data),
    responseValidator: async (data) => await zListNotesResponse.parseAsync(data),
    url: '/note/notes',
    ...options
});

/**
 * Create note
 *
 * Create a new note
 */
export const createNote = <ThrowOnError extends boolean = false>(options: Options<CreateNoteData, ThrowOnError>) => (options.client ?? client).post<CreateNoteResponses, CreateNoteErrors, ThrowOnError>({
    requestValidator: async (data) => await zCreateNoteData.parseAsync(data),
    responseValidator: async (data) => await zCreateNoteResponse.parseAsync(data),
    url: '/note/notes',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete note
 *
 * Delete a note by its unique identifier
 */
export const deleteNote = <ThrowOnError extends boolean = false>(options: Options<DeleteNoteData, ThrowOnError>) => (options.client ?? client).delete<DeleteNoteResponses, DeleteNoteErrors, ThrowOnError>({
    requestValidator: async (data) => await zDeleteNoteData.parseAsync(data),
    responseValidator: async (data) => await zDeleteNoteResponse.parseAsync(data),
    url: '/note/notes/{noteId}',
    ...options
});

/**
 * Get note
 *
 * Retrieve a single note by its unique identifier
 */
export const getNote = <ThrowOnError extends boolean = false>(options: Options<GetNoteData, ThrowOnError>) => (options.client ?? client).get<GetNoteResponses, GetNoteErrors, ThrowOnError>({
    requestValidator: async (data) => await zGetNoteData.parseAsync(data),
    responseValidator: async (data) => await zGetNoteResponse.parseAsync(data),
    url: '/note/notes/{noteId}',
    ...options
});

/**
 * Patch note
 *
 * Update specific fields of a note (only provided fields will be updated)
 */
export const patchNote = <ThrowOnError extends boolean = false>(options: Options<PatchNoteData, ThrowOnError>) => (options.client ?? client).patch<PatchNoteResponses, PatchNoteErrors, ThrowOnError>({
    requestValidator: async (data) => await zPatchNoteData.parseAsync(data),
    responseValidator: async (data) => await zPatchNoteResponse.parseAsync(data),
    url: '/note/notes/{noteId}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Put note
 *
 * Replace an existing note with new data (all fields are required)
 */
export const updateNote = <ThrowOnError extends boolean = false>(options: Options<UpdateNoteData, ThrowOnError>) => (options.client ?? client).put<UpdateNoteResponses, UpdateNoteErrors, ThrowOnError>({
    requestValidator: async (data) => await zUpdateNoteData.parseAsync(data),
    responseValidator: async (data) => await zUpdateNoteResponse.parseAsync(data),
    url: '/note/notes/{noteId}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * SSE workspace updates
 */
export const getWorkspaceEvents = <ThrowOnError extends boolean = false>(options: Options<GetWorkspaceEventsData, ThrowOnError>) => (options.client ?? client).sse.get<GetWorkspaceEventsResponses, GetWorkspaceEventsErrors, ThrowOnError>({
    requestValidator: async (data) => await zGetWorkspaceEventsData.parseAsync(data),
    responseValidator: async (data) => await zGetWorkspaceEventsResponse.parseAsync(data),
    url: '/note/workspaces/{workspaceId}/events',
    ...options
});
