// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://api.notopia.localhost' | 'http://localhost:8082' | 'http://localhost:8081' | (string & {});
};

export type EditBundledError = {
    /**
     * Error code
     */
    code: string;
    /**
     * Human-readable error message
     */
    message: string;
    /**
     * URL with more information about the error
     */
    more_info?: string;
};

export type NoteBundledNote = {
    readonly id?: string;
    /**
     * Title of the note
     */
    title?: string;
    /**
     * Timestamp when the note was created
     */
    readonly createdAt?: string;
    /**
     * Timestamp when the note was last updated
     */
    readonly updatedAt?: string | null;
};

export type NoteBundledPagination = {
    /**
     * Current page number
     */
    page: number;
    /**
     * Number of items per page
     */
    limit: number;
    /**
     * Total number of items
     */
    total: number;
    /**
     * Total number of pages
     */
    totalPages: number;
    /**
     * Whether there is a next page
     */
    hasNext: boolean;
    /**
     * Whether there is a previous page
     */
    hasPrev: boolean;
};

export type NoteBundledError = {
    /**
     * Error code
     */
    code: string;
    /**
     * Human-readable error message
     */
    message: string;
    /**
     * URL with more information about the error
     */
    more_info?: string;
};

export type NoteBundledNoteRequired = NoteBundledNote;

export type NoteBundledNoteMovedEvent = {
    type: 'NoteMovedEvent';
    data: {
        noteId: string;
        fromFolderId: string;
        toFolderId: string;
    };
};

export type NoteBundledFolderMovedEvent = {
    type: 'FolderRenamedEvent';
    data: {
        folderId: string;
        oldFolderId: string;
        newFolderId: string;
    };
};

export type NoteBundledFolderRenamedEvent = {
    type: 'FolderRenamedEvent';
    data: {
        folderId: string;
        oldName: string;
        newName: string;
    };
};

export type NoteBundledWorkspaceRenamedEvent = {
    type: 'WorkspaceRenamedEvent';
    data: {
        workspaceId: string;
        oldName: string;
        newName: string;
    };
};

export type NoteBundledNoteWritable = {
    /**
     * Title of the note
     */
    title?: string;
};

export type NoteBundledNoteRequiredWritable = NoteBundledNoteWritable;

/**
 * Unique identifier of the document (note)
 */
export type EditBundledDocumentIdPath = string;

/**
 * Page number for pagination
 */
export type NoteBundledPageQuery = number;

/**
 * Number of items per page
 */
export type NoteBundledLimitQuery = number;

/**
 * Sort order
 */
export const NoteBundledOrderQuery = { ASC: 'asc', DESC: 'desc' } as const;

/**
 * Sort order
 */
export type NoteBundledOrderQuery = typeof NoteBundledOrderQuery[keyof typeof NoteBundledOrderQuery];

/**
 * Unique identifier of the note
 */
export type NoteBundledNoteIdPath = string;

/**
 * The unique identifier of the workspace.
 */
export type NoteBundledWorkspaceIdPath = string;

/**
 * Create note request
 */
export type NoteBundledCreateNoteRequest = NoteBundledNoteRequiredWritable & unknown;

/**
 * Put note request (replace entire note)
 */
export type NoteBundledPutNoteRequest = NoteBundledNoteRequiredWritable & unknown;

/**
 * Patch note request (partial update)
 */
export type NoteBundledPatchNoteRequest = NoteBundledNoteWritable & unknown;

export type EditBundledWsEditsDocumentData = {
    body?: never;
    path: {
        /**
         * Unique identifier of the document (note)
         */
        documentId: string;
    };
    query?: never;
    url: '/ws/edits/{documentId}';
};

export type EditBundledWsEditsDocumentErrors = {
    /**
     * Bad Request Error response
     */
    400: EditBundledError;
    /**
     * Unauthorized Error response
     */
    401: EditBundledError;
    /**
     * Not Found Error response
     */
    404: EditBundledError;
    /**
     * Internal Server Error response
     */
    500: EditBundledError;
};

export type EditBundledWsEditsDocumentError = EditBundledWsEditsDocumentErrors[keyof EditBundledWsEditsDocumentErrors];

export type EditBundledWsEditsDocumentResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type NoteBundledListNotesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number for pagination
         */
        page?: number;
        /**
         * Number of items per page
         */
        limit?: number;
        /**
         * Sort order
         */
        order?: 'asc' | 'desc';
        /**
         * Field to sort by
         */
        sortBy?: 'createdAt' | 'updatedAt' | 'title';
        /**
         * Search notes by title or content
         */
        search?: string;
    };
    url: '/note/notes';
};

export type NoteBundledListNotesErrors = {
    /**
     * Bad Request Error response
     */
    400: NoteBundledError;
    /**
     * Unauthorized Error response
     */
    401: NoteBundledError;
    /**
     * Internal Server Error response
     */
    500: NoteBundledError;
};

export type NoteBundledListNotesError = NoteBundledListNotesErrors[keyof NoteBundledListNotesErrors];

export type NoteBundledListNotesResponses = {
    /**
     * Successful response
     */
    200: {
        data: Array<NoteBundledNote>;
        pagination: NoteBundledPagination & unknown;
    };
};

export type NoteBundledListNotesResponse = NoteBundledListNotesResponses[keyof NoteBundledListNotesResponses];

export type NoteBundledCreateNoteData = {
    /**
     * Create note request
     */
    body: NoteBundledCreateNoteRequest;
    path?: never;
    query?: never;
    url: '/note/notes';
};

export type NoteBundledCreateNoteErrors = {
    /**
     * Bad Request Error response
     */
    400: NoteBundledError;
    /**
     * Unauthorized Error response
     */
    401: NoteBundledError;
    /**
     * Internal Server Error response
     */
    500: NoteBundledError;
};

export type NoteBundledCreateNoteError = NoteBundledCreateNoteErrors[keyof NoteBundledCreateNoteErrors];

export type NoteBundledCreateNoteResponses = {
    /**
     * Note successfully created
     */
    201: NoteBundledNote & unknown;
};

export type NoteBundledCreateNoteResponse = NoteBundledCreateNoteResponses[keyof NoteBundledCreateNoteResponses];

export type NoteBundledDeleteNoteData = {
    body?: never;
    path: {
        /**
         * Unique identifier of the note
         */
        noteId: string;
    };
    query?: never;
    url: '/note/notes/{noteId}';
};

export type NoteBundledDeleteNoteErrors = {
    /**
     * Bad Request Error response
     */
    400: NoteBundledError;
    /**
     * Unauthorized Error response
     */
    401: NoteBundledError;
    /**
     * Forbidden Error response
     */
    403: NoteBundledError;
    /**
     * Not Found Error response
     */
    404: NoteBundledError;
    /**
     * Internal Server Error response
     */
    500: NoteBundledError;
};

export type NoteBundledDeleteNoteError = NoteBundledDeleteNoteErrors[keyof NoteBundledDeleteNoteErrors];

export type NoteBundledDeleteNoteResponses = {
    /**
     * Note successfully deleted
     */
    204: void;
};

export type NoteBundledDeleteNoteResponse = NoteBundledDeleteNoteResponses[keyof NoteBundledDeleteNoteResponses];

export type NoteBundledGetNoteData = {
    body?: never;
    path: {
        /**
         * Unique identifier of the note
         */
        noteId: string;
    };
    query?: never;
    url: '/note/notes/{noteId}';
};

export type NoteBundledGetNoteErrors = {
    /**
     * Bad Request Error response
     */
    400: NoteBundledError;
    /**
     * Unauthorized Error response
     */
    401: NoteBundledError;
    /**
     * Forbidden Error response
     */
    403: NoteBundledError;
    /**
     * Not Found Error response
     */
    404: NoteBundledError;
    /**
     * Internal Server Error response
     */
    500: NoteBundledError;
};

export type NoteBundledGetNoteError = NoteBundledGetNoteErrors[keyof NoteBundledGetNoteErrors];

export type NoteBundledGetNoteResponses = {
    /**
     * Successful response
     */
    200: NoteBundledNoteRequired & unknown;
};

export type NoteBundledGetNoteResponse = NoteBundledGetNoteResponses[keyof NoteBundledGetNoteResponses];

export type NoteBundledPatchNoteData = {
    /**
     * Patch note request (partial update)
     */
    body: NoteBundledPatchNoteRequest;
    path: {
        /**
         * Unique identifier of the note
         */
        noteId: string;
    };
    query?: never;
    url: '/note/notes/{noteId}';
};

export type NoteBundledPatchNoteErrors = {
    /**
     * Bad Request Error response
     */
    400: NoteBundledError;
    /**
     * Unauthorized Error response
     */
    401: NoteBundledError;
    /**
     * Forbidden Error response
     */
    403: NoteBundledError;
    /**
     * Not Found Error response
     */
    404: NoteBundledError;
    /**
     * Internal Server Error response
     */
    500: NoteBundledError;
};

export type NoteBundledPatchNoteError = NoteBundledPatchNoteErrors[keyof NoteBundledPatchNoteErrors];

export type NoteBundledPatchNoteResponses = {
    /**
     * Note successfully patched
     */
    200: NoteBundledNote & unknown;
};

export type NoteBundledPatchNoteResponse = NoteBundledPatchNoteResponses[keyof NoteBundledPatchNoteResponses];

export type NoteBundledUpdateNoteData = {
    /**
     * Put note request (replace entire note)
     */
    body: NoteBundledPutNoteRequest;
    path: {
        /**
         * Unique identifier of the note
         */
        noteId: string;
    };
    query?: never;
    url: '/note/notes/{noteId}';
};

export type NoteBundledUpdateNoteErrors = {
    /**
     * Bad Request Error response
     */
    400: NoteBundledError;
    /**
     * Unauthorized Error response
     */
    401: NoteBundledError;
    /**
     * Forbidden Error response
     */
    403: NoteBundledError;
    /**
     * Not Found Error response
     */
    404: NoteBundledError;
    /**
     * Internal Server Error response
     */
    500: NoteBundledError;
};

export type NoteBundledUpdateNoteError = NoteBundledUpdateNoteErrors[keyof NoteBundledUpdateNoteErrors];

export type NoteBundledUpdateNoteResponses = {
    /**
     * Note successfully updated
     */
    200: NoteBundledNoteRequired & unknown;
};

export type NoteBundledUpdateNoteResponse = NoteBundledUpdateNoteResponses[keyof NoteBundledUpdateNoteResponses];

export type NoteBundledGetWorkspaceEventsData = {
    body?: never;
    path: {
        /**
         * The unique identifier of the workspace.
         */
        workspaceId: string;
    };
    query?: never;
    url: '/note/workspaces/{workspaceId}/events';
};

export type NoteBundledGetWorkspaceEventsErrors = {
    /**
     * Bad Request Error response
     */
    400: NoteBundledError;
    /**
     * Unauthorized Error response
     */
    401: NoteBundledError;
    /**
     * Internal Server Error response
     */
    500: NoteBundledError;
};

export type NoteBundledGetWorkspaceEventsError = NoteBundledGetWorkspaceEventsErrors[keyof NoteBundledGetWorkspaceEventsErrors];

export type NoteBundledGetWorkspaceEventsResponses = {
    /**
     * A persistent stream of events
     */
    200: ({
        type: 'note_bundled_NoteMovedEvent';
    } & NoteBundledNoteMovedEvent) | ({
        type: 'note_bundled_FolderMovedEvent';
    } & NoteBundledFolderMovedEvent) | ({
        type: 'note_bundled_FolderRenamedEvent';
    } & NoteBundledFolderRenamedEvent) | ({
        type: 'note_bundled_WorkspaceRenamedEvent';
    } & NoteBundledWorkspaceRenamedEvent);
};

export type NoteBundledGetWorkspaceEventsResponse = NoteBundledGetWorkspaceEventsResponses[keyof NoteBundledGetWorkspaceEventsResponses];
