// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | 'http://api.notopia.localhost' | 'http://localhost:8082' | 'http://api.notopia.localhost' | 'http://localhost:8082' | 'http://api.notopia.localhost' | 'http://localhost:8082' | 'http://api.notopia.localhost' | 'http://localhost:8081' | 'http://api.notopia.localhost' | 'http://localhost:8081' | 'http://api.notopia.localhost' | 'http://localhost:8081' | 'http://api.notopia.localhost' | 'http://localhost:8081' | 'http://api.notopia.localhost' | 'http://localhost:8081' | 'http://api.notopia.localhost' | 'http://localhost:8081' | 'http://api.notopia.localhost' | 'http://localhost:8081' | 'http://api.notopia.localhost' | 'http://localhost:8081' | 'http://api.notopia.localhost' | 'http://localhost:8081' | 'http://api.notopia.localhost' | 'http://localhost:8081' | 'http://api.notopia.localhost' | 'http://localhost:8081' | 'http://api.notopia.localhost' | 'http://localhost:8081' | 'http://api.notopia.localhost' | 'http://localhost:8081' | 'http://api.notopia.localhost' | 'http://localhost:8081' | 'http://api.notopia.localhost' | 'http://localhost:8081' | 'http://api.notopia.localhost' | 'http://localhost:8081' | 'http://api.notopia.localhost' | 'http://localhost:8081' | 'http://api.notopia.localhost' | 'http://localhost:8081' | 'http://api.notopia.localhost' | 'http://localhost:8081' | 'http://api.notopia.localhost' | 'http://localhost:8081' | 'http://api.notopia.localhost' | 'http://localhost:8081' | 'http://api.notopia.localhost' | 'http://localhost:8081' | 'http://api.notopia.localhost' | 'http://localhost:8081' | 'http://api.notopia.localhost' | 'http://localhost:8081' | 'http://api.notopia.localhost' | 'http://localhost:8081' | (string & {});
};

export type Error = {
    /**
     * Error code
     */
    code: string;
    /**
     * Human-readable error message
     */
    message: string;
    /**
     * URL with more information about the error
     */
    more_info?: string;
};

export type Id = string;

export type Name = string | null;

export type Note = {
    readonly id: string;
    name: string;
    folderId: string;
    readonly currentRevision: {
        id?: Id;
        name?: Name;
    };
};

export type PropertiesId = string;

export type PropertiesName = string;

export type Revision = {
    readonly id: string;
    name: string | null;
    blockNoteContent: string | null;
    readonly createdAt: string;
};

export type Pagination = {
    /**
     * Current page number
     */
    page: number;
    /**
     * Number of items per page
     */
    limit: number;
    /**
     * Total number of items
     */
    total: number;
    /**
     * Total number of pages
     */
    totalPages: number;
    /**
     * Whether there is a next page
     */
    hasNext: boolean;
    /**
     * Whether there is a previous page
     */
    hasPrev: boolean;
};

export type Workspace = {
    readonly id: string;
    name: string;
};

export type Folder = {
    readonly id: string;
    name: string;
    parentId: string | null;
};

export type FolderWithRelations = Folder & {
    children: Array<FolderWithRelations>;
    parentId: string | null;
    notes: Array<Note>;
};

export type NoteMovedEvent = {
    type: 'NoteMovedEvent';
    data: {
        noteId: string;
        fromFolderId: string;
        toFolderId: string;
    };
};

export type FolderMovedEvent = {
    type: 'FolderRenamedEvent';
    data: {
        folderId: string;
        oldFolderId: string;
        newFolderId: string;
    };
};

export type FolderRenamedEvent = {
    type: 'FolderRenamedEvent';
    data: {
        folderId: string;
        oldName: string;
        newName: string;
    };
};

export type WorkspaceRenamedEvent = {
    type: 'WorkspaceRenamedEvent';
    data: {
        workspaceId: string;
        oldName: string;
        newName: string;
    };
};

export type WorkspacePropertiesName = string;

export const TrashedDeletedBy = { PURPOSE: 'purpose', PARENT: 'parent' } as const;

export type TrashedDeletedBy = typeof TrashedDeletedBy[keyof typeof TrashedDeletedBy];

export type TrashedNote = {
    id: string;
    readonly name: string;
    type: 'note';
    deletedBy: TrashedDeletedBy;
    readonly deletedAt: string | null;
};

export type TrashedFolder = {
    id: string;
    readonly name: string;
    type: 'folder';
    deletedBy: TrashedDeletedBy;
    readonly deletedAt: string | null;
};

export type FolderPropertiesName = string;

export type NoteWritable = {
    name: string;
    folderId: string;
};

export type RevisionWritable = {
    name: string | null;
    blockNoteContent: string | null;
};

export type WorkspaceWritable = {
    name: string;
};

export type FolderWritable = {
    name: string;
    parentId: string | null;
};

export type FolderWithRelationsWritable = FolderWritable & {
    children: Array<FolderWithRelationsWritable>;
    parentId: string | null;
    notes: Array<NoteWritable>;
};

export type TrashedNoteWritable = {
    id: string;
    type: 'note';
};

export type TrashedFolderWritable = {
    id: string;
    type: 'folder';
};

/**
 * Unique identifier of the document (note)
 */
export type DocumentIdPath = string;

export type NoteIdPath = string;

/**
 * Page number for pagination
 */
export type PageQuery = number;

/**
 * Number of items per page
 */
export type LimitQuery = number;

export type RevisionIdPath = string;

export type WorkspaceIdPath = string;

export type FolderIdPath = string;

export type ImportDocumentsRequest = Array<{
    [key: string]: unknown;
}>;

export type CreateNoteRequest = NoteWritable;

export type GenerateDailyNoteRequest = {
    workspaceId: PropertiesId;
};

export type OpenRandomNoteRequest = {
    workspaceId: PropertiesId;
};

export type SearchTagsRequest = {
    name: string;
    limit?: number;
};

export type RenameNoteRequest = {
    name: PropertiesName;
};

export type RenameNoteRevisionRequest = {
    name: Name;
};

export type CreateWorkspaceRequest = WorkspaceWritable;

export type RenameWorkspaceRequest = {
    name: WorkspacePropertiesName;
};

export type RestoreTrashedWorkspaceItemsRequest = Array<({
    type: 'note';
} & TrashedNoteWritable) | ({
    type: 'folder';
} & TrashedFolderWritable)>;

export type TrashWorkspaceItemsRequest = Array<({
    type: 'note';
} & TrashedNoteWritable) | ({
    type: 'folder';
} & TrashedFolderWritable)>;

export type CreateFolderRequest = FolderWritable;

export type RenameFolderRequest = {
    name: FolderPropertiesName;
};

export type ImportDocumentsData = {
    body: ImportDocumentsRequest;
    path?: never;
    query?: never;
    url: '/document/documents/import';
};

export type ImportDocumentsErrors = {
    /**
     * Bad Request Error response
     */
    400: Error;
    /**
     * Unauthorized Error response
     */
    401: Error;
    /**
     * Not Found Error response
     */
    404: Error;
    /**
     * Internal Server Error response
     */
    500: Error;
};

export type ImportDocumentsError = ImportDocumentsErrors[keyof ImportDocumentsErrors];

export type ImportDocumentsResponses = {
    /**
     * Successfully imported documents
     */
    201: unknown;
};

export type WsDocumentData = {
    body?: never;
    path: {
        /**
         * Unique identifier of the document (note)
         */
        documentId: string;
    };
    query?: never;
    url: '/document/ws/documents/{documentId}';
};

export type WsDocumentErrors = {
    /**
     * Bad Request Error response
     */
    400: Error;
    /**
     * Unauthorized Error response
     */
    401: Error;
    /**
     * Not Found Error response
     */
    404: Error;
    /**
     * Internal Server Error response
     */
    500: Error;
};

export type WsDocumentError = WsDocumentErrors[keyof WsDocumentErrors];

export type WsDocumentResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetDocumentAttachmentUrlData = {
    body?: never;
    path: {
        /**
         * Unique identifier of the document (note)
         */
        documentId: string;
    };
    query?: never;
    url: '/document/documents/{documentId}/attachment-url';
};

export type GetDocumentAttachmentUrlErrors = {
    /**
     * Bad Request Error response
     */
    400: Error;
    /**
     * Unauthorized Error response
     */
    401: Error;
    /**
     * Not Found Error response
     */
    404: Error;
    /**
     * Internal Server Error response
     */
    500: Error;
};

export type GetDocumentAttachmentUrlError = GetDocumentAttachmentUrlErrors[keyof GetDocumentAttachmentUrlErrors];

export type GetDocumentAttachmentUrlResponses = {
    /**
     * Presigned URL
     */
    200: {
        url: string;
    };
};

export type GetDocumentAttachmentUrlResponse = GetDocumentAttachmentUrlResponses[keyof GetDocumentAttachmentUrlResponses];

export type CreateNoteData = {
    body: CreateNoteRequest;
    path?: never;
    query?: never;
    url: '/note/notes';
};

export type CreateNoteErrors = {
    /**
     * Bad Request Error response
     */
    400: Error;
    /**
     * Unauthorized Error response
     */
    401: Error;
    /**
     * Internal Server Error response
     */
    500: Error;
};

export type CreateNoteError = CreateNoteErrors[keyof CreateNoteErrors];

export type CreateNoteResponses = {
    /**
     * Note successfully created
     */
    201: unknown;
};

export type GenerateDailyNoteData = {
    body: GenerateDailyNoteRequest;
    path?: never;
    query?: never;
    url: '/note/notes/generate-daily';
};

export type GenerateDailyNoteErrors = {
    /**
     * Bad Request Error response
     */
    400: Error;
    /**
     * Unauthorized Error response
     */
    401: Error;
    /**
     * Not Found Error response
     */
    404: Error;
    /**
     * Internal Server Error response
     */
    500: Error;
};

export type GenerateDailyNoteError = GenerateDailyNoteErrors[keyof GenerateDailyNoteErrors];

export type GenerateDailyNoteResponses = {
    /**
     * Daily note generated successfully
     */
    201: unknown;
};

export type OpenRandomNoteData = {
    body: OpenRandomNoteRequest;
    path?: never;
    query?: never;
    url: '/note/notes/random';
};

export type OpenRandomNoteErrors = {
    /**
     * Bad Request Error response
     */
    400: Error;
    /**
     * Unauthorized Error response
     */
    401: Error;
    /**
     * Not Found Error response
     */
    404: Error;
    /**
     * Internal Server Error response
     */
    500: Error;
};

export type OpenRandomNoteError = OpenRandomNoteErrors[keyof OpenRandomNoteErrors];

export type OpenRandomNoteResponses = {
    /**
     * Random note
     */
    201: unknown;
};

export type SearchTagsData = {
    body: SearchTagsRequest;
    path?: never;
    query?: never;
    url: '/note/notes/search-tags';
};

export type SearchTagsErrors = {
    /**
     * Bad Request Error response
     */
    400: Error;
    /**
     * Unauthorized Error response
     */
    401: Error;
    /**
     * Internal Server Error response
     */
    500: Error;
};

export type SearchTagsError = SearchTagsErrors[keyof SearchTagsErrors];

export type SearchTagsResponses = {
    /**
     * List of matching tags in the workspace
     */
    200: Array<string>;
};

export type SearchTagsResponse = SearchTagsResponses[keyof SearchTagsResponses];

export type DeleteNoteData = {
    body?: never;
    path: {
        noteId: string;
    };
    query?: never;
    url: '/note/notes/{noteId}';
};

export type DeleteNoteErrors = {
    /**
     * Bad Request Error response
     */
    400: Error;
    /**
     * Unauthorized Error response
     */
    401: Error;
    /**
     * Forbidden Error response
     */
    403: Error;
    /**
     * Not Found Error response
     */
    404: Error;
    /**
     * Internal Server Error response
     */
    500: Error;
};

export type DeleteNoteError = DeleteNoteErrors[keyof DeleteNoteErrors];

export type DeleteNoteResponses = {
    /**
     * Note successfully deleted
     */
    204: void;
};

export type DeleteNoteResponse = DeleteNoteResponses[keyof DeleteNoteResponses];

export type GetNoteData = {
    body?: never;
    path: {
        noteId: string;
    };
    query?: never;
    url: '/note/notes/{noteId}';
};

export type GetNoteErrors = {
    /**
     * Bad Request Error response
     */
    400: Error;
    /**
     * Unauthorized Error response
     */
    401: Error;
    /**
     * Forbidden Error response
     */
    403: Error;
    /**
     * Not Found Error response
     */
    404: Error;
    /**
     * Internal Server Error response
     */
    500: Error;
};

export type GetNoteError = GetNoteErrors[keyof GetNoteErrors];

export type GetNoteResponses = {
    /**
     * Successful response
     */
    200: Note;
};

export type GetNoteResponse = GetNoteResponses[keyof GetNoteResponses];

export type PublishNoteData = {
    body?: never;
    path: {
        noteId: string;
    };
    query?: never;
    url: '/note/notes/{noteId}/publish';
};

export type PublishNoteErrors = {
    /**
     * Bad Request Error response
     */
    400: Error;
    /**
     * Unauthorized Error response
     */
    401: Error;
    /**
     * Not Found Error response
     */
    404: Error;
    /**
     * Internal Server Error response
     */
    500: Error;
};

export type PublishNoteError = PublishNoteErrors[keyof PublishNoteErrors];

export type PublishNoteResponses = {
    /**
     * Note published successfully
     */
    204: void;
};

export type PublishNoteResponse = PublishNoteResponses[keyof PublishNoteResponses];

export type RenameNoteData = {
    body: RenameNoteRequest;
    path: {
        noteId: string;
    };
    query?: never;
    url: '/note/notes/{noteId}/rename';
};

export type RenameNoteErrors = {
    /**
     * Bad Request Error response
     */
    400: Error;
    /**
     * Unauthorized Error response
     */
    401: Error;
    /**
     * Not Found Error response
     */
    404: Error;
    /**
     * Internal Server Error response
     */
    500: Error;
};

export type RenameNoteError = RenameNoteErrors[keyof RenameNoteErrors];

export type RenameNoteResponses = {
    /**
     * Note renamed successfully
     */
    204: void;
};

export type RenameNoteResponse = RenameNoteResponses[keyof RenameNoteResponses];

export type GetNoteRevisionsData = {
    body?: never;
    path: {
        noteId: string;
    };
    query?: {
        /**
         * Page number for pagination
         */
        page?: number;
        /**
         * Number of items per page
         */
        limit?: number;
    };
    url: '/note/notes/{noteId}/revisions';
};

export type GetNoteRevisionsErrors = {
    /**
     * Bad Request Error response
     */
    400: Error;
    /**
     * Unauthorized Error response
     */
    401: Error;
    /**
     * Not Found Error response
     */
    404: Error;
    /**
     * Internal Server Error response
     */
    500: Error;
};

export type GetNoteRevisionsError = GetNoteRevisionsErrors[keyof GetNoteRevisionsErrors];

export type GetNoteRevisionsResponses = {
    /**
     * Note revisions
     */
    200: {
        data: Array<Revision>;
        pagination: Pagination;
    };
};

export type GetNoteRevisionsResponse = GetNoteRevisionsResponses[keyof GetNoteRevisionsResponses];

export type RenameNoteRevisionData = {
    body: RenameNoteRevisionRequest;
    path: {
        noteId: string;
        revisionId: string;
    };
    query?: never;
    url: '/note/notes/{noteId}/revisions/{revisionId}/rename';
};

export type RenameNoteRevisionErrors = {
    /**
     * Bad Request Error response
     */
    400: Error;
    /**
     * Unauthorized Error response
     */
    401: Error;
    /**
     * Not Found Error response
     */
    404: Error;
    /**
     * Internal Server Error response
     */
    500: Error;
};

export type RenameNoteRevisionError = RenameNoteRevisionErrors[keyof RenameNoteRevisionErrors];

export type RenameNoteRevisionResponses = {
    /**
     * Note revisions
     */
    200: {
        data: Array<Revision>;
        pagination: Pagination;
    };
};

export type RenameNoteRevisionResponse = RenameNoteRevisionResponses[keyof RenameNoteRevisionResponses];

export type DeleteNoteRevisionData = {
    body?: never;
    path: {
        noteId: string;
        revisionId: string;
    };
    query?: never;
    url: '/note/notes/{noteId}/revisions/{revisionId}';
};

export type DeleteNoteRevisionErrors = {
    /**
     * Bad Request Error response
     */
    400: Error;
    /**
     * Unauthorized Error response
     */
    401: Error;
    /**
     * Forbidden Error response
     */
    403: Error;
    /**
     * Not Found Error response
     */
    404: Error;
    /**
     * Internal Server Error response
     */
    500: Error;
};

export type DeleteNoteRevisionError = DeleteNoteRevisionErrors[keyof DeleteNoteRevisionErrors];

export type DeleteNoteRevisionResponses = {
    /**
     * Revision deleted successfully
     */
    204: void;
};

export type DeleteNoteRevisionResponse = DeleteNoteRevisionResponses[keyof DeleteNoteRevisionResponses];

export type GetNoteRevisionData = {
    body?: never;
    path: {
        noteId: string;
        revisionId: string;
    };
    query?: never;
    url: '/note/notes/{noteId}/revisions/{revisionId}';
};

export type GetNoteRevisionErrors = {
    /**
     * Bad Request Error response
     */
    400: Error;
    /**
     * Unauthorized Error response
     */
    401: Error;
    /**
     * Forbidden Error response
     */
    403: Error;
    /**
     * Not Found Error response
     */
    404: Error;
    /**
     * Internal Server Error response
     */
    500: Error;
};

export type GetNoteRevisionError = GetNoteRevisionErrors[keyof GetNoteRevisionErrors];

export type GetNoteRevisionResponses = {
    /**
     * Note revision detail
     */
    200: Revision;
};

export type GetNoteRevisionResponse = GetNoteRevisionResponses[keyof GetNoteRevisionResponses];

export type UnpublishNoteData = {
    body?: never;
    path: {
        noteId: string;
    };
    query?: never;
    url: '/note/notes/{noteId}/unpublish';
};

export type UnpublishNoteErrors = {
    /**
     * Bad Request Error response
     */
    400: Error;
    /**
     * Unauthorized Error response
     */
    401: Error;
    /**
     * Not Found Error response
     */
    404: Error;
    /**
     * Internal Server Error response
     */
    500: Error;
};

export type UnpublishNoteError = UnpublishNoteErrors[keyof UnpublishNoteErrors];

export type UnpublishNoteResponses = {
    /**
     * Note unpublished successfully
     */
    204: void;
};

export type UnpublishNoteResponse = UnpublishNoteResponses[keyof UnpublishNoteResponses];

export type CreateWorkspaceData = {
    body: CreateWorkspaceRequest;
    path?: never;
    query?: never;
    url: '/note/workspaces';
};

export type CreateWorkspaceErrors = {
    /**
     * Bad Request Error response
     */
    400: Error;
    /**
     * Unauthorized Error response
     */
    401: Error;
    /**
     * Internal Server Error response
     */
    500: Error;
};

export type CreateWorkspaceError = CreateWorkspaceErrors[keyof CreateWorkspaceErrors];

export type CreateWorkspaceResponses = {
    /**
     * Workspace successfully created
     */
    201: unknown;
};

export type DeleteWorkspaceData = {
    body?: never;
    path: {
        workspaceId: string;
    };
    query?: never;
    url: '/note/workspaces/{workspaceId}';
};

export type DeleteWorkspaceErrors = {
    /**
     * Bad Request Error response
     */
    400: Error;
    /**
     * Unauthorized Error response
     */
    401: Error;
    /**
     * Not Found Error response
     */
    404: Error;
    /**
     * Internal Server Error response
     */
    500: Error;
};

export type DeleteWorkspaceError = DeleteWorkspaceErrors[keyof DeleteWorkspaceErrors];

export type DeleteWorkspaceResponses = {
    /**
     * No Content - Workspace successfully deleted.
     */
    204: void;
};

export type DeleteWorkspaceResponse = DeleteWorkspaceResponses[keyof DeleteWorkspaceResponses];

export type GetWorkspaceData = {
    body?: never;
    path: {
        workspaceId: string;
    };
    query?: never;
    url: '/note/workspaces/{workspaceId}';
};

export type GetWorkspaceErrors = {
    /**
     * Bad Request Error response
     */
    400: Error;
    /**
     * Unauthorized Error response
     */
    401: Error;
    /**
     * Not Found Error response
     */
    404: Error;
    /**
     * Internal Server Error response
     */
    500: Error;
};

export type GetWorkspaceError = GetWorkspaceErrors[keyof GetWorkspaceErrors];

export type GetWorkspaceResponses = {
    /**
     * OK
     */
    200: Workspace & {
        rootFolder: FolderWithRelations;
    };
};

export type GetWorkspaceResponse = GetWorkspaceResponses[keyof GetWorkspaceResponses];

export type GetWorkspaceEventsData = {
    body?: never;
    path: {
        workspaceId: string;
    };
    query?: never;
    url: '/note/workspaces/{workspaceId}/events';
};

export type GetWorkspaceEventsErrors = {
    /**
     * Bad Request Error response
     */
    400: Error;
    /**
     * Unauthorized Error response
     */
    401: Error;
    /**
     * Internal Server Error response
     */
    500: Error;
};

export type GetWorkspaceEventsError = GetWorkspaceEventsErrors[keyof GetWorkspaceEventsErrors];

export type GetWorkspaceEventsResponses = {
    /**
     * A persistent stream of events
     */
    200: ({
        type: 'NoteMovedEvent';
    } & NoteMovedEvent) | ({
        type: 'FolderMovedEvent';
    } & FolderMovedEvent) | ({
        type: 'FolderRenamedEvent';
    } & FolderRenamedEvent) | ({
        type: 'WorkspaceRenamedEvent';
    } & WorkspaceRenamedEvent);
};

export type GetWorkspaceEventsResponse = GetWorkspaceEventsResponses[keyof GetWorkspaceEventsResponses];

export type PublishWorkspaceData = {
    body?: never;
    path: {
        workspaceId: string;
    };
    query?: never;
    url: '/note/workspaces/{workspaceId}/publish';
};

export type PublishWorkspaceErrors = {
    /**
     * Bad Request Error response
     */
    400: Error;
    /**
     * Unauthorized Error response
     */
    401: Error;
    /**
     * Not Found Error response
     */
    404: Error;
    /**
     * Internal Server Error response
     */
    500: Error;
};

export type PublishWorkspaceError = PublishWorkspaceErrors[keyof PublishWorkspaceErrors];

export type PublishWorkspaceResponses = {
    /**
     * Workspace published successfully
     */
    204: void;
};

export type PublishWorkspaceResponse = PublishWorkspaceResponses[keyof PublishWorkspaceResponses];

export type RenameWorkspaceData = {
    body: RenameWorkspaceRequest;
    path: {
        workspaceId: string;
    };
    query?: never;
    url: '/note/workspaces/{workspaceId}/rename';
};

export type RenameWorkspaceErrors = {
    /**
     * Bad Request Error response
     */
    400: Error;
    /**
     * Unauthorized Error response
     */
    401: Error;
    /**
     * Not Found Error response
     */
    404: Error;
    /**
     * Internal Server Error response
     */
    500: Error;
};

export type RenameWorkspaceError = RenameWorkspaceErrors[keyof RenameWorkspaceErrors];

export type RenameWorkspaceResponses = {
    /**
     * Workspace renamed successfully
     */
    204: void;
};

export type RenameWorkspaceResponse = RenameWorkspaceResponses[keyof RenameWorkspaceResponses];

export type RestoreTrashedWorkspaceItemsData = {
    body: RestoreTrashedWorkspaceItemsRequest;
    path: {
        workspaceId: string;
    };
    query?: never;
    url: '/note/workspaces/{workspaceId}/restore-trashed-items';
};

export type RestoreTrashedWorkspaceItemsErrors = {
    /**
     * Bad Request Error response
     */
    400: Error;
    /**
     * Unauthorized Error response
     */
    401: Error;
    /**
     * Not Found Error response
     */
    404: Error;
    /**
     * Internal Server Error response
     */
    500: Error;
};

export type RestoreTrashedWorkspaceItemsError = RestoreTrashedWorkspaceItemsErrors[keyof RestoreTrashedWorkspaceItemsErrors];

export type RestoreTrashedWorkspaceItemsResponses = {
    /**
     * Workspace items successfully restored
     */
    204: void;
};

export type RestoreTrashedWorkspaceItemsResponse = RestoreTrashedWorkspaceItemsResponses[keyof RestoreTrashedWorkspaceItemsResponses];

export type ShowTrashData = {
    body?: never;
    path: {
        workspaceId: string;
    };
    query?: never;
    url: '/note/workspaces/{workspaceId}/show-trash';
};

export type ShowTrashErrors = {
    /**
     * Bad Request Error response
     */
    400: Error;
    /**
     * Unauthorized Error response
     */
    401: Error;
    /**
     * Not Found Error response
     */
    404: Error;
    /**
     * Internal Server Error response
     */
    500: Error;
};

export type ShowTrashError = ShowTrashErrors[keyof ShowTrashErrors];

export type ShowTrashResponses = {
    /**
     * Trash
     */
    200: {
        data: Array<({
            type: 'note';
        } & TrashedNote) | ({
            type: 'folder';
        } & TrashedFolder)>;
        pagination: Pagination;
    };
};

export type ShowTrashResponse = ShowTrashResponses[keyof ShowTrashResponses];

export type TrashWorkspaceItemsData = {
    body: TrashWorkspaceItemsRequest;
    path: {
        workspaceId: string;
    };
    query?: never;
    url: '/note/workspaces/{workspaceId}/trash-items';
};

export type TrashWorkspaceItemsErrors = {
    /**
     * Bad Request Error response
     */
    400: Error;
    /**
     * Unauthorized Error response
     */
    401: Error;
    /**
     * Not Found Error response
     */
    404: Error;
    /**
     * Internal Server Error response
     */
    500: Error;
};

export type TrashWorkspaceItemsError = TrashWorkspaceItemsErrors[keyof TrashWorkspaceItemsErrors];

export type TrashWorkspaceItemsResponses = {
    /**
     * Workspace items successfully trashed
     */
    204: void;
};

export type TrashWorkspaceItemsResponse = TrashWorkspaceItemsResponses[keyof TrashWorkspaceItemsResponses];

export type UnpublishWorkspaceData = {
    body?: never;
    path: {
        workspaceId: string;
    };
    query?: never;
    url: '/note/workspaces/{workspaceId}/unpublish';
};

export type UnpublishWorkspaceErrors = {
    /**
     * Bad Request Error response
     */
    400: Error;
    /**
     * Unauthorized Error response
     */
    401: Error;
    /**
     * Not Found Error response
     */
    404: Error;
    /**
     * Internal Server Error response
     */
    500: Error;
};

export type UnpublishWorkspaceError = UnpublishWorkspaceErrors[keyof UnpublishWorkspaceErrors];

export type UnpublishWorkspaceResponses = {
    /**
     * Workspace unpublished successfully
     */
    204: void;
};

export type UnpublishWorkspaceResponse = UnpublishWorkspaceResponses[keyof UnpublishWorkspaceResponses];

export type CreateFolderData = {
    body: CreateFolderRequest;
    path?: never;
    query?: never;
    url: '/note/folders';
};

export type CreateFolderErrors = {
    /**
     * Bad Request Error response
     */
    400: Error;
    /**
     * Unauthorized Error response
     */
    401: Error;
    /**
     * Internal Server Error response
     */
    500: Error;
};

export type CreateFolderError = CreateFolderErrors[keyof CreateFolderErrors];

export type CreateFolderResponses = {
    /**
     * Folder successfully created
     */
    201: unknown;
};

export type RenameFolderData = {
    body: RenameFolderRequest;
    path: {
        folderId: string;
    };
    query?: never;
    url: '/note/folders/{folderId}/rename';
};

export type RenameFolderErrors = {
    /**
     * Bad Request Error response
     */
    400: Error;
    /**
     * Unauthorized Error response
     */
    401: Error;
    /**
     * Not Found Error response
     */
    404: Error;
    /**
     * Internal Server Error response
     */
    500: Error;
};

export type RenameFolderError = RenameFolderErrors[keyof RenameFolderErrors];

export type RenameFolderResponses = {
    /**
     * Folder renamed successfully
     */
    204: void;
};

export type RenameFolderResponse = RenameFolderResponses[keyof RenameFolderResponses];
