// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * Number of items per page
 */
export const zLimitQueryRoot = z.unknown();

/**
 * Sort order
 */
export const zOrderQueryRoot = z.unknown();

/**
 * Page number for pagination
 */
export const zPageQueryRoot = z.unknown();

/**
 * Bad Request Error response
 */
export const zBadRequestErrorRoot = z.unknown();

/**
 * Forbidden Error response
 */
export const zForbiddenErrorRoot = z.unknown();

/**
 * Internal Server Error response
 */
export const zInternalServerErrorRoot = z.unknown();

/**
 * Not Found Error response
 */
export const zNotFoundErrorRoot = z.unknown();

/**
 * Unauthorized Error response
 */
export const zUnauthorizedErrorRoot = z.unknown();

export const zErrorRoot = z.object({
    code: z.string(),
    message: z.string(),
    more_info: z.optional(z.string())
});

export const zPaginationRoot = z.object({
    page: z.int().gte(1),
    limit: z.int().gte(1).lte(100),
    total: z.int().gte(0),
    totalPages: z.int().gte(0),
    hasNext: z.boolean(),
    hasPrev: z.boolean()
});

/**
 * OAuth2 Security Scheme
 */
export const zOauth2Root = z.unknown();

/**
 * Unique identifier of the document (note)
 */
export const zDocumentIdPathRoot = z.unknown();

export const zWsEdits7BdocumentId7dRoot = z.unknown();

export const zCreateNoteRequestRoot = z.unknown();

/**
 * Meeting Notes
 */
export const zCreateNoteResponseRoot = z.unknown();

/**
 * Meeting Notes
 */
export const zGetNoteResponseRoot = z.unknown();

export const zListNoteResponseDataRoot = z.unknown();

export const zListNoteResponsePaginationRoot = z.unknown();

export const zPatchNoteRequestRoot = z.unknown();

/**
 * Partially Updated Meeting Notes
 */
export const zPatchNoteResponseRoot = z.unknown();

export const zPutNoteRequestRoot = z.unknown();

/**
 * Updated Meeting Notes
 */
export const zPutNoteResponseRoot = z.unknown();

/**
 * Unique identifier of the note
 */
export const zNoteIdPathRoot = z.unknown();

export const zWorkspaceIdPathRoot = z.unknown();

/**
 * Create note request
 */
export const zCreateNoteRequestRoot2 = z.unknown();

/**
 * Patch note request (partial update)
 */
export const zPatchNoteRequestRoot2 = z.unknown();

/**
 * Put note request (replace entire note)
 */
export const zPutNoteRequestRoot2 = z.unknown();

/**
 * Note successfully created
 */
export const zCreateNoteResponseRoot2 = z.unknown();

/**
 * Successful response
 */
export const zGetNoteResponseRoot2 = z.unknown();

/**
 * A persistent stream of events
 */
export const zGetWorkspaceEventsResponseRoot = z.unknown();

/**
 * Successful response
 */
export const zListNotesResponseRoot = z.unknown();

/**
 * Note successfully patched
 */
export const zPatchNoteResponseRoot2 = z.unknown();

/**
 * Note successfully updated
 */
export const zPutNoteResponseRoot2 = z.unknown();

export const zFolderMovedEventRoot = z.object({
    type: z.enum(['FolderRenamedEvent']),
    data: z.object({
        folderId: z.uuid(),
        oldFolderId: z.uuid(),
        newFolderId: z.uuid()
    })
});

export const zFolderRenamedEventRoot = z.object({
    type: z.enum(['FolderRenamedEvent']),
    data: z.object({
        folderId: z.uuid(),
        oldName: z.string(),
        newName: z.string()
    })
});

export const zNoteRoot = z.object({
    id: z.optional(z.uuid().readonly()),
    title: z.optional(z.string().min(1).max(255)),
    createdAt: z.optional(z.iso.datetime().readonly()),
    updatedAt: z.optional(z.union([
        z.iso.datetime().readonly(),
        z.null()
    ]).readonly())
});

export const zNoteMovedEventRoot = z.object({
    type: z.enum(['NoteMovedEvent']),
    data: z.object({
        noteId: z.uuid(),
        fromFolderId: z.uuid(),
        toFolderId: z.uuid()
    })
});

export const zNoteRequiredRoot = zNoteRoot;

export const zWorkspaceRenamedEventRoot = z.object({
    type: z.enum(['WorkspaceRenamedEvent']),
    data: z.object({
        workspaceId: z.uuid(),
        oldName: z.string(),
        newName: z.string()
    })
});

export const zNotesRoot = z.unknown();

export const zNotes7BnoteId7dRoot = z.unknown();

export const zWorkspaces7BworkspaceId7dEventsRoot = z.unknown();

/**
 * Create note request
 */
export const zCreateNoteRequestRoot2Writable = z.unknown();

/**
 * Patch note request (partial update)
 */
export const zPatchNoteRequestRoot2Writable = z.unknown();

/**
 * Put note request (replace entire note)
 */
export const zPutNoteRequestRoot2Writable = z.unknown();

/**
 * Note successfully created
 */
export const zCreateNoteResponseRoot2Writable = z.unknown();

/**
 * Successful response
 */
export const zGetNoteResponseRoot2Writable = z.unknown();

/**
 * Successful response
 */
export const zListNotesResponseRootWritable = z.unknown();

/**
 * Note successfully patched
 */
export const zPatchNoteResponseRoot2Writable = z.unknown();

/**
 * Note successfully updated
 */
export const zPutNoteResponseRoot2Writable = z.unknown();

export const zNoteRootWritable = z.object({
    title: z.optional(z.string().min(1).max(255))
});

export const zNoteRequiredRootWritable = zNoteRootWritable;

export const zNotesRootWritable = z.unknown();

export const zNotes7BnoteId7dRootWritable = z.unknown();

export const zWsEditsDocumentData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        documentId: z.uuid()
    }),
    query: z.optional(z.never())
});

export const zListNotesData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        page: z.optional(z.int().gte(1)).default(1),
        limit: z.optional(z.int().gte(1).lte(100)).default(20),
        order: z.optional(z.enum(['asc', 'desc'])),
        sortBy: z.optional(z.enum([
            'createdAt',
            'updatedAt',
            'title'
        ])),
        search: z.optional(z.string())
    }))
});

/**
 * Successful response
 */
export const zListNotesResponse = z.object({
    data: z.array(zNoteRoot),
    pagination: zPaginationRoot.and(z.unknown())
});

export const zCreateNoteData = z.object({
    body: zCreateNoteRequestRoot2Writable,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * Note successfully created
 */
export const zCreateNoteResponse = zNoteRoot.and(z.unknown());

export const zDeleteNoteData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        noteId: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Note successfully deleted
 */
export const zDeleteNoteResponse = z.void();

export const zGetNoteData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        noteId: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Successful response
 */
export const zGetNoteResponse = zNoteRequiredRoot.and(z.unknown());

export const zPatchNoteData = z.object({
    body: zPatchNoteRequestRoot2Writable,
    path: z.object({
        noteId: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Note successfully patched
 */
export const zPatchNoteResponse = zNoteRoot.and(z.unknown());

export const zUpdateNoteData = z.object({
    body: zPutNoteRequestRoot2Writable,
    path: z.object({
        noteId: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * Note successfully updated
 */
export const zUpdateNoteResponse = zNoteRequiredRoot.and(z.unknown());

export const zGetWorkspaceEventsData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        workspaceId: z.uuid()
    }),
    query: z.optional(z.never())
});

/**
 * A persistent stream of events
 */
export const zGetWorkspaceEventsResponse = z.union([
    z.object({
        type: z.literal('NoteMovedEvent_root')
    }).and(zNoteMovedEventRoot),
    z.object({
        type: z.literal('FolderMovedEvent_root')
    }).and(zFolderMovedEventRoot),
    z.object({
        type: z.literal('FolderRenamedEvent_root')
    }).and(zFolderRenamedEventRoot),
    z.object({
        type: z.literal('WorkspaceRenamedEvent_root')
    }).and(zWorkspaceRenamedEventRoot)
]);
