## yaml-language-server: $schema=https://www.schemastore.org/openapi-3.X.json
# vim: ft=yaml.openapi
openapi: 3.0.4

info:
  version: 0.0.0
  title: Notopia API
  license:
    name: MIT
    url: https://github.com/notopia-uit/notopia/blob/main/LICENSE
  x-apiName: share

paths: {}

components:
  schemas:
    DocumentCommittedEvent:
      $ref: ./components/schemas/DocumentCommittedEvent.yaml
    NoteCreatedEvent:
      $ref: ./components/schemas/NoteCreatedEvent.yaml
    NoteDeletedEvent:
      $ref: ./components/schemas/NoteDeletedEvent.yaml
    NoteSearch:
      $ref: ./components/schemas/NoteSearch.yaml
    NoteUpdatedEvent:
      $ref: ./components/schemas/NoteUpdatedEvent.yaml
    UserDeletedEvent:
      $ref: ./components/schemas/UserDeletedEvent.yaml
    UserWorkspaceRoleUpdatedEvent:
      $ref: ./components/schemas/UserWorkspaceRoleUpdatedEvent.yaml
    WorkspaceMemberAddedEvent:
      $ref: ./components/schemas/WorkspaceMemberAddedEvent.yaml
    WorkspaceMemberRemovedEvent:
      $ref: ./components/schemas/WorkspaceMemberRemovedEvent.yaml
