// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/goforj/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/notopia-uit/notopia/pkg/common/otlp"
	"github.com/notopia-uit/notopia/pkg/note/app"
	"github.com/notopia-uit/notopia/pkg/note/components"
	"github.com/notopia-uit/notopia/pkg/note/config"
	"github.com/notopia-uit/notopia/pkg/note/ports"
	"github.com/notopia-uit/notopia/pkg/note/ports/http"
	"github.com/notopia-uit/notopia/pkg/note/ports/rpc"
	"github.com/spf13/viper"
)

// Injectors from wire.go:

func InitializeServer(ctx context.Context) (*ports.Server, error) {
	engine := http.NewGin()
	appApp := app.NewApp()
	strictServer := http.newStrictServer(appApp)
	serverInterface := http.NewServer(strictServer)
	rpcHandler := rpc.NewRPCHandler(appApp)
	validate := components.ProvideValidate()
	viperViper := viper.New()
	configConfig, err := config.NewConfig(validate, viperViper)
	if err != nil {
		return nil, err
	}
	configOTLP := configConfig.OTLP
	serviceName := _wireServiceNameValue
	serviceVersion := _wireServiceVersionValue
	resource, err := otlp.NewResource(serviceName, serviceVersion)
	if err != nil {
		return nil, err
	}
	tracerProvider, err := otlp.NewTracerProvider(ctx, configOTLP, resource)
	if err != nil {
		return nil, err
	}
	meterProvider, err := otlp.NewMeterProvider(ctx, configOTLP, resource)
	if err != nil {
		return nil, err
	}
	httpServiceHandler, err := rpc.NewHTTPServiceHandler(rpcHandler, tracerProvider, meterProvider)
	if err != nil {
		return nil, err
	}
	server := ports.NewServer(engine, serverInterface, httpServiceHandler, configConfig)
	return server, nil
}

var (
	_wireServiceNameValue    = components.ServiceName
	_wireServiceVersionValue = components.ServiceVersion
)
