// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/goforj/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/goforj/wire"
	"github.com/notopia-uit/notopia/internal/note"
	"github.com/notopia-uit/notopia/internal/note/app"
	"github.com/notopia-uit/notopia/internal/note/component"
	"github.com/notopia-uit/notopia/internal/note/config"
	"github.com/notopia-uit/notopia/internal/note/controller/grpc"
	"github.com/notopia-uit/notopia/internal/note/controller/http"
	"github.com/notopia-uit/notopia/internal/note/domain"
	"github.com/notopia-uit/notopia/internal/note/infra/persistence"
	"github.com/notopia-uit/notopia/internal/note/infra/persistence/pg"
	"github.com/notopia-uit/notopia/internal/note/infra/pubsub"
	"github.com/notopia-uit/notopia/internal/note/infra/service"
	"github.com/notopia-uit/notopia/pkg/common/http"
	"github.com/notopia-uit/notopia/pkg/logging"
	"github.com/notopia-uit/notopia/pkg/otel"
)

// Injectors from wire.go:

func InitializeServer(ctx context.Context) (*note.Server, func(), error) {
	validate := components.ProvideValidate()
	viper := config.NewViper()
	configConfig, err := config.New(validate, viper)
	if err != nil {
		return nil, nil, err
	}
	loggingConfig := &configConfig.Log
	stdoutHandler := logging.NewStdoutHandler(loggingConfig)
	serviceName := _wireServiceNameValue
	serviceVersion := _wireServiceVersionValue
	resource, err := otel.NewResource(ctx, serviceName, serviceVersion)
	if err != nil {
		return nil, nil, err
	}
	loggerProvider, cleanup, err := otel.NewLoggerProvider(ctx, resource)
	if err != nil {
		return nil, nil, err
	}
	slogHandler := otel.NewSlogHandler(serviceName, loggerProvider)
	logger := logging.New(stdoutHandler, slogHandler, loggingConfig)
	ginSlogHandlerFunc := commonhttp.NewGinSlogHandler(logger)
	meterProvider, cleanup2, err := otel.NewMeterProvider(ctx, resource)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	tracerProvider, cleanup3, err := otel.NewTracerProvider(ctx, resource)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	otelGinHandlerFunc := commonhttp.NewOtelGinHandler(serviceName, meterProvider, tracerProvider)
	sql := &configConfig.Database
	pool, cleanup4, err := pg.NewPgPool(ctx, tracerProvider, sql)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	db := pg.NewStdlib(pool)
	provider, err := persistence.NewGooseProvider(db, logger)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	persistencePg, err := persistence.NewPg(pool, provider)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	healthManager := http.NewHealthManager(persistencePg)
	engine := commonhttp.NewGin(ginSlogHandlerFunc, otelGinHandlerFunc, healthManager)
	queries := pg.NewQueries(pool)
	pgNote := pg.NewNote(queries)
	createNoteHandler := app.NewCreateNoteHandler(pgNote)
	folder := pg.NewFolder(queries)
	createFolderHandler := app.NewCreateFolderHandler(folder)
	workspace := pg.NewWorkspace(queries)
	createWorkspaceHandler := app.NewCreateWorkspaceHandler(workspace, folder)
	deleteNoteHandler := app.NewDeleteNoteHandler(pgNote)
	deleteWorkspaceHandler := app.NewDeleteWorkspaceHandler(workspace)
	generateDailyNoteHandler := app.NewGenerateDailyNoteHandler(pgNote, folder, workspace)
	services := &configConfig.Services
	authorization := service.NewAuthorization(services)
	unitOfWork := pg.NewUnitOfWork(queries, pool)
	loggerAdapter := pubsub.NewWatermillLogger(logger)
	commandEventMarshaler := pubsub.NewIntegrationMarshaler()
	redis := &configConfig.Redis
	redisClient, cleanup5 := pubsub.NewRedisClient(ctx, redis, logger)
	workspaceEventInternalPubSub, err := pubsub.NewWorkspaceEventInternalPubSub(loggerAdapter, commandEventMarshaler, redisClient)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	workspaceEventHubPubSub := pubsub.NewWorkspaceEventHubPubSub(loggerAdapter)
	workspaceEvent := pubsub.NewWorkspaceEvent(workspaceEventInternalPubSub, workspaceEventHubPubSub)
	moveWorkspaceItemsHandler := app.NewMoveWorkspaceItemsHandler(authorization, pgNote, folder, unitOfWork, workspaceEvent)
	publishNoteHandler := app.NewPublishNoteHandler(pgNote)
	publishWorkspaceHandler := app.NewPublishWorkspaceHandler(workspace)
	renameFolderHandler := app.NewRenameFolderHandler(folder)
	renameNoteHandler := app.NewRenameNoteHandler(pgNote)
	renameWorkspaceHandler := app.NewRenameWorkspaceHandler(workspace)
	restoreTrashedWorkspaceItemsHandler := app.NewRestoreTrashedWorkspaceItemsHandler(pgNote, folder)
	trashWorkspaceItemsHandler := app.NewTrashWorkspaceItemsHandler(pgNote, folder)
	unpublishNoteHandler := app.NewUnpublishNoteHandler(pgNote)
	unpublishWorkspaceHandler := app.NewUnpublishWorkspaceHandler(workspace)
	updateWorkspaceMembersHandler := app.NewUpdateWorkspaceMembersHandler()
	readModel := pg.NewReadModel(pool)
	checkWorkspaceExistsHandler := app.NewCheckWorkspaceExistsHandler(readModel)
	getNoteGraphHandler := app.NewGetNoteGraphHandler(readModel)
	getNoteLinksHandler := app.NewGetNoteLinksHandler(readModel)
	getNotesHandler := app.NewGetNotesHandler(readModel)
	getWorkspaceHandler := app.NewGetWorkspaceHandler(readModel)
	getWorkspaceGraphHandler := app.NewGetWorkspaceGraphHandler(readModel)
	getWorkspaceMembersHandler := app.NewGetWorkspaceMembersHandler(readModel)
	getWorkspaceTreeHandler := app.NewGetWorkspaceTreeHandler(readModel)
	showTrashHandler := app.NewShowTrashHandler(readModel)
	noteService := domain.NewNoteService()
	documentCommittedHandler := app.NewDocumentCommittedHandler(pgNote, noteService)
	appApp := app.NewApp(createNoteHandler, createFolderHandler, createWorkspaceHandler, deleteNoteHandler, deleteWorkspaceHandler, generateDailyNoteHandler, moveWorkspaceItemsHandler, publishNoteHandler, publishWorkspaceHandler, renameFolderHandler, renameNoteHandler, renameWorkspaceHandler, restoreTrashedWorkspaceItemsHandler, trashWorkspaceItemsHandler, unpublishNoteHandler, unpublishWorkspaceHandler, updateWorkspaceMembersHandler, checkWorkspaceExistsHandler, getNoteGraphHandler, getNoteLinksHandler, getNotesHandler, getWorkspaceHandler, getWorkspaceGraphHandler, getWorkspaceMembersHandler, getWorkspaceTreeHandler, showTrashHandler, documentCommittedHandler)
	strictHandler := &http.StrictHandler{
		App:            appApp,
		WorkspaceEvent: workspaceEvent,
	}
	serverInterface := http.NewHandler(strictHandler)
	server := &configConfig.Server
	httpServer, cleanup6, err := http.New(ctx, engine, serverInterface, server, logger)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	handler := grpc.NewHandler(appApp)
	grpcServer, cleanup7, err := grpc.New(ctx, handler, server, tracerProvider, meterProvider, logger)
	if err != nil {
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	noteServer := note.NewServer(httpServer, grpcServer, healthManager, persistencePg, logger)
	return noteServer, func() {
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

var (
	_wireServiceNameValue    = ServiceName
	_wireServiceVersionValue = ServiceVersion
)

// wire.go:

var ProviderSet = wire.NewSet(note.ProviderSet, wire.Value(ServiceName), wire.Value(ServiceVersion))
