// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/goforj/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/goforj/wire"
	"github.com/notopia-uit/notopia/internal/note"
	"github.com/notopia-uit/notopia/internal/note/app"
	"github.com/notopia-uit/notopia/internal/note/component"
	"github.com/notopia-uit/notopia/internal/note/config"
	"github.com/notopia-uit/notopia/internal/note/controller/event"
	"github.com/notopia-uit/notopia/internal/note/controller/grpc"
	"github.com/notopia-uit/notopia/internal/note/controller/health"
	"github.com/notopia-uit/notopia/internal/note/controller/http"
	"github.com/notopia-uit/notopia/internal/note/domain"
	"github.com/notopia-uit/notopia/internal/note/infra/common"
	"github.com/notopia-uit/notopia/internal/note/infra/identity"
	"github.com/notopia-uit/notopia/internal/note/infra/outbox"
	"github.com/notopia-uit/notopia/internal/note/infra/persistence"
	"github.com/notopia-uit/notopia/internal/note/infra/persistence/pgreadmodel"
	"github.com/notopia-uit/notopia/internal/note/infra/persistence/pgrepo"
	"github.com/notopia-uit/notopia/internal/note/infra/service"
	"github.com/notopia-uit/notopia/internal/note/infra/workspaceevent"
	"github.com/notopia-uit/notopia/pkg/common/http"
	"github.com/notopia-uit/notopia/pkg/logging"
	"github.com/notopia-uit/notopia/pkg/otel"
)

// Injectors from wire.go:

func InitializeServer(ctx context.Context) (*note.Server, func(), error) {
	serviceName := _wireServiceNameValue
	serviceVersion := _wireServiceVersionValue
	resource, err := otel.NewResource(ctx, serviceName, serviceVersion)
	if err != nil {
		return nil, nil, err
	}
	tracerProvider, cleanup, err := otel.NewTracerProvider(ctx, resource)
	if err != nil {
		return nil, nil, err
	}
	validate := component.ProvideValidate()
	viper := config.NewViper()
	configConfig, err := config.New(validate, viper)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	sql := &configConfig.Database
	pool, cleanup2, err := persistence.NewPgPool(ctx, tracerProvider, sql)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	db := persistence.NewPgxPoolStdlib(pool)
	log := &configConfig.Log
	stdoutHandler := logging.NewStdoutHandler(log)
	loggerProvider, cleanup3, err := otel.NewLoggerProvider(ctx, resource)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	slogHandler := otel.NewSlogHandler(serviceName, loggerProvider)
	logger := logging.New(stdoutHandler, slogHandler, log)
	provider, err := persistence.NewGooseProvider(db, logger)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	pg, err := persistence.NewPg(pool, provider)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	ginSlogHandlerFunc := commonhttp.NewGinSlogHandler(log, logger)
	otelGinHandlerFunc := commonhttp.NewOtelGinHandler(serviceName)
	engine := commonhttp.NewGin(ginSlogHandlerFunc, otelGinHandlerFunc)
	services := &configConfig.Services
	loggingLogger := otel.MapSlogToGRPCMiddlewareLogger(logger)
	authorization, cleanup4, err := service.NewAuthorization(services, loggingLogger)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	advanced := &configConfig.Advanced
	domainEvent := advanced.DomainEvent
	loggerAdapter := component.NewWatermillLogger(logger)
	configDomainEvent := &advanced.DomainEvent
	defaultPostgreSQLSchema := outbox.NewSchemaAdapter(configDomainEvent)
	fromPersistenceToQSLForwarder := outbox.NewFromPersistenceToQSLForwarder(domainEvent, loggerAdapter, defaultPostgreSQLSchema, serviceName)
	runInTx := pgrepo.NewRunInTx(fromPersistenceToQSLForwarder)
	unitOfWork := pgrepo.NewUnitOfWork(pool, fromPersistenceToQSLForwarder, runInTx)
	createFolderHandler := app.NewCreateFolderHandler(authorization, unitOfWork)
	createNoteHandler := app.NewCreateNoteHandler(authorization, unitOfWork)
	createWorkspaceHandler := app.NewCreateWorkspaceHandler(unitOfWork, authorization)
	permanentlyDeleteFolderHandler := app.NewPermanentlyDeleteFolderHandler(authorization, unitOfWork)
	permanentlyDeleteNoteHandler := app.PermanentlyNewDeleteNoteHandler(authorization, unitOfWork)
	deleteWorkspaceHandler := app.NewDeleteWorkspaceHandler(authorization, unitOfWork)
	moveWorkspaceItemsHandler := app.NewMoveWorkspaceItemsHandler(authorization, unitOfWork)
	permanentlyDeleteWorkspaceItemsHandler := app.NewPermanentlyDeleteWorkspaceItemsHandler(authorization, unitOfWork)
	queries := persistence.NewSQLCQueries(pool)
	pgrepoNote := pgrepo.NewNoTransactionNote(pool, queries, runInTx)
	publishNoteHandler := app.NewPublishNoteHandler(pgrepoNote)
	workspace := pgrepo.NewNoTransactionWorkspace(pool, queries, runInTx)
	publishWorkspaceHandler := app.NewPublishWorkspaceHandler(workspace)
	renameFolderHandler := app.NewRenameFolderHandler(authorization, unitOfWork)
	renameNoteHandler := app.NewRenameNoteHandler(authorization, unitOfWork)
	renameWorkspaceHandler := app.NewRenameWorkspaceHandler(authorization, unitOfWork)
	trashService := domain.NewTrashService()
	restoreTrashedWorkspaceItemsHandler := app.NewRestoreTrashedWorkspaceItemsHandler(authorization, trashService, unitOfWork)
	trashWorkspaceItemsHandler := app.NewTrashWorkspaceItemsHandler(authorization, unitOfWork, trashService)
	unpublishNoteHandler := app.NewUnpublishNoteHandler(pgrepoNote)
	unpublishWorkspaceHandler := app.NewUnpublishWorkspaceHandler(workspace)
	workspaceEvent := &advanced.WorkspaceEvent
	redis := &configConfig.Redis
	redisClient, cleanup5 := workspaceevent.NewRedisClient(ctx, redis, logger)
	workspaceEventHub, err := workspaceevent.NewWorkspaceEventHub(workspaceEvent, loggerAdapter, redisClient, serviceName)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	updateWorkspaceMembersHandler := app.NewUpdateWorkspaceMembersHandler(workspaceEventHub, authorization)
	cmds := &app.Cmds{
		CreateFolderHandler:                    createFolderHandler,
		CreateNoteHandler:                      createNoteHandler,
		CreateWorkspaceHandler:                 createWorkspaceHandler,
		DeleteFolderHandler:                    permanentlyDeleteFolderHandler,
		DeleteNoteHandler:                      permanentlyDeleteNoteHandler,
		DeleteWorkspaceHandler:                 deleteWorkspaceHandler,
		MoveWorkspaceItemsHandler:              moveWorkspaceItemsHandler,
		PermanentlyDeleteWorkspaceItemsHandler: permanentlyDeleteWorkspaceItemsHandler,
		PublishNoteHandler:                     publishNoteHandler,
		PublishWorkspaceHandler:                publishWorkspaceHandler,
		RenameFolderHandler:                    renameFolderHandler,
		RenameNoteHandler:                      renameNoteHandler,
		RenameWorkspaceHandler:                 renameWorkspaceHandler,
		RestoreTrashedWorkspaceItemsHandler:    restoreTrashedWorkspaceItemsHandler,
		TrashWorkspaceItemsHandler:             trashWorkspaceItemsHandler,
		UnpublishNoteHandler:                   unpublishNoteHandler,
		UnpublishWorkspaceHandler:              unpublishWorkspaceHandler,
		UpdateWorkspaceMembersHandler:          updateWorkspaceMembersHandler,
	}
	updateNoteSizeService := domain.NewUpdateNoteSizeService()
	documentCommittedHandler := app.NewDocumentCommittedHandler(pgrepoNote, updateNoteSizeService)
	notifyWorkspaceItemsUpdatedHandler := app.NewNotifyWorkspaceItemsUpdatedHandler(workspaceEventHub)
	events := &app.Events{
		DocumentCommittedHandler:    documentCommittedHandler,
		NotifyWorkspaceItemsUpdated: notifyWorkspaceItemsUpdatedHandler,
	}
	checkWorkspaceSlugExists := pgreadmodel.NewCheckWorkspaceSlugExists(queries)
	checkWorkspaceSlugExistsHandler := app.NewCheckWorkspaceSlugExistsHandler(checkWorkspaceSlugExists)
	getWorkspacesByIDs := pgreadmodel.NewGetWorkspacesByIDs(queries)
	getMyWorkspacesHandler := app.NewGetMyWorkspacesHandler(authorization, getWorkspacesByIDs)
	noteGraph := pgreadmodel.NewNoteGraph(queries)
	getNoteGraphHandler := app.NewGetNoteGraphHandler(authorization, pgrepoNote, noteGraph)
	pgreadmodelNote := pgreadmodel.GetNote(queries)
	getNoteHandler := app.NewGetNoteHandler(authorization, pgrepoNote, pgreadmodelNote)
	noteLinks := pgreadmodel.GetNoteLinks(queries)
	getNoteLinksHandler := app.NewGetNoteLinksHandler(authorization, pgrepoNote, noteLinks)
	workspaceGraph := pgreadmodel.GetWorkspaceGraph(queries)
	getWorkspaceGraphHandler := app.NewGetWorkspaceGraphHandler(authorization, workspaceGraph)
	workspaceBySlug := pgreadmodel.NewWorkspaceBySlug(queries)
	getWorkspaceHandler := app.NewGetWorkspaceBySlugHandler(authorization, workspaceBySlug)
	authentik := &configConfig.Authentik
	identityAuthentik := identity.NewAuthentik(authentik)
	getWorkspaceMembersHandler := app.NewGetWorkspaceMembersHandler(identityAuthentik, authorization)
	workspaceTree := pgreadmodel.NewWorkspaceTree(queries)
	getWorkspaceTreeHandler := app.NewGetWorkspaceTreeHandler(authorization, workspaceTree)
	showTrash := pgreadmodel.NewShowTrash(queries)
	showTrashHandler := app.NewShowTrashHandler(authorization, showTrash)
	appQueries := &app.Queries{
		CheckWorkspaceSlugExistsHandler: checkWorkspaceSlugExistsHandler,
		GetMyWorkspacesHandler:          getMyWorkspacesHandler,
		GetNoteGraphHandler:             getNoteGraphHandler,
		GetNoteHandler:                  getNoteHandler,
		GetNoteLinksHandler:             getNoteLinksHandler,
		GetWorkspaceGraphHandler:        getWorkspaceGraphHandler,
		GetWorkspaceHandler:             getWorkspaceHandler,
		GetWorkspaceMembersHandler:      getWorkspaceMembersHandler,
		GetWorkspaceTreeHandler:         getWorkspaceTreeHandler,
		ShowTrashHandler:                showTrashHandler,
	}
	server := &app.Server{
		Cmds:              cmds,
		Events:            events,
		Queries:           appQueries,
		WorkspaceEventHub: workspaceEventHub,
	}
	configServer := &configConfig.Server
	strictHandler := http.NewStrictHandler(server, configServer, workspaceEventHub)
	serverInterface := http.NewHandler(strictHandler)
	httpHTTP, cleanup6, err := http.New(ctx, engine, serverInterface, configServer, logger)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	serviceServer := grpc.NewServiceServer(server)
	grpcGRPC, cleanup7, err := grpc.New(ctx, serviceServer, configServer, loggingLogger)
	if err != nil {
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	kafka := &configConfig.Kafka
	watermillKafkaTracer := otel.NewOTELSaramaTracer(tracerProvider)
	jsonMarshaler := component.NewWatermillJsonMarshaler()
	eventEvent, err := event.NewEvent(kafka, server, watermillKafkaTracer, loggerAdapter, jsonMarshaler, configDomainEvent)
	if err != nil {
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	kafkaPublisher, err := common.NewKafkaPublisher(kafka, loggerAdapter, watermillKafkaTracer)
	if err != nil {
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	outboxOutbox, err := outbox.NewOutbox(kafkaPublisher, loggerAdapter, defaultPostgreSQLSchema, pool)
	if err != nil {
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	healthHealth := health.New(pg, configServer, workspaceEventHub, redisClient)
	meterProvider, cleanup8, err := otel.NewMeterProvider(ctx, resource)
	if err != nil {
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	global := otel.ProvideGlobal(loggerProvider, meterProvider, tracerProvider)
	noteServer := note.NewServer(pg, httpHTTP, grpcGRPC, eventEvent, workspaceEventHub, outboxOutbox, healthHealth, logger, global)
	return noteServer, func() {
		cleanup8()
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

var (
	_wireServiceNameValue    = ServiceName
	_wireServiceVersionValue = ServiceVersion
)

// wire.go:

var ProviderSet = wire.NewSet(note.ProviderSet, wire.Value(ServiceName), wire.Value(ServiceVersion))
