sonar.projectKey=notopia-uit_authorization
sonar.organization=notopia-uit
sonar.go.activate=true
sonar.dre.go.activate=true
sonar.go.exclusions**/vendor/**, **/testdata/**, **/pkg/pb/**, **/pkg/api/**
sonar.project.monorepo.enabled=true
