// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://api.notopia.localhost' | (string & {});
};

export type ShareDocumentCommittedEvent = ShareDocument & {
    userId: string;
    tags: Array<string>;
    outgoingLinkIds: Array<string>;
};

export type ShareNoteCreatedEvent = {
    id: string;
    workspaceId: string;
    name: string;
    icon: string | null;
};

export type ShareNoteDeletedEvent = {
    id: string;
};

export type ShareNoteSearch = {
    id: string;
    workspaceId: string;
    folderId: string;
    folderName: string;
    name: string;
    /**
     * Plain text content
     */
    plainTextContent: string;
    tags: Array<string>;
    trashed?: ShareTrashed;
};

export type ShareNoteUpdatedEvent = {
    id: string;
    workspaceId: string;
    name: string;
    icon: string | null;
    folderId: string;
    folderName: string;
    trashed?: ShareTrashed;
    updatedAt: Date;
};

export type ShareUserDeletedEvent = {
    id: ShareId;
};

export type ShareUserWorkspaceRoleUpdatedEvent = {
    workspaceId: SharePropertiesId;
    userId: ShareId;
    role: ShareWorkspaceRole;
};

export type ShareWorkspaceMemberAddedEvent = {
    workspaceId: SharePropertiesId;
    userId: ShareId;
    role: ShareWorkspaceRole;
};

export type ShareWorkspaceMemberRemovedEvent = {
    workspaceId: SharePropertiesId;
    userId: ShareId;
};

/**
 * BlockNote model
 */
export type ShareDocumentContent = Array<unknown>;

export type ShareDocument = {
    id: string;
    content: ShareDocumentContent;
};

export const ShareTrashedBy = { PURPOSE: 'purpose', PARENT: 'parent' } as const;

export type ShareTrashedBy = typeof ShareTrashedBy[keyof typeof ShareTrashedBy];

export type ShareTrashed = {
    by: ShareTrashedBy;
    at: Date;
};

/**
 * User ID from Authentik (need to change subject mode to User's ID instead of hashed)
 */
export type ShareId = string;

export type SharePropertiesId = string;

export const ShareWorkspaceRole = {
    OWNER: 'owner',
    EDITOR: 'editor',
    VIEWER: 'viewer'
} as const;

export type ShareWorkspaceRole = typeof ShareWorkspaceRole[keyof typeof ShareWorkspaceRole];

export type DocumentId = string;

export type DocumentError = {
    /**
     * Error code
     */
    code: string;
    /**
     * Human-readable error message
     */
    message: string;
    /**
     * URL with more information about the error
     */
    more_info?: string;
};

export type DocumentRevision = {
    readonly id: string;
    name: string | null;
    readonly createdAt: Date;
};

export type DocumentPagination = {
    /**
     * Current page number
     */
    page: number;
    /**
     * Number of items per page
     */
    limit: number;
    /**
     * Total number of items
     */
    total: number;
    /**
     * Total number of pages
     */
    totalPages: number;
    /**
     * Whether there is a next page
     */
    hasNext: boolean;
    /**
     * Whether there is a previous page
     */
    hasPrev: boolean;
};

/**
 * BlockNote model
 */
export type DocumentDocumentContent = Array<unknown>;

export type DocumentRevisionWithContent = DocumentRevision & {
    content: DocumentDocumentContent;
};

export type DocumentName = string | null;

export type NoteId = string;

export const NoteTrashedBy = { PURPOSE: 'purpose', PARENT: 'parent' } as const;

export type NoteTrashedBy = typeof NoteTrashedBy[keyof typeof NoteTrashedBy];

export type NoteFolder = {
    readonly id: string;
    name: string;
    icon: string | null;
    parentId: NoteId;
    workspaceId: string;
    readonly updatedAt: Date;
    readonly trashed: {
        by: NoteTrashedBy;
        at: Date;
    } | null;
};

export type NoteError = {
    /**
     * Error code
     */
    code: string;
    /**
     * Human-readable error message
     */
    message: string;
    /**
     * URL with more information about the error
     */
    more_info?: string;
};

export type NoteName = string;

export type NoteNote = {
    readonly id: string;
    /**
     * Can be empty string when creating but will be set to "Untitled Note" internally
     */
    name: string;
    icon: string | null;
    folderId: NoteId;
    readonly tags: Array<string>;
    readonly updatedAt: Date;
    readonly trashed: {
        by: NoteTrashedBy;
        at: Date;
    } | null;
};

export type NotePropertiesId = string;

export type NoteGraph = {
    nodes: Array<{
        /**
         * Can be either a note ID or a hashtag prefixed tag name
         */
        id: string;
        /**
         * Can be either a note name or a tag name (no hashtag prefix)
         */
        name: string;
        type: 'note' | 'tag';
        /**
         * Optional weight for the note node, rounded to 1 decimal place
         */
        weight?: number;
    }>;
    links: Array<{
        /**
         * The ID of the source node (note id or hashtag prefixed tag name)
         */
        source: string;
        /**
         * The ID of the target node (note id or hashtag prefixed tag name)
         */
        target: string;
    }>;
};

/**
 * Can be empty string when creating but will be set to "Untitled Note" internally
 */
export type NotePropertiesName = string;

export type NoteIcon = string | null;

export type NoteNoteLink = {
    id: NotePropertiesId;
    name: NotePropertiesName;
    icon: NoteIcon;
};

export type NoteSlug = string;

export type NoteWorkspace = {
    readonly id: string;
    slug: string;
    name: string;
};

export const NoteWorkspaceRole = {
    OWNER: 'owner',
    EDITOR: 'editor',
    VIEWER: 'viewer'
} as const;

export type NoteWorkspaceRole = typeof NoteWorkspaceRole[keyof typeof NoteWorkspaceRole];

export type NoteUserWorkspace = {
    workspace: NoteWorkspace;
    role: NoteWorkspaceRole;
};

export type NoteWorkspacePropertiesId = string;

export type NoteHeartBeatWorkspaceEvent = {
    event: 'HeartBeatWorkspaceEvent';
    timestamp: Date;
};

export type NoteWorkspaceDeletedEvent = {
    id: string;
    event: 'WorkspaceDeletedEvent';
    data: {
        id: NoteWorkspacePropertiesId;
    };
};

export type NoteWorkspaceItemsUpdatedEvent = {
    id: string;
    event: 'WorkspaceItemsUpdatedEvent';
    data: {
        workspaceId: NoteWorkspacePropertiesId;
    };
};

export type NoteWorkspaceMembersUpdatedEvent = {
    id: string;
    event: 'WorkspaceMembersUpdatedEvent';
    data: {
        workspaceId: NoteWorkspacePropertiesId;
    };
};

export type NoteWorkspacePropertiesName = string;

export type NoteWorkspaceRenamedEvent = {
    id: string;
    event: 'WorkspaceRenamedEvent';
    data: {
        id: NoteWorkspacePropertiesId;
        name: NoteWorkspacePropertiesName;
    };
};

export type NoteWorkspaceSlugChangedEvent = {
    id: string;
    event: 'WorkspaceSlugChangedEvent';
    data: {
        id: NoteWorkspacePropertiesId;
        slug: NoteSlug;
    };
};

/**
 * User ID from Authentik (need to change subject mode to User's ID instead of hashed)
 */
export type NoteUserPropertiesId = string;

/**
 * Full name from Authentik
 */
export type NoteUserPropertiesName = string | null;

export type NoteWorkspaceMember = {
    id: NoteUserPropertiesId;
    name?: NoteUserPropertiesName;
    role: NoteWorkspaceRole;
};

export type NoteTrashed = {
    by: NoteTrashedBy;
    at: Date;
};

export type NoteTrashedNote = {
    id: string;
    readonly name: string;
    trashed: NoteTrashed;
};

export type NoteTrashedFolder = {
    id: string;
    readonly name: string;
    trashed: NoteTrashed;
};

export type NotePropertiesIcon = string | null;

export type NoteUpdatedAt = Date;

export type NoteWorkspaceTreeNote = {
    id: NotePropertiesId;
    name: NotePropertiesName;
    icon: NoteIcon;
    updatedAt: NoteUpdatedAt;
};

export type NoteWorkspaceTreeFolder = {
    id: NoteId;
    name: NoteName;
    icon: NotePropertiesIcon;
    notes: Array<NoteWorkspaceTreeNote>;
    children: Array<NoteWorkspaceTreeFolder>;
    updatedAt: NotePropertiesUpdatedAt;
};

export type NotePropertiesUpdatedAt = Date;

export type ShareUserWorkspaceRoleUpdatedEventWritable = {
    userId: ShareId;
    role: ShareWorkspaceRole;
};

export type ShareWorkspaceMemberAddedEventWritable = {
    userId: ShareId;
    role: ShareWorkspaceRole;
};

export type ShareWorkspaceMemberRemovedEventWritable = {
    userId: ShareId;
};

/**
 * BlockNote model
 */
export type ShareDocumentContentWritable = Array<unknown>;

export type DocumentRevisionWritable = {
    name: string | null;
};

/**
 * BlockNote model
 */
export type DocumentDocumentContentWritable = Array<unknown>;

export type DocumentRevisionWithContentWritable = DocumentRevisionWritable & {
    content: DocumentDocumentContentWritable;
};

export type NoteFolderWritable = {
    name: string;
    icon: string | null;
    workspaceId: string;
};

export type NoteNoteWritable = {
    /**
     * Can be empty string when creating but will be set to "Untitled Note" internally
     */
    name: string;
    icon: string | null;
};

export type NoteNoteLinkWritable = {
    name: NotePropertiesName;
    icon: NoteIcon;
};

export type NoteWorkspaceWritable = {
    slug: string;
    name: string;
};

export type NoteUserWorkspaceWritable = {
    workspace: NoteWorkspaceWritable;
    role: NoteWorkspaceRole;
};

export type NoteWorkspaceDeletedEventWritable = {
    id: string;
    event: 'WorkspaceDeletedEvent';
};

export type NoteWorkspaceItemsUpdatedEventWritable = {
    id: string;
    event: 'WorkspaceItemsUpdatedEvent';
};

export type NoteWorkspaceMembersUpdatedEventWritable = {
    id: string;
    event: 'WorkspaceMembersUpdatedEvent';
};

export type NoteWorkspaceRenamedEventWritable = {
    id: string;
    event: 'WorkspaceRenamedEvent';
    data: {
        name: NoteWorkspacePropertiesName;
    };
};

export type NoteWorkspaceSlugChangedEventWritable = {
    id: string;
    event: 'WorkspaceSlugChangedEvent';
    data: {
        slug: NoteSlug;
    };
};

export type NoteWorkspaceMemberWritable = {
    id: NoteUserPropertiesId;
    role: NoteWorkspaceRole;
};

export type NoteTrashedNoteWritable = {
    id: string;
    trashed: NoteTrashed;
};

export type NoteTrashedFolderWritable = {
    id: string;
    trashed: NoteTrashed;
};

export type NoteWorkspaceTreeNoteWritable = {
    name: NotePropertiesName;
    icon: NoteIcon;
};

export type NoteWorkspaceTreeFolderWritable = {
    name: NoteName;
    icon: NotePropertiesIcon;
    notes: Array<NoteWorkspaceTreeNoteWritable>;
    children: Array<NoteWorkspaceTreeFolderWritable>;
};

/**
 * Unique identifier of the document (note)
 */
export type DocumentDocumentIdPath = DocumentId;

export type DocumentDocumentIdQuery = DocumentId;

/**
 * Page number for pagination
 */
export type DocumentPageQuery = number;

/**
 * Number of items per page
 */
export type DocumentLimitQuery = number;

export type DocumentRevisionIdPath = string;

export type NoteFolderIdPath = NoteId;

export type NoteNoteIdPath = NotePropertiesId;

export type NoteWorkspaceSlugPath = NoteSlug;

export type NoteWorkspaceIdPath = NoteWorkspacePropertiesId;

export type GetDocumentAttachmentUploadUrlData = {
    body?: never;
    path: {
        /**
         * Unique identifier of the document (note)
         */
        documentId: DocumentId;
    };
    query?: never;
    url: '/document/documents/{documentId}/attachment-url';
};

export type GetDocumentAttachmentUploadUrlErrors = {
    /**
     * Bad Request Error response
     */
    400: DocumentError;
    /**
     * The error response body returned when JWT validation or OPA authorization fails.
     */
    401: {
        /**
         * The category of the error encountered during the middleware lifecycle.
         */
        type: 'ExtractToken' | 'VerifyToken' | 'FetchJWKS' | 'OPA';
        /**
         * A descriptive message providing technical context for the failure.
         */
        details: string;
        /**
         * An optional, developer-defined message, often populated by OPA policy violations.
         */
        custom_message: string | null;
    };
    /**
     * Not Found Error response
     */
    404: DocumentError;
    /**
     * Internal Server Error response
     */
    500: DocumentError;
};

export type GetDocumentAttachmentUploadUrlError = GetDocumentAttachmentUploadUrlErrors[keyof GetDocumentAttachmentUploadUrlErrors];

export type GetDocumentAttachmentUploadUrlResponses = {
    /**
     * Presigned URL
     */
    200: {
        uploadUrl: string;
        url: string;
    };
};

export type GetDocumentAttachmentUploadUrlResponse = GetDocumentAttachmentUploadUrlResponses[keyof GetDocumentAttachmentUploadUrlResponses];

export type CommitDocumentData = {
    body?: never;
    path: {
        /**
         * Unique identifier of the document (note)
         */
        documentId: DocumentId;
    };
    query?: never;
    url: '/document/documents/{documentId}/commit';
};

export type CommitDocumentErrors = {
    /**
     * Bad Request Error response
     */
    400: DocumentError;
    /**
     * The error response body returned when JWT validation or OPA authorization fails.
     */
    401: {
        /**
         * The category of the error encountered during the middleware lifecycle.
         */
        type: 'ExtractToken' | 'VerifyToken' | 'FetchJWKS' | 'OPA';
        /**
         * A descriptive message providing technical context for the failure.
         */
        details: string;
        /**
         * An optional, developer-defined message, often populated by OPA policy violations.
         */
        custom_message: string | null;
    };
    /**
     * Not Found Error response
     */
    404: DocumentError;
    /**
     * Internal Server Error response
     */
    500: DocumentError;
};

export type CommitDocumentError = CommitDocumentErrors[keyof CommitDocumentErrors];

export type CommitDocumentResponses = {
    /**
     * Document revision committed successfully
     */
    204: void;
};

export type CommitDocumentResponse = CommitDocumentResponses[keyof CommitDocumentResponses];

export type GetRevisionsData = {
    body?: never;
    path?: never;
    query: {
        documentId: DocumentId;
        /**
         * Page number for pagination
         */
        page?: number;
        /**
         * Number of items per page
         */
        limit?: number;
    };
    url: '/document/revisions';
};

export type GetRevisionsErrors = {
    /**
     * Bad Request Error response
     */
    400: DocumentError;
    /**
     * The error response body returned when JWT validation or OPA authorization fails.
     */
    401: {
        /**
         * The category of the error encountered during the middleware lifecycle.
         */
        type: 'ExtractToken' | 'VerifyToken' | 'FetchJWKS' | 'OPA';
        /**
         * A descriptive message providing technical context for the failure.
         */
        details: string;
        /**
         * An optional, developer-defined message, often populated by OPA policy violations.
         */
        custom_message: string | null;
    };
    /**
     * Not Found Error response
     */
    404: DocumentError;
    /**
     * Internal Server Error response
     */
    500: DocumentError;
};

export type GetRevisionsError = GetRevisionsErrors[keyof GetRevisionsErrors];

export type GetRevisionsResponses = {
    /**
     * Revisions
     */
    200: {
        data: Array<DocumentRevision>;
        pagination: DocumentPagination;
    };
};

export type GetRevisionsResponse = GetRevisionsResponses[keyof GetRevisionsResponses];

export type DeleteRevisionData = {
    body?: never;
    path: {
        revisionId: string;
    };
    query?: never;
    url: '/document/revisions/{revisionId}';
};

export type DeleteRevisionErrors = {
    /**
     * Bad Request Error response
     */
    400: DocumentError;
    /**
     * The error response body returned when JWT validation or OPA authorization fails.
     */
    401: {
        /**
         * The category of the error encountered during the middleware lifecycle.
         */
        type: 'ExtractToken' | 'VerifyToken' | 'FetchJWKS' | 'OPA';
        /**
         * A descriptive message providing technical context for the failure.
         */
        details: string;
        /**
         * An optional, developer-defined message, often populated by OPA policy violations.
         */
        custom_message: string | null;
    };
    /**
     * Forbidden Error response
     */
    403: DocumentError;
    /**
     * Not Found Error response
     */
    404: DocumentError;
    /**
     * Internal Server Error response
     */
    500: DocumentError;
};

export type DeleteRevisionError = DeleteRevisionErrors[keyof DeleteRevisionErrors];

export type DeleteRevisionResponses = {
    /**
     * Revision deleted successfully
     */
    204: void;
};

export type DeleteRevisionResponse = DeleteRevisionResponses[keyof DeleteRevisionResponses];

export type GetRevisionWithContentData = {
    body?: never;
    path: {
        revisionId: string;
    };
    query?: never;
    url: '/document/revisions/{revisionId}';
};

export type GetRevisionWithContentErrors = {
    /**
     * Bad Request Error response
     */
    400: DocumentError;
    /**
     * The error response body returned when JWT validation or OPA authorization fails.
     */
    401: {
        /**
         * The category of the error encountered during the middleware lifecycle.
         */
        type: 'ExtractToken' | 'VerifyToken' | 'FetchJWKS' | 'OPA';
        /**
         * A descriptive message providing technical context for the failure.
         */
        details: string;
        /**
         * An optional, developer-defined message, often populated by OPA policy violations.
         */
        custom_message: string | null;
    };
    /**
     * Forbidden Error response
     */
    403: DocumentError;
    /**
     * Not Found Error response
     */
    404: DocumentError;
    /**
     * Internal Server Error response
     */
    500: DocumentError;
};

export type GetRevisionWithContentError = GetRevisionWithContentErrors[keyof GetRevisionWithContentErrors];

export type GetRevisionWithContentResponses = {
    /**
     * Revision retrieved successfully
     */
    200: DocumentRevisionWithContent;
};

export type GetRevisionWithContentResponse = GetRevisionWithContentResponses[keyof GetRevisionWithContentResponses];

export type RenameRevisionData = {
    body: {
        name: DocumentName;
    };
    path: {
        revisionId: string;
    };
    query?: never;
    url: '/document/revisions/{revisionId}/rename';
};

export type RenameRevisionErrors = {
    /**
     * Bad Request Error response
     */
    400: DocumentError;
    /**
     * The error response body returned when JWT validation or OPA authorization fails.
     */
    401: {
        /**
         * The category of the error encountered during the middleware lifecycle.
         */
        type: 'ExtractToken' | 'VerifyToken' | 'FetchJWKS' | 'OPA';
        /**
         * A descriptive message providing technical context for the failure.
         */
        details: string;
        /**
         * An optional, developer-defined message, often populated by OPA policy violations.
         */
        custom_message: string | null;
    };
    /**
     * Not Found Error response
     */
    404: DocumentError;
    /**
     * Internal Server Error response
     */
    500: DocumentError;
};

export type RenameRevisionError = RenameRevisionErrors[keyof RenameRevisionErrors];

export type RenameRevisionResponses = {
    /**
     * Revision renamed successfully
     */
    204: void;
};

export type RenameRevisionResponse = RenameRevisionResponses[keyof RenameRevisionResponses];

export type CreateFolderData = {
    body: NoteFolderWritable;
    path?: never;
    query?: never;
    url: '/note/folders';
};

export type CreateFolderErrors = {
    /**
     * Bad Request Error response
     */
    400: NoteError;
    /**
     * The error response body returned when JWT validation or OPA authorization fails.
     */
    401: {
        /**
         * The category of the error encountered during the middleware lifecycle.
         */
        type: 'ExtractToken' | 'VerifyToken' | 'FetchJWKS' | 'OPA';
        /**
         * A descriptive message providing technical context for the failure.
         */
        details: string;
        /**
         * An optional, developer-defined message, often populated by OPA policy violations.
         */
        custom_message: string | null;
    };
    /**
     * Internal Server Error response
     */
    500: NoteError;
};

export type CreateFolderError = CreateFolderErrors[keyof CreateFolderErrors];

export type CreateFolderResponses = {
    /**
     * Folder successfully created
     */
    201: unknown;
};

export type PermanentlyDeleteFolderData = {
    body?: never;
    path: {
        folderId: NoteId;
    };
    query?: never;
    url: '/note/folders/{folderId}';
};

export type PermanentlyDeleteFolderErrors = {
    /**
     * Bad Request Error response
     */
    400: NoteError;
    /**
     * The error response body returned when JWT validation or OPA authorization fails.
     */
    401: {
        /**
         * The category of the error encountered during the middleware lifecycle.
         */
        type: 'ExtractToken' | 'VerifyToken' | 'FetchJWKS' | 'OPA';
        /**
         * A descriptive message providing technical context for the failure.
         */
        details: string;
        /**
         * An optional, developer-defined message, often populated by OPA policy violations.
         */
        custom_message: string | null;
    };
    /**
     * Forbidden Error response
     */
    403: NoteError;
    /**
     * Not Found Error response
     */
    404: NoteError;
    /**
     * Internal Server Error response
     */
    500: NoteError;
};

export type PermanentlyDeleteFolderError = PermanentlyDeleteFolderErrors[keyof PermanentlyDeleteFolderErrors];

export type PermanentlyDeleteFolderResponses = {
    /**
     * Folder successfully deleted
     */
    204: void;
};

export type PermanentlyDeleteFolderResponse = PermanentlyDeleteFolderResponses[keyof PermanentlyDeleteFolderResponses];

export type RenameFolderData = {
    body: {
        name: NoteName;
    };
    path: {
        folderId: NoteId;
    };
    query?: never;
    url: '/note/folders/{folderId}/rename';
};

export type RenameFolderErrors = {
    /**
     * Bad Request Error response
     */
    400: NoteError;
    /**
     * The error response body returned when JWT validation or OPA authorization fails.
     */
    401: {
        /**
         * The category of the error encountered during the middleware lifecycle.
         */
        type: 'ExtractToken' | 'VerifyToken' | 'FetchJWKS' | 'OPA';
        /**
         * A descriptive message providing technical context for the failure.
         */
        details: string;
        /**
         * An optional, developer-defined message, often populated by OPA policy violations.
         */
        custom_message: string | null;
    };
    /**
     * Not Found Error response
     */
    404: NoteError;
    /**
     * Internal Server Error response
     */
    500: NoteError;
};

export type RenameFolderError = RenameFolderErrors[keyof RenameFolderErrors];

export type RenameFolderResponses = {
    /**
     * Folder renamed successfully
     */
    204: void;
};

export type RenameFolderResponse = RenameFolderResponses[keyof RenameFolderResponses];

export type CreateNoteData = {
    body: NoteNoteWritable;
    path?: never;
    query?: never;
    url: '/note/notes';
};

export type CreateNoteErrors = {
    /**
     * Bad Request Error response
     */
    400: NoteError;
    /**
     * The error response body returned when JWT validation or OPA authorization fails.
     */
    401: {
        /**
         * The category of the error encountered during the middleware lifecycle.
         */
        type: 'ExtractToken' | 'VerifyToken' | 'FetchJWKS' | 'OPA';
        /**
         * A descriptive message providing technical context for the failure.
         */
        details: string;
        /**
         * An optional, developer-defined message, often populated by OPA policy violations.
         */
        custom_message: string | null;
    };
    /**
     * Internal Server Error response
     */
    500: NoteError;
};

export type CreateNoteError = CreateNoteErrors[keyof CreateNoteErrors];

export type CreateNoteResponses = {
    /**
     * Note successfully created
     */
    201: unknown;
};

export type PermanentlyDeleteNoteData = {
    body?: never;
    path: {
        noteId: NotePropertiesId;
    };
    query?: never;
    url: '/note/notes/{noteId}';
};

export type PermanentlyDeleteNoteErrors = {
    /**
     * Bad Request Error response
     */
    400: NoteError;
    /**
     * The error response body returned when JWT validation or OPA authorization fails.
     */
    401: {
        /**
         * The category of the error encountered during the middleware lifecycle.
         */
        type: 'ExtractToken' | 'VerifyToken' | 'FetchJWKS' | 'OPA';
        /**
         * A descriptive message providing technical context for the failure.
         */
        details: string;
        /**
         * An optional, developer-defined message, often populated by OPA policy violations.
         */
        custom_message: string | null;
    };
    /**
     * Forbidden Error response
     */
    403: NoteError;
    /**
     * Not Found Error response
     */
    404: NoteError;
    /**
     * Internal Server Error response
     */
    500: NoteError;
};

export type PermanentlyDeleteNoteError = PermanentlyDeleteNoteErrors[keyof PermanentlyDeleteNoteErrors];

export type PermanentlyDeleteNoteResponses = {
    /**
     * Note successfully deleted
     */
    204: void;
};

export type PermanentlyDeleteNoteResponse = PermanentlyDeleteNoteResponses[keyof PermanentlyDeleteNoteResponses];

export type GetNoteData = {
    body?: never;
    path: {
        noteId: NotePropertiesId;
    };
    query?: {
        includeTrashed?: boolean;
    };
    url: '/note/notes/{noteId}';
};

export type GetNoteErrors = {
    /**
     * Bad Request Error response
     */
    400: NoteError;
    /**
     * The error response body returned when JWT validation or OPA authorization fails.
     */
    401: {
        /**
         * The category of the error encountered during the middleware lifecycle.
         */
        type: 'ExtractToken' | 'VerifyToken' | 'FetchJWKS' | 'OPA';
        /**
         * A descriptive message providing technical context for the failure.
         */
        details: string;
        /**
         * An optional, developer-defined message, often populated by OPA policy violations.
         */
        custom_message: string | null;
    };
    /**
     * Forbidden Error response
     */
    403: NoteError;
    /**
     * Not Found Error response
     */
    404: NoteError;
    /**
     * Internal Server Error response
     */
    500: NoteError;
};

export type GetNoteError = GetNoteErrors[keyof GetNoteErrors];

export type GetNoteResponses = {
    /**
     * Successful response
     */
    200: NoteNote;
};

export type GetNoteResponse = GetNoteResponses[keyof GetNoteResponses];

export type GetNoteGraphData = {
    body?: never;
    path: {
        noteId: NotePropertiesId;
    };
    query?: {
        depth?: number;
    };
    url: '/note/notes/{noteId}/graph';
};

export type GetNoteGraphErrors = {
    /**
     * Bad Request Error response
     */
    400: NoteError;
    /**
     * The error response body returned when JWT validation or OPA authorization fails.
     */
    401: {
        /**
         * The category of the error encountered during the middleware lifecycle.
         */
        type: 'ExtractToken' | 'VerifyToken' | 'FetchJWKS' | 'OPA';
        /**
         * A descriptive message providing technical context for the failure.
         */
        details: string;
        /**
         * An optional, developer-defined message, often populated by OPA policy violations.
         */
        custom_message: string | null;
    };
    /**
     * Forbidden Error response
     */
    403: NoteError;
    /**
     * Not Found Error response
     */
    404: NoteError;
    /**
     * Internal Server Error response
     */
    500: NoteError;
};

export type GetNoteGraphError = GetNoteGraphErrors[keyof GetNoteGraphErrors];

export type GetNoteGraphResponses = {
    /**
     * Note graph
     */
    200: NoteGraph;
};

export type GetNoteGraphResponse = GetNoteGraphResponses[keyof GetNoteGraphResponses];

export type GetNoteLinksData = {
    body?: never;
    path: {
        noteId: NotePropertiesId;
    };
    query?: {
        outgoingLinks?: boolean;
        backlinks?: boolean;
    };
    url: '/note/notes/{noteId}/links';
};

export type GetNoteLinksErrors = {
    /**
     * Bad Request Error response
     */
    400: NoteError;
    /**
     * The error response body returned when JWT validation or OPA authorization fails.
     */
    401: {
        /**
         * The category of the error encountered during the middleware lifecycle.
         */
        type: 'ExtractToken' | 'VerifyToken' | 'FetchJWKS' | 'OPA';
        /**
         * A descriptive message providing technical context for the failure.
         */
        details: string;
        /**
         * An optional, developer-defined message, often populated by OPA policy violations.
         */
        custom_message: string | null;
    };
    /**
     * Not Found Error response
     */
    404: NoteError;
    /**
     * Internal Server Error response
     */
    500: NoteError;
};

export type GetNoteLinksError = GetNoteLinksErrors[keyof GetNoteLinksErrors];

export type GetNoteLinksResponses = {
    /**
     * Note links
     */
    200: {
        outgoingLinks?: Array<NoteNoteLink>;
        backlinks?: Array<NoteNoteLink>;
    };
};

export type GetNoteLinksResponse = GetNoteLinksResponses[keyof GetNoteLinksResponses];

export type PublishNoteData = {
    body?: never;
    path: {
        noteId: NotePropertiesId;
    };
    query?: never;
    url: '/note/notes/{noteId}/publish';
};

export type PublishNoteErrors = {
    /**
     * Bad Request Error response
     */
    400: NoteError;
    /**
     * The error response body returned when JWT validation or OPA authorization fails.
     */
    401: {
        /**
         * The category of the error encountered during the middleware lifecycle.
         */
        type: 'ExtractToken' | 'VerifyToken' | 'FetchJWKS' | 'OPA';
        /**
         * A descriptive message providing technical context for the failure.
         */
        details: string;
        /**
         * An optional, developer-defined message, often populated by OPA policy violations.
         */
        custom_message: string | null;
    };
    /**
     * Not Found Error response
     */
    404: NoteError;
    /**
     * Internal Server Error response
     */
    500: NoteError;
};

export type PublishNoteError = PublishNoteErrors[keyof PublishNoteErrors];

export type PublishNoteResponses = {
    /**
     * Note published successfully
     */
    204: void;
};

export type PublishNoteResponse = PublishNoteResponses[keyof PublishNoteResponses];

export type RenameNoteData = {
    body: {
        name: NotePropertiesName;
    };
    path: {
        noteId: NotePropertiesId;
    };
    query?: never;
    url: '/note/notes/{noteId}/rename';
};

export type RenameNoteErrors = {
    /**
     * Bad Request Error response
     */
    400: NoteError;
    /**
     * The error response body returned when JWT validation or OPA authorization fails.
     */
    401: {
        /**
         * The category of the error encountered during the middleware lifecycle.
         */
        type: 'ExtractToken' | 'VerifyToken' | 'FetchJWKS' | 'OPA';
        /**
         * A descriptive message providing technical context for the failure.
         */
        details: string;
        /**
         * An optional, developer-defined message, often populated by OPA policy violations.
         */
        custom_message: string | null;
    };
    /**
     * Not Found Error response
     */
    404: NoteError;
    /**
     * Internal Server Error response
     */
    500: NoteError;
};

export type RenameNoteError = RenameNoteErrors[keyof RenameNoteErrors];

export type RenameNoteResponses = {
    /**
     * Note renamed successfully
     */
    204: void;
};

export type RenameNoteResponse = RenameNoteResponses[keyof RenameNoteResponses];

export type UnpublishNoteData = {
    body?: never;
    path: {
        noteId: NotePropertiesId;
    };
    query?: never;
    url: '/note/notes/{noteId}/unpublish';
};

export type UnpublishNoteErrors = {
    /**
     * Bad Request Error response
     */
    400: NoteError;
    /**
     * The error response body returned when JWT validation or OPA authorization fails.
     */
    401: {
        /**
         * The category of the error encountered during the middleware lifecycle.
         */
        type: 'ExtractToken' | 'VerifyToken' | 'FetchJWKS' | 'OPA';
        /**
         * A descriptive message providing technical context for the failure.
         */
        details: string;
        /**
         * An optional, developer-defined message, often populated by OPA policy violations.
         */
        custom_message: string | null;
    };
    /**
     * Not Found Error response
     */
    404: NoteError;
    /**
     * Internal Server Error response
     */
    500: NoteError;
};

export type UnpublishNoteError = UnpublishNoteErrors[keyof UnpublishNoteErrors];

export type UnpublishNoteResponses = {
    /**
     * Note unpublished successfully
     */
    204: void;
};

export type UnpublishNoteResponse = UnpublishNoteResponses[keyof UnpublishNoteResponses];

export type GetWorkspaceData = {
    body?: never;
    path: {
        workspaceSlug: NoteSlug;
    };
    query?: never;
    url: '/note/workspaces-by-slug/{workspaceSlug}';
};

export type GetWorkspaceErrors = {
    /**
     * Bad Request Error response
     */
    400: NoteError;
    /**
     * The error response body returned when JWT validation or OPA authorization fails.
     */
    401: {
        /**
         * The category of the error encountered during the middleware lifecycle.
         */
        type: 'ExtractToken' | 'VerifyToken' | 'FetchJWKS' | 'OPA';
        /**
         * A descriptive message providing technical context for the failure.
         */
        details: string;
        /**
         * An optional, developer-defined message, often populated by OPA policy violations.
         */
        custom_message: string | null;
    };
    /**
     * Not Found Error response
     */
    404: NoteError;
    /**
     * Internal Server Error response
     */
    500: NoteError;
};

export type GetWorkspaceError = GetWorkspaceErrors[keyof GetWorkspaceErrors];

export type GetWorkspaceResponses = {
    /**
     * OK
     */
    200: NoteWorkspace;
};

export type GetWorkspaceResponse = GetWorkspaceResponses[keyof GetWorkspaceResponses];

export type CheckWorkspaceSlugExistsData = {
    body?: never;
    path: {
        workspaceSlug: NoteSlug;
    };
    query?: never;
    url: '/note/workspaces-by-slug/{workspaceSlug}/exists';
};

export type CheckWorkspaceSlugExistsErrors = {
    /**
     * Bad Request Error response
     */
    400: NoteError;
    /**
     * The error response body returned when JWT validation or OPA authorization fails.
     */
    401: {
        /**
         * The category of the error encountered during the middleware lifecycle.
         */
        type: 'ExtractToken' | 'VerifyToken' | 'FetchJWKS' | 'OPA';
        /**
         * A descriptive message providing technical context for the failure.
         */
        details: string;
        /**
         * An optional, developer-defined message, often populated by OPA policy violations.
         */
        custom_message: string | null;
    };
    /**
     * Not Found Error response
     */
    404: NoteError;
    /**
     * The workspace slug already exists
     */
    409: unknown;
    /**
     * Internal Server Error response
     */
    500: NoteError;
};

export type CheckWorkspaceSlugExistsError = CheckWorkspaceSlugExistsErrors[keyof CheckWorkspaceSlugExistsErrors];

export type CheckWorkspaceSlugExistsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type CreateWorkspaceData = {
    body: NoteWorkspaceWritable;
    path?: never;
    query?: never;
    url: '/note/workspaces';
};

export type CreateWorkspaceErrors = {
    /**
     * Bad Request Error response
     */
    400: NoteError;
    /**
     * The error response body returned when JWT validation or OPA authorization fails.
     */
    401: {
        /**
         * The category of the error encountered during the middleware lifecycle.
         */
        type: 'ExtractToken' | 'VerifyToken' | 'FetchJWKS' | 'OPA';
        /**
         * A descriptive message providing technical context for the failure.
         */
        details: string;
        /**
         * An optional, developer-defined message, often populated by OPA policy violations.
         */
        custom_message: string | null;
    };
    /**
     * Internal Server Error response
     */
    500: NoteError;
};

export type CreateWorkspaceError = CreateWorkspaceErrors[keyof CreateWorkspaceErrors];

export type CreateWorkspaceResponses = {
    /**
     * Workspace successfully created
     */
    201: unknown;
};

export type GetMyWorkspacesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/note/workspaces/me';
};

export type GetMyWorkspacesErrors = {
    /**
     * Bad Request Error response
     */
    400: NoteError;
    /**
     * The error response body returned when JWT validation or OPA authorization fails.
     */
    401: {
        /**
         * The category of the error encountered during the middleware lifecycle.
         */
        type: 'ExtractToken' | 'VerifyToken' | 'FetchJWKS' | 'OPA';
        /**
         * A descriptive message providing technical context for the failure.
         */
        details: string;
        /**
         * An optional, developer-defined message, often populated by OPA policy violations.
         */
        custom_message: string | null;
    };
    /**
     * Internal Server Error response
     */
    500: NoteError;
};

export type GetMyWorkspacesError = GetMyWorkspacesErrors[keyof GetMyWorkspacesErrors];

export type GetMyWorkspacesResponses = {
    /**
     * A list of workspaces
     */
    200: Array<NoteUserWorkspace>;
};

export type GetMyWorkspacesResponse = GetMyWorkspacesResponses[keyof GetMyWorkspacesResponses];

export type DeleteWorkspaceData = {
    body?: never;
    path: {
        workspaceId: NoteWorkspacePropertiesId;
    };
    query?: never;
    url: '/note/workspaces/{workspaceId}';
};

export type DeleteWorkspaceErrors = {
    /**
     * Bad Request Error response
     */
    400: NoteError;
    /**
     * The error response body returned when JWT validation or OPA authorization fails.
     */
    401: {
        /**
         * The category of the error encountered during the middleware lifecycle.
         */
        type: 'ExtractToken' | 'VerifyToken' | 'FetchJWKS' | 'OPA';
        /**
         * A descriptive message providing technical context for the failure.
         */
        details: string;
        /**
         * An optional, developer-defined message, often populated by OPA policy violations.
         */
        custom_message: string | null;
    };
    /**
     * Not Found Error response
     */
    404: NoteError;
    /**
     * Internal Server Error response
     */
    500: NoteError;
};

export type DeleteWorkspaceError = DeleteWorkspaceErrors[keyof DeleteWorkspaceErrors];

export type DeleteWorkspaceResponses = {
    /**
     * No Content - Workspace successfully deleted.
     */
    204: void;
};

export type DeleteWorkspaceResponse = DeleteWorkspaceResponses[keyof DeleteWorkspaceResponses];

export type ChangeWorkspaceSlugData = {
    body: {
        slug: NoteSlug;
    };
    path: {
        workspaceId: NoteWorkspacePropertiesId;
    };
    query?: never;
    url: '/note/workspaces/{workspaceId}/change-slug';
};

export type ChangeWorkspaceSlugErrors = {
    /**
     * Bad Request Error response
     */
    400: NoteError;
    /**
     * The error response body returned when JWT validation or OPA authorization fails.
     */
    401: {
        /**
         * The category of the error encountered during the middleware lifecycle.
         */
        type: 'ExtractToken' | 'VerifyToken' | 'FetchJWKS' | 'OPA';
        /**
         * A descriptive message providing technical context for the failure.
         */
        details: string;
        /**
         * An optional, developer-defined message, often populated by OPA policy violations.
         */
        custom_message: string | null;
    };
    /**
     * Not Found Error response
     */
    404: NoteError;
    /**
     * Internal Server Error response
     */
    500: NoteError;
};

export type ChangeWorkspaceSlugError = ChangeWorkspaceSlugErrors[keyof ChangeWorkspaceSlugErrors];

export type ChangeWorkspaceSlugResponses = {
    /**
     * Workspace slug changed successfully
     */
    204: void;
};

export type ChangeWorkspaceSlugResponse = ChangeWorkspaceSlugResponses[keyof ChangeWorkspaceSlugResponses];

export type GetWorkspaceEventsData = {
    body?: never;
    path: {
        workspaceId: NoteWorkspacePropertiesId;
    };
    query?: never;
    url: '/note/workspaces/{workspaceId}/events';
};

export type GetWorkspaceEventsErrors = {
    /**
     * Bad Request Error response
     */
    400: NoteError;
    /**
     * The error response body returned when JWT validation or OPA authorization fails.
     */
    401: {
        /**
         * The category of the error encountered during the middleware lifecycle.
         */
        type: 'ExtractToken' | 'VerifyToken' | 'FetchJWKS' | 'OPA';
        /**
         * A descriptive message providing technical context for the failure.
         */
        details: string;
        /**
         * An optional, developer-defined message, often populated by OPA policy violations.
         */
        custom_message: string | null;
    };
    /**
     * Internal Server Error response
     */
    500: NoteError;
};

export type GetWorkspaceEventsError = GetWorkspaceEventsErrors[keyof GetWorkspaceEventsErrors];

export type GetWorkspaceEventsResponses = {
    /**
     * A persistent stream of events
     */
    200: ({
        event: 'HeartBeatWorkspaceEvent';
    } & NoteHeartBeatWorkspaceEvent) | ({
        event: 'WorkspaceDeletedEvent';
    } & NoteWorkspaceDeletedEvent) | ({
        event: 'WorkspaceItemsUpdatedEvent';
    } & NoteWorkspaceItemsUpdatedEvent) | ({
        event: 'WorkspaceMembersUpdatedEvent';
    } & NoteWorkspaceMembersUpdatedEvent) | ({
        event: 'WorkspaceRenamedEvent';
    } & NoteWorkspaceRenamedEvent) | ({
        event: 'WorkspaceSlugChangedEvent';
    } & NoteWorkspaceSlugChangedEvent);
};

export type GetWorkspaceEventsResponse = GetWorkspaceEventsResponses[keyof GetWorkspaceEventsResponses];

export type GetWorkspaceGraphData = {
    body?: never;
    path: {
        workspaceId: NoteWorkspacePropertiesId;
    };
    query?: {
        /**
         * Include node that are not connected to any other node
         */
        includeOrphans?: boolean;
    };
    url: '/note/workspaces/{workspaceId}/graph';
};

export type GetWorkspaceGraphErrors = {
    /**
     * Bad Request Error response
     */
    400: NoteError;
    /**
     * The error response body returned when JWT validation or OPA authorization fails.
     */
    401: {
        /**
         * The category of the error encountered during the middleware lifecycle.
         */
        type: 'ExtractToken' | 'VerifyToken' | 'FetchJWKS' | 'OPA';
        /**
         * A descriptive message providing technical context for the failure.
         */
        details: string;
        /**
         * An optional, developer-defined message, often populated by OPA policy violations.
         */
        custom_message: string | null;
    };
    /**
     * Forbidden Error response
     */
    403: NoteError;
    /**
     * Not Found Error response
     */
    404: NoteError;
    /**
     * Internal Server Error response
     */
    500: NoteError;
};

export type GetWorkspaceGraphError = GetWorkspaceGraphErrors[keyof GetWorkspaceGraphErrors];

export type GetWorkspaceGraphResponses = {
    /**
     * Workspace graph
     */
    200: NoteGraph;
};

export type GetWorkspaceGraphResponse = GetWorkspaceGraphResponses[keyof GetWorkspaceGraphResponses];

export type GetWorkspaceMembersData = {
    body?: never;
    path: {
        workspaceId: NoteWorkspacePropertiesId;
    };
    query?: never;
    url: '/note/workspaces/{workspaceId}/members';
};

export type GetWorkspaceMembersErrors = {
    /**
     * Bad Request Error response
     */
    400: NoteError;
    /**
     * The error response body returned when JWT validation or OPA authorization fails.
     */
    401: {
        /**
         * The category of the error encountered during the middleware lifecycle.
         */
        type: 'ExtractToken' | 'VerifyToken' | 'FetchJWKS' | 'OPA';
        /**
         * A descriptive message providing technical context for the failure.
         */
        details: string;
        /**
         * An optional, developer-defined message, often populated by OPA policy violations.
         */
        custom_message: string | null;
    };
    /**
     * Not Found Error response
     */
    404: NoteError;
    /**
     * Internal Server Error response
     */
    500: NoteError;
};

export type GetWorkspaceMembersError = GetWorkspaceMembersErrors[keyof GetWorkspaceMembersErrors];

export type GetWorkspaceMembersResponses = {
    /**
     * A list of workspace members
     */
    200: Array<NoteWorkspaceMember>;
};

export type GetWorkspaceMembersResponse = GetWorkspaceMembersResponses[keyof GetWorkspaceMembersResponses];

export type UpdateWorkspaceMembersData = {
    body: Array<NoteWorkspaceMemberWritable>;
    path: {
        workspaceId: NoteWorkspacePropertiesId;
    };
    query?: never;
    url: '/note/workspaces/{workspaceId}/members';
};

export type UpdateWorkspaceMembersErrors = {
    /**
     * Bad Request Error response
     */
    400: NoteError;
    /**
     * The error response body returned when JWT validation or OPA authorization fails.
     */
    401: {
        /**
         * The category of the error encountered during the middleware lifecycle.
         */
        type: 'ExtractToken' | 'VerifyToken' | 'FetchJWKS' | 'OPA';
        /**
         * A descriptive message providing technical context for the failure.
         */
        details: string;
        /**
         * An optional, developer-defined message, often populated by OPA policy violations.
         */
        custom_message: string | null;
    };
    /**
     * Not Found Error response
     */
    404: NoteError;
    /**
     * Internal Server Error response
     */
    500: NoteError;
};

export type UpdateWorkspaceMembersError = UpdateWorkspaceMembersErrors[keyof UpdateWorkspaceMembersErrors];

export type UpdateWorkspaceMembersResponses = {
    /**
     * Workspace members updated successfully
     */
    204: void;
};

export type UpdateWorkspaceMembersResponse = UpdateWorkspaceMembersResponses[keyof UpdateWorkspaceMembersResponses];

export type MoveWorkspaceItemsData = {
    body: {
        noteIds?: Array<NotePropertiesId>;
        folderIds?: Array<NoteId>;
        destinationFolderId: NoteId;
    };
    path: {
        workspaceId: NoteWorkspacePropertiesId;
    };
    query?: never;
    url: '/note/workspaces/{workspaceId}/move-items';
};

export type MoveWorkspaceItemsErrors = {
    /**
     * Bad Request Error response
     */
    400: NoteError;
    /**
     * The error response body returned when JWT validation or OPA authorization fails.
     */
    401: {
        /**
         * The category of the error encountered during the middleware lifecycle.
         */
        type: 'ExtractToken' | 'VerifyToken' | 'FetchJWKS' | 'OPA';
        /**
         * A descriptive message providing technical context for the failure.
         */
        details: string;
        /**
         * An optional, developer-defined message, often populated by OPA policy violations.
         */
        custom_message: string | null;
    };
    /**
     * Not Found Error response
     */
    404: NoteError;
    /**
     * Internal Server Error response
     */
    500: NoteError;
};

export type MoveWorkspaceItemsError = MoveWorkspaceItemsErrors[keyof MoveWorkspaceItemsErrors];

export type MoveWorkspaceItemsResponses = {
    /**
     * Workspace items successfully moved
     */
    204: void;
};

export type MoveWorkspaceItemsResponse = MoveWorkspaceItemsResponses[keyof MoveWorkspaceItemsResponses];

export type PermanentlyDeleteWorkspaceItemsData = {
    body: {
        noteIds?: Array<NotePropertiesId>;
        folderIds?: Array<NoteId>;
    };
    path: {
        workspaceId: NoteWorkspacePropertiesId;
    };
    query?: never;
    url: '/note/workspaces/{workspaceId}/permanently-delete-items';
};

export type PermanentlyDeleteWorkspaceItemsErrors = {
    /**
     * Bad Request Error response
     */
    400: NoteError;
    /**
     * The error response body returned when JWT validation or OPA authorization fails.
     */
    401: {
        /**
         * The category of the error encountered during the middleware lifecycle.
         */
        type: 'ExtractToken' | 'VerifyToken' | 'FetchJWKS' | 'OPA';
        /**
         * A descriptive message providing technical context for the failure.
         */
        details: string;
        /**
         * An optional, developer-defined message, often populated by OPA policy violations.
         */
        custom_message: string | null;
    };
    /**
     * Not Found Error response
     */
    404: NoteError;
    /**
     * Internal Server Error response
     */
    500: NoteError;
};

export type PermanentlyDeleteWorkspaceItemsError = PermanentlyDeleteWorkspaceItemsErrors[keyof PermanentlyDeleteWorkspaceItemsErrors];

export type PermanentlyDeleteWorkspaceItemsResponses = {
    /**
     * Workspace items permanently deleted
     */
    204: void;
};

export type PermanentlyDeleteWorkspaceItemsResponse = PermanentlyDeleteWorkspaceItemsResponses[keyof PermanentlyDeleteWorkspaceItemsResponses];

export type PublishWorkspaceData = {
    body?: never;
    path: {
        workspaceId: NoteWorkspacePropertiesId;
    };
    query?: never;
    url: '/note/workspaces/{workspaceId}/publish';
};

export type PublishWorkspaceErrors = {
    /**
     * Bad Request Error response
     */
    400: NoteError;
    /**
     * The error response body returned when JWT validation or OPA authorization fails.
     */
    401: {
        /**
         * The category of the error encountered during the middleware lifecycle.
         */
        type: 'ExtractToken' | 'VerifyToken' | 'FetchJWKS' | 'OPA';
        /**
         * A descriptive message providing technical context for the failure.
         */
        details: string;
        /**
         * An optional, developer-defined message, often populated by OPA policy violations.
         */
        custom_message: string | null;
    };
    /**
     * Not Found Error response
     */
    404: NoteError;
    /**
     * Internal Server Error response
     */
    500: NoteError;
};

export type PublishWorkspaceError = PublishWorkspaceErrors[keyof PublishWorkspaceErrors];

export type PublishWorkspaceResponses = {
    /**
     * Workspace published successfully
     */
    204: void;
};

export type PublishWorkspaceResponse = PublishWorkspaceResponses[keyof PublishWorkspaceResponses];

export type RenameWorkspaceData = {
    body: {
        name: NoteWorkspacePropertiesName;
    };
    path: {
        workspaceId: NoteWorkspacePropertiesId;
    };
    query?: never;
    url: '/note/workspaces/{workspaceId}/rename';
};

export type RenameWorkspaceErrors = {
    /**
     * Bad Request Error response
     */
    400: NoteError;
    /**
     * The error response body returned when JWT validation or OPA authorization fails.
     */
    401: {
        /**
         * The category of the error encountered during the middleware lifecycle.
         */
        type: 'ExtractToken' | 'VerifyToken' | 'FetchJWKS' | 'OPA';
        /**
         * A descriptive message providing technical context for the failure.
         */
        details: string;
        /**
         * An optional, developer-defined message, often populated by OPA policy violations.
         */
        custom_message: string | null;
    };
    /**
     * Not Found Error response
     */
    404: NoteError;
    /**
     * Internal Server Error response
     */
    500: NoteError;
};

export type RenameWorkspaceError = RenameWorkspaceErrors[keyof RenameWorkspaceErrors];

export type RenameWorkspaceResponses = {
    /**
     * Workspace renamed successfully
     */
    204: void;
};

export type RenameWorkspaceResponse = RenameWorkspaceResponses[keyof RenameWorkspaceResponses];

export type RestoreTrashedWorkspaceItemsData = {
    body: {
        noteIds?: Array<NotePropertiesId>;
        folderIds?: Array<NoteId>;
    };
    path: {
        workspaceId: NoteWorkspacePropertiesId;
    };
    query?: never;
    url: '/note/workspaces/{workspaceId}/restore-trashed-items';
};

export type RestoreTrashedWorkspaceItemsErrors = {
    /**
     * Bad Request Error response
     */
    400: NoteError;
    /**
     * The error response body returned when JWT validation or OPA authorization fails.
     */
    401: {
        /**
         * The category of the error encountered during the middleware lifecycle.
         */
        type: 'ExtractToken' | 'VerifyToken' | 'FetchJWKS' | 'OPA';
        /**
         * A descriptive message providing technical context for the failure.
         */
        details: string;
        /**
         * An optional, developer-defined message, often populated by OPA policy violations.
         */
        custom_message: string | null;
    };
    /**
     * Not Found Error response
     */
    404: NoteError;
    /**
     * Internal Server Error response
     */
    500: NoteError;
};

export type RestoreTrashedWorkspaceItemsError = RestoreTrashedWorkspaceItemsErrors[keyof RestoreTrashedWorkspaceItemsErrors];

export type RestoreTrashedWorkspaceItemsResponses = {
    /**
     * Workspace items successfully restored
     */
    204: void;
};

export type RestoreTrashedWorkspaceItemsResponse = RestoreTrashedWorkspaceItemsResponses[keyof RestoreTrashedWorkspaceItemsResponses];

export type ShowTrashData = {
    body?: never;
    path: {
        workspaceId: NoteWorkspacePropertiesId;
    };
    query?: never;
    url: '/note/workspaces/{workspaceId}/show-trash';
};

export type ShowTrashErrors = {
    /**
     * Bad Request Error response
     */
    400: NoteError;
    /**
     * The error response body returned when JWT validation or OPA authorization fails.
     */
    401: {
        /**
         * The category of the error encountered during the middleware lifecycle.
         */
        type: 'ExtractToken' | 'VerifyToken' | 'FetchJWKS' | 'OPA';
        /**
         * A descriptive message providing technical context for the failure.
         */
        details: string;
        /**
         * An optional, developer-defined message, often populated by OPA policy violations.
         */
        custom_message: string | null;
    };
    /**
     * Not Found Error response
     */
    404: NoteError;
    /**
     * Internal Server Error response
     */
    500: NoteError;
};

export type ShowTrashError = ShowTrashErrors[keyof ShowTrashErrors];

export type ShowTrashResponses = {
    /**
     * Trash
     */
    200: {
        notes: Array<NoteTrashedNote>;
        folders: Array<NoteTrashedFolder>;
    };
};

export type ShowTrashResponse = ShowTrashResponses[keyof ShowTrashResponses];

export type TrashWorkspaceItemsData = {
    body: {
        noteIds?: Array<NotePropertiesId>;
        folderIds?: Array<NoteId>;
    };
    path: {
        workspaceId: NoteWorkspacePropertiesId;
    };
    query?: never;
    url: '/note/workspaces/{workspaceId}/trash-items';
};

export type TrashWorkspaceItemsErrors = {
    /**
     * Bad Request Error response
     */
    400: NoteError;
    /**
     * The error response body returned when JWT validation or OPA authorization fails.
     */
    401: {
        /**
         * The category of the error encountered during the middleware lifecycle.
         */
        type: 'ExtractToken' | 'VerifyToken' | 'FetchJWKS' | 'OPA';
        /**
         * A descriptive message providing technical context for the failure.
         */
        details: string;
        /**
         * An optional, developer-defined message, often populated by OPA policy violations.
         */
        custom_message: string | null;
    };
    /**
     * Not Found Error response
     */
    404: NoteError;
    /**
     * Internal Server Error response
     */
    500: NoteError;
};

export type TrashWorkspaceItemsError = TrashWorkspaceItemsErrors[keyof TrashWorkspaceItemsErrors];

export type TrashWorkspaceItemsResponses = {
    /**
     * Workspace items successfully trashed
     */
    204: void;
};

export type TrashWorkspaceItemsResponse = TrashWorkspaceItemsResponses[keyof TrashWorkspaceItemsResponses];

export type GetWorkspaceTreeData = {
    body?: never;
    path: {
        workspaceId: NoteWorkspacePropertiesId;
    };
    query?: {
        rootFolderId?: NoteId;
        includeTrashed?: boolean;
        depth?: number;
    };
    url: '/note/workspaces/{workspaceId}/tree';
};

export type GetWorkspaceTreeErrors = {
    /**
     * Bad Request Error response
     */
    400: NoteError;
    /**
     * The error response body returned when JWT validation or OPA authorization fails.
     */
    401: {
        /**
         * The category of the error encountered during the middleware lifecycle.
         */
        type: 'ExtractToken' | 'VerifyToken' | 'FetchJWKS' | 'OPA';
        /**
         * A descriptive message providing technical context for the failure.
         */
        details: string;
        /**
         * An optional, developer-defined message, often populated by OPA policy violations.
         */
        custom_message: string | null;
    };
    /**
     * Not Found Error response
     */
    404: NoteError;
    /**
     * Internal Server Error response
     */
    500: NoteError;
};

export type GetWorkspaceTreeError = GetWorkspaceTreeErrors[keyof GetWorkspaceTreeErrors];

export type GetWorkspaceTreeResponses = {
    /**
     * OK
     */
    200: NoteWorkspaceTreeFolder;
};

export type GetWorkspaceTreeResponse = GetWorkspaceTreeResponses[keyof GetWorkspaceTreeResponses];

export type UnpublishWorkspaceData = {
    body?: never;
    path: {
        workspaceId: NoteWorkspacePropertiesId;
    };
    query?: never;
    url: '/note/workspaces/{workspaceId}/unpublish';
};

export type UnpublishWorkspaceErrors = {
    /**
     * Bad Request Error response
     */
    400: NoteError;
    /**
     * The error response body returned when JWT validation or OPA authorization fails.
     */
    401: {
        /**
         * The category of the error encountered during the middleware lifecycle.
         */
        type: 'ExtractToken' | 'VerifyToken' | 'FetchJWKS' | 'OPA';
        /**
         * A descriptive message providing technical context for the failure.
         */
        details: string;
        /**
         * An optional, developer-defined message, often populated by OPA policy violations.
         */
        custom_message: string | null;
    };
    /**
     * Not Found Error response
     */
    404: NoteError;
    /**
     * Internal Server Error response
     */
    500: NoteError;
};

export type UnpublishWorkspaceError = UnpublishWorkspaceErrors[keyof UnpublishWorkspaceErrors];

export type UnpublishWorkspaceResponses = {
    /**
     * Workspace unpublished successfully
     */
    204: void;
};

export type UnpublishWorkspaceResponse = UnpublishWorkspaceResponses[keyof UnpublishWorkspaceResponses];
