// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zShareNoteCreatedEvent = z.object({
    id: z.uuid(),
    workspaceId: z.uuid(),
    name: z.string(),
    icon: z.string().nullable()
});

export const zShareNoteDeletedEvent = z.object({
    id: z.uuid()
});

/**
 * BlockNote model
 */
export const zShareDocumentContent = z.array(z.unknown());

export const zShareDocument = z.object({
    id: z.uuid(),
    content: zShareDocumentContent
});

export const zShareDocumentCommittedEvent = zShareDocument.and(z.object({
    userId: z.string(),
    tags: z.array(z.string()),
    outgoingLinkIds: z.array(z.uuid())
}));

export const zShareTrashedBy = z.enum(['purpose', 'parent']);

export const zShareTrashed = z.object({
    by: zShareTrashedBy,
    at: z.iso.datetime()
});

export const zShareNoteSearch = z.object({
    id: z.uuid(),
    workspaceId: z.uuid(),
    folderId: z.uuid(),
    folderName: z.string(),
    name: z.string(),
    plainTextContent: z.string(),
    tags: z.array(z.string()),
    trashed: zShareTrashed.optional()
});

export const zShareNoteUpdatedEvent = z.object({
    id: z.uuid(),
    workspaceId: z.uuid(),
    name: z.string(),
    icon: z.string().nullable(),
    folderId: z.uuid(),
    folderName: z.string(),
    trashed: zShareTrashed.optional(),
    updatedAt: z.iso.datetime()
});

/**
 * User ID from Authentik (need to change subject mode to User's ID instead of hashed)
 */
export const zShareId = z.string();

export const zShareUserDeletedEvent = z.object({
    id: zShareId
});

export const zShareId2 = z.uuid().readonly();

export const zShareWorkspaceMemberRemovedEvent = z.object({
    workspaceId: zShareId2,
    userId: zShareId
});

export const zShareWorkspaceRole = z.enum([
    'owner',
    'editor',
    'viewer'
]);

export const zShareUserWorkspaceRoleUpdatedEvent = z.object({
    workspaceId: zShareId2,
    userId: zShareId,
    role: zShareWorkspaceRole
});

export const zShareWorkspaceMemberAddedEvent = z.object({
    workspaceId: zShareId2,
    userId: zShareId,
    role: zShareWorkspaceRole
});

export const zDocumentId = z.uuid();

export const zDocumentError = z.object({
    code: z.string(),
    message: z.string(),
    more_info: z.string().optional()
});

export const zDocumentId2 = z.uuid().readonly();

export const zDocumentRevision = z.object({
    id: z.uuid().readonly(),
    name: z.string().min(1).max(255).nullable(),
    createdAt: z.iso.datetime().readonly()
});

export const zDocumentPagination = z.object({
    page: z.int().gte(1),
    limit: z.int().gte(1).lte(100),
    total: z.int().gte(0),
    totalPages: z.int().gte(0),
    hasNext: z.boolean(),
    hasPrev: z.boolean()
});

/**
 * BlockNote model
 */
export const zDocumentDocumentContent = z.array(z.unknown());

export const zDocumentRevisionWithContent = zDocumentRevision.and(z.object({
    content: zDocumentDocumentContent
}));

export const zDocumentName = z.string().min(1).max(255).nullable();

export const zNoteTrashedBy = z.enum(['purpose', 'parent']);

export const zNoteFolder = z.object({
    id: z.uuid().readonly(),
    name: z.string().min(1).max(255),
    icon: z.string().nullable(),
    parentId: z.uuid().nullable(),
    workspaceId: z.uuid(),
    updatedAt: z.iso.datetime().readonly(),
    trashed: z.object({
        by: zNoteTrashedBy,
        at: z.iso.datetime()
    }).readonly().nullable()
});

export const zNoteId = z.uuid().readonly();

export const zNoteError = z.object({
    code: z.string(),
    message: z.string(),
    more_info: z.string().optional()
});

export const zNoteName = z.string().min(1).max(255);

export const zNoteNote = z.object({
    id: z.uuid().readonly(),
    name: z.string().min(1).max(255),
    icon: z.string().nullable(),
    folderId: z.uuid(),
    tags: z.array(z.string()).readonly(),
    updatedAt: z.iso.datetime().readonly(),
    trashed: z.object({
        by: zNoteTrashedBy,
        at: z.iso.datetime()
    }).readonly().nullable()
});

export const zNoteId2 = z.uuid().readonly();

export const zNoteGraph = z.object({
    nodes: z.array(z.object({
        id: z.string(),
        name: z.string(),
        type: z.enum(['note', 'tag']),
        weight: z.number().gte(0.5).lte(1).optional()
    })),
    links: z.array(z.object({
        source: z.string(),
        target: z.string()
    }))
});

/**
 * Can be empty string when creating but will be set to "Untitled Note" internally
 */
export const zNoteName2 = z.string().min(1).max(255);

export const zNoteIcon = z.string().nullable();

export const zNoteNoteLink = z.object({
    id: zNoteId2,
    name: zNoteName2,
    icon: zNoteIcon
});

export const zNoteSlug = z.string();

export const zNoteWorkspace = z.object({
    id: z.uuid().readonly(),
    slug: z.string(),
    name: z.string().min(1).max(255)
});

export const zNoteId3 = z.uuid().readonly();

export const zNoteWorkspaceRole = z.enum([
    'owner',
    'editor',
    'viewer'
]);

export const zNoteUserWorkspace = z.object({
    workspace: zNoteWorkspace,
    role: zNoteWorkspaceRole
});

export const zNoteHeartBeatWorkspaceEvent = z.object({
    event: z.enum(['HeartBeatWorkspaceEvent']),
    timestamp: z.iso.datetime()
});

export const zNoteWorkspaceDeletedEvent = z.object({
    id: z.uuid(),
    event: z.enum(['WorkspaceDeletedEvent']),
    data: z.object({
        id: zNoteId3
    })
});

export const zNoteWorkspaceItemsUpdatedEvent = z.object({
    id: z.uuid(),
    event: z.enum(['WorkspaceItemsUpdatedEvent']),
    data: z.object({
        workspaceId: zNoteId3
    })
});

export const zNoteWorkspaceMembersUpdatedEvent = z.object({
    id: z.uuid(),
    event: z.enum(['WorkspaceMembersUpdatedEvent']),
    data: z.object({
        workspaceId: zNoteId3
    })
});

export const zNoteName3 = z.string().min(1).max(255);

export const zNoteWorkspaceRenamedEvent = z.object({
    id: z.uuid(),
    event: z.enum(['WorkspaceRenamedEvent']),
    data: z.object({
        id: zNoteId3,
        name: zNoteName3
    })
});

export const zNoteWorkspaceSlugChangedEvent = z.object({
    id: z.uuid(),
    event: z.enum(['WorkspaceSlugChangedEvent']),
    data: z.object({
        id: zNoteId3,
        slug: zNoteSlug
    })
});

/**
 * User ID from Authentik (need to change subject mode to User's ID instead of hashed)
 */
export const zNoteId4 = z.string();

/**
 * Full name from Authentik
 */
export const zNoteName4 = z.string().nullable();

export const zNoteWorkspaceMember = z.object({
    id: zNoteId4,
    name: zNoteName4.optional(),
    role: zNoteWorkspaceRole
});

export const zNoteSearchToken = z.object({
    token: z.string(),
    expiresAt: z.iso.datetime()
});

export const zNoteTrashed = z.object({
    by: zNoteTrashedBy,
    at: z.iso.datetime()
});

export const zNoteTrashedNote = z.object({
    id: z.uuid(),
    name: z.string().min(1).max(255).readonly(),
    trashed: zNoteTrashed
});

export const zNoteTrashedFolder = z.object({
    id: z.uuid(),
    name: z.string().min(1).max(255).readonly(),
    trashed: zNoteTrashed
});

export const zNoteIcon2 = z.string().nullable();

export const zNoteUpdatedAt = z.iso.datetime().readonly();

export const zNoteWorkspaceTreeNote = z.object({
    id: zNoteId2,
    name: zNoteName2,
    icon: zNoteIcon,
    updatedAt: zNoteUpdatedAt
});

export const zNoteUpdatedAt2 = z.iso.datetime().readonly();

export const zNoteWorkspaceTreeFolder = z.object({
    id: zNoteId,
    name: zNoteName,
    icon: zNoteIcon2,
    notes: z.array(zNoteWorkspaceTreeNote),
    children: z.array(z.lazy((): any => zNoteWorkspaceTreeFolder)),
    updatedAt: zNoteUpdatedAt2
});

export const zShareUserWorkspaceRoleUpdatedEventWritable = z.object({
    userId: zShareId,
    role: zShareWorkspaceRole
});

export const zShareWorkspaceMemberAddedEventWritable = z.object({
    userId: zShareId,
    role: zShareWorkspaceRole
});

export const zShareWorkspaceMemberRemovedEventWritable = z.object({
    userId: zShareId
});

/**
 * BlockNote model
 */
export const zShareDocumentContentWritable = z.array(z.unknown());

export const zDocumentRevisionWritable = z.object({
    name: z.string().min(1).max(255).nullable()
});

/**
 * BlockNote model
 */
export const zDocumentDocumentContentWritable = z.array(z.unknown());

export const zDocumentRevisionWithContentWritable = zDocumentRevisionWritable.and(z.object({
    content: zDocumentDocumentContentWritable
}));

export const zNoteFolderWritable = z.object({
    name: z.string().min(1).max(255),
    icon: z.string().nullable(),
    parentId: z.uuid().nullable(),
    workspaceId: z.uuid()
});

export const zNoteNoteWritable = z.object({
    name: z.string().min(1).max(255),
    icon: z.string().nullable(),
    folderId: z.uuid()
});

export const zNoteNoteLinkWritable = z.object({
    name: zNoteName2,
    icon: zNoteIcon
});

export const zNoteWorkspaceWritable = z.object({
    slug: z.string(),
    name: z.string().min(1).max(255)
});

export const zNoteUserWorkspaceWritable = z.object({
    workspace: zNoteWorkspaceWritable,
    role: zNoteWorkspaceRole
});

export const zNoteWorkspaceDeletedEventWritable = z.object({
    id: z.uuid(),
    event: z.enum(['WorkspaceDeletedEvent'])
});

export const zNoteWorkspaceItemsUpdatedEventWritable = z.object({
    id: z.uuid(),
    event: z.enum(['WorkspaceItemsUpdatedEvent'])
});

export const zNoteWorkspaceMembersUpdatedEventWritable = z.object({
    id: z.uuid(),
    event: z.enum(['WorkspaceMembersUpdatedEvent'])
});

export const zNoteWorkspaceRenamedEventWritable = z.object({
    id: z.uuid(),
    event: z.enum(['WorkspaceRenamedEvent']),
    data: z.object({
        name: zNoteName3
    })
});

export const zNoteWorkspaceSlugChangedEventWritable = z.object({
    id: z.uuid(),
    event: z.enum(['WorkspaceSlugChangedEvent']),
    data: z.object({
        slug: zNoteSlug
    })
});

export const zNoteWorkspaceMemberWritable = z.object({
    id: zNoteId4,
    role: zNoteWorkspaceRole
});

export const zNoteTrashedNoteWritable = z.object({
    id: z.uuid(),
    trashed: zNoteTrashed
});

export const zNoteTrashedFolderWritable = z.object({
    id: z.uuid(),
    trashed: zNoteTrashed
});

export const zNoteWorkspaceTreeNoteWritable = z.object({
    name: zNoteName2,
    icon: zNoteIcon
});

export const zNoteWorkspaceTreeFolderWritable = z.object({
    name: zNoteName,
    icon: zNoteIcon2,
    notes: z.array(zNoteWorkspaceTreeNoteWritable),
    children: z.array(z.lazy((): any => zNoteWorkspaceTreeFolderWritable))
});

/**
 * Unique identifier of the document (note)
 */
export const zDocumentDocumentIdPath = zDocumentId;

export const zDocumentDocumentIdQuery = zDocumentId;

/**
 * Page number for pagination
 */
export const zDocumentPageQuery = z.int().gte(1).default(1);

/**
 * Number of items per page
 */
export const zDocumentLimitQuery = z.int().gte(1).lte(100).default(20);

export const zDocumentRevisionIdPath = zDocumentId2;

export const zNoteFolderIdPath = zNoteId;

export const zNoteNoteIdPath = zNoteId2;

export const zNoteWorkspaceSlugPath = zNoteSlug;

export const zNoteWorkspaceIdPath = zNoteId3;

export const zGetDocumentAttachmentUploadUrlPath = z.object({
    documentId: zDocumentId
});

/**
 * Presigned URL
 */
export const zGetDocumentAttachmentUploadUrlResponse = z.object({
    uploadUrl: z.url(),
    url: z.url()
});

export const zCommitDocumentPath = z.object({
    documentId: zDocumentId
});

/**
 * Document revision committed successfully
 */
export const zCommitDocumentResponse = z.object({
    id: zDocumentId2
});

export const zGetRevisionsQuery = z.object({
    documentId: zDocumentId,
    page: z.int().gte(1).optional().default(1),
    limit: z.int().gte(1).lte(100).optional().default(20)
});

/**
 * Revisions
 */
export const zGetRevisionsResponse = z.object({
    data: z.array(zDocumentRevision),
    pagination: zDocumentPagination
});

export const zDeleteRevisionPath = z.object({
    revisionId: zDocumentId2
});

/**
 * Revision deleted successfully
 */
export const zDeleteRevisionResponse = z.void();

export const zGetRevisionWithContentPath = z.object({
    revisionId: zDocumentId2
});

/**
 * Revision retrieved successfully
 */
export const zGetRevisionWithContentResponse = zDocumentRevisionWithContent;

export const zRenameRevisionBody = z.object({
    name: zDocumentName
});

export const zRenameRevisionPath = z.object({
    revisionId: zDocumentId2
});

/**
 * Revision renamed successfully
 */
export const zRenameRevisionResponse = z.void();

export const zCreateFolderBody = zNoteFolderWritable;

/**
 * Folder successfully created
 */
export const zCreateFolderResponse = z.object({
    id: zNoteId
});

export const zPermanentlyDeleteFolderPath = z.object({
    folderId: zNoteId
});

/**
 * Folder successfully deleted
 */
export const zPermanentlyDeleteFolderResponse = z.void();

export const zRenameFolderBody = z.object({
    name: zNoteName
});

export const zRenameFolderPath = z.object({
    folderId: zNoteId
});

/**
 * Folder renamed successfully
 */
export const zRenameFolderResponse = z.void();

export const zCreateNoteBody = zNoteNoteWritable;

/**
 * Note successfully created
 */
export const zCreateNoteResponse = z.object({
    id: zNoteId2
});

export const zPermanentlyDeleteNotePath = z.object({
    noteId: zNoteId2
});

/**
 * Note successfully deleted
 */
export const zPermanentlyDeleteNoteResponse = z.void();

export const zGetNotePath = z.object({
    noteId: zNoteId2
});

export const zGetNoteQuery = z.object({
    includeTrashed: z.boolean().optional().default(true)
});

/**
 * Successful response
 */
export const zGetNoteResponse = zNoteNote;

export const zGetNoteGraphPath = z.object({
    noteId: zNoteId2
});

export const zGetNoteGraphQuery = z.object({
    depth: z.int().gte(1).lte(500).optional().default(100)
});

/**
 * Note graph
 */
export const zGetNoteGraphResponse = zNoteGraph;

export const zGetNoteLinksPath = z.object({
    noteId: zNoteId2
});

export const zGetNoteLinksQuery = z.object({
    outgoingLinks: z.boolean().optional().default(true),
    backlinks: z.boolean().optional().default(true)
});

/**
 * Note links
 */
export const zGetNoteLinksResponse = z.object({
    outgoingLinks: z.array(zNoteNoteLink).optional(),
    backlinks: z.array(zNoteNoteLink).optional()
});

export const zPublishNotePath = z.object({
    noteId: zNoteId2
});

/**
 * Note published successfully
 */
export const zPublishNoteResponse = z.void();

export const zRenameNoteBody = z.object({
    name: zNoteName2
});

export const zRenameNotePath = z.object({
    noteId: zNoteId2
});

/**
 * Note renamed successfully
 */
export const zRenameNoteResponse = z.void();

export const zUnpublishNotePath = z.object({
    noteId: zNoteId2
});

/**
 * Note unpublished successfully
 */
export const zUnpublishNoteResponse = z.void();

export const zGetWorkspacePath = z.object({
    workspaceSlug: zNoteSlug
});

/**
 * OK
 */
export const zGetWorkspaceResponse = zNoteWorkspace;

export const zCheckWorkspaceSlugExistsPath = z.object({
    workspaceSlug: zNoteSlug
});

export const zCreateWorkspaceBody = zNoteWorkspaceWritable;

/**
 * Workspace successfully created
 */
export const zCreateWorkspaceResponse = z.object({
    id: zNoteId3
});

/**
 * A list of workspaces
 */
export const zGetMyWorkspacesResponse = z.array(zNoteUserWorkspace);

export const zDeleteWorkspacePath = z.object({
    workspaceId: zNoteId3
});

/**
 * No Content - Workspace successfully deleted.
 */
export const zDeleteWorkspaceResponse = z.void();

export const zChangeWorkspaceSlugBody = z.object({
    slug: zNoteSlug
});

export const zChangeWorkspaceSlugPath = z.object({
    workspaceId: zNoteId3
});

/**
 * Workspace slug changed successfully
 */
export const zChangeWorkspaceSlugResponse = z.void();

export const zGetWorkspaceEventsPath = z.object({
    workspaceId: zNoteId3
});

/**
 * A persistent stream of events
 */
export const zGetWorkspaceEventsResponse = z.discriminatedUnion('event', [
    zNoteHeartBeatWorkspaceEvent.extend({ event: z.literal('HeartBeatWorkspaceEvent') }),
    zNoteWorkspaceDeletedEvent.extend({ event: z.literal('WorkspaceDeletedEvent') }),
    zNoteWorkspaceItemsUpdatedEvent.extend({ event: z.literal('WorkspaceItemsUpdatedEvent') }),
    zNoteWorkspaceMembersUpdatedEvent.extend({ event: z.literal('WorkspaceMembersUpdatedEvent') }),
    zNoteWorkspaceRenamedEvent.extend({ event: z.literal('WorkspaceRenamedEvent') }),
    zNoteWorkspaceSlugChangedEvent.extend({ event: z.literal('WorkspaceSlugChangedEvent') })
]);

export const zGetWorkspaceGraphPath = z.object({
    workspaceId: zNoteId3
});

export const zGetWorkspaceGraphQuery = z.object({
    includeOrphans: z.boolean().optional().default(false)
});

/**
 * Workspace graph
 */
export const zGetWorkspaceGraphResponse = zNoteGraph;

export const zLeaveWorkspacePath = z.object({
    workspaceId: zNoteId3
});

/**
 * No Content - Workspace successfully left
 */
export const zLeaveWorkspaceResponse = z.void();

export const zGetWorkspaceMembersPath = z.object({
    workspaceId: zNoteId3
});

/**
 * A list of workspace members
 */
export const zGetWorkspaceMembersResponse = z.array(zNoteWorkspaceMember);

export const zUpdateWorkspaceMembersBody = z.array(zNoteWorkspaceMemberWritable);

export const zUpdateWorkspaceMembersPath = z.object({
    workspaceId: zNoteId3
});

/**
 * Workspace members updated successfully
 */
export const zUpdateWorkspaceMembersResponse = z.void();

export const zMoveWorkspaceItemsBody = z.object({
    noteIds: z.array(z.uuid()).optional(),
    folderIds: z.array(z.uuid()).optional(),
    destinationFolderId: z.uuid()
});

export const zMoveWorkspaceItemsPath = z.object({
    workspaceId: zNoteId3
});

/**
 * Workspace items successfully moved
 */
export const zMoveWorkspaceItemsResponse = z.void();

export const zPermanentlyDeleteWorkspaceItemsBody = z.object({
    noteIds: z.array(z.uuid()).optional(),
    folderIds: z.array(z.uuid()).optional()
});

export const zPermanentlyDeleteWorkspaceItemsPath = z.object({
    workspaceId: zNoteId3
});

/**
 * Workspace items permanently deleted
 */
export const zPermanentlyDeleteWorkspaceItemsResponse = z.void();

export const zPublishWorkspacePath = z.object({
    workspaceId: zNoteId3
});

/**
 * Workspace published successfully
 */
export const zPublishWorkspaceResponse = z.void();

export const zRenameWorkspaceBody = z.object({
    name: zNoteName3
});

export const zRenameWorkspacePath = z.object({
    workspaceId: zNoteId3
});

/**
 * Workspace renamed successfully
 */
export const zRenameWorkspaceResponse = z.void();

export const zRestoreTrashedWorkspaceItemsBody = z.object({
    noteIds: z.array(z.uuid()).optional(),
    folderIds: z.array(z.uuid()).optional()
});

export const zRestoreTrashedWorkspaceItemsPath = z.object({
    workspaceId: zNoteId3
});

/**
 * Workspace items successfully restored
 */
export const zRestoreTrashedWorkspaceItemsResponse = z.void();

export const zGetWorkspaceSearchTokenPath = z.object({
    workspaceId: zNoteId3
});

/**
 * Successful response
 */
export const zGetWorkspaceSearchTokenResponse = zNoteSearchToken;

export const zShowTrashPath = z.object({
    workspaceId: zNoteId3
});

/**
 * Trash
 */
export const zShowTrashResponse = z.object({
    notes: z.array(zNoteTrashedNote),
    folders: z.array(zNoteTrashedFolder)
});

export const zTrashWorkspaceItemsBody = z.object({
    noteIds: z.array(z.uuid()).optional(),
    folderIds: z.array(z.uuid()).optional()
});

export const zTrashWorkspaceItemsPath = z.object({
    workspaceId: zNoteId3
});

/**
 * Workspace items successfully trashed
 */
export const zTrashWorkspaceItemsResponse = z.void();

export const zGetWorkspaceTreePath = z.object({
    workspaceId: zNoteId3
});

export const zGetWorkspaceTreeQuery = z.object({
    rootFolderId: zNoteId.optional(),
    includeTrashed: z.boolean().optional().default(false),
    depth: z.int().gte(1).optional()
});

/**
 * OK
 */
export const zGetWorkspaceTreeResponse = zNoteWorkspaceTreeFolder;

export const zUnpublishWorkspacePath = z.object({
    workspaceId: zNoteId3
});

/**
 * Workspace unpublished successfully
 */
export const zUnpublishWorkspaceResponse = z.void();
