# yaml-language-server: $schema=https://www.schemastore.org/traefik-v3-file-provider.json
http:
  routers:
    document:
      entryPoints:
        - web
      rule: Host(`api.notopia.localhost`) && PathPrefix(`/document`)
      service: document
      middlewares:
        - cors
        - jwt

    document-public:
      entryPoints:
        - web
      rule: Host(`api.notopia.localhost`) && PathPrefix(`/document/ws/document`)
      service: document
      middlewares:
        - cors

  services:
    document:
      loadBalancer:
        servers:
          - url: http://host.docker.internal:8082
