# yaml-language-server: $schema=https://www.schemastore.org/traefik-v3-file-provider.json
http:
  routers:
    note:
      entryPoints:
        - web
      rule: Host(`api.notopia.localhost`) && PathPrefix(`/note`) && !PathPrefix(`/note/health`)
      service: note
      middlewares:
        - cors
        - jwt
    note-health:
      entryPoints:
        - web
      rule: Host(`api.notopia.localhost`) && PathPrefix(`/note/health`)
      service: note-health

  services:
    note:
      loadBalancer:
        servers:
          - url: http://host.docker.internal:8081
    note-health:
      loadBalancer:
        servers:
          - url: http://host.docker.internal:28081
