### 

@host = http://meilisearch.notopia.localhost
@meiliMasterToken = notopiauit


### List Keys

GET {{host}}/keys HTTP/1.1
Authorization: Bearer {{meiliMasterToken}}


### Search Note Index

# @prompt query
# @prompt searchToken

POST {{host}}/indexes/notes/search HTTP/1.1
Authorization: Bearer {{searchToken}}
Content-Type: application/json

{
  "attributesToCrop": [
    "*"
  ],
  "attributesToHighlight": [
    "name"
  ],
  "attributesToRetrieve": [
    "*"
  ],
  "highlightPostTag": "</mark>",
  "highlightPreTag": "<mark>",
  "q": "{{query}}"
}
