# yaml-language-server: $schema=https://www.schemastore.org/traefik-v3.json
api:
  insecure: true

providers:
  docker:
    exposedByDefault: false
    network: notopia_default
  file:
    directory: /etc/traefik/dynamic

log:
  level: INFO

accessLog:
  format: json
  fields:
    headers:
      defaultMode: keep
      names:
        Authorization: keep

# tracing:
#   samplerate: 1.0
#   otlp:
#     grpc:
#       endpoint: http://alloy:4317/v1/traces

entryPoints:
  web:
    address: ':80'

experimental:
  plugins:
    jwt:
      moduleName: github.com/agilezebra/jwt-middleware
      version: v1.4.0
