## yaml-language-server: $schema=https://www.schemastore.org/openapi-3.X.json
# vim: ft=yaml.openapi
openapi: 3.0.4

servers:
  - url: http://api.notopia.localhost
    description: Local dev server via gateway
  - url: http://localhost:8082
    description: Local dev/mock server direct

info:
  description: >
    Notopia API - A comprehensive note-taking service API.
  version: 0.0.0
  title: Notopia API
  license:
    name: MIT
    url: https://github.com/notopia-uit/notopia/blob/main/LICENSE
  contact:
    name: Notopia Support
    email: kevinnitro@duck.com

tags:
  - name: edit
    description: Operations related to editing notes, collaboration.

paths:
  /ws/edits/{documentId}:
    $ref: ./paths/ws_edits_{documentId}.yaml

components:
  securitySchemes:
    oauth2:
      $ref: ../shared/components/securitySchemes/Oauth2.yaml

externalDocs:
  url: https://notopia-uit.github.io/notopia
