## yaml-language-server: $schema=https://www.schemastore.org/openapi-3.X.json
# vim: ft=yaml.openapi
openapi: 3.0.4

servers:
  - url: http://api.notopia.localhost

info:
  description: >
    Notopia API - A comprehensive note-taking service API.
  version: 0.0.0
  title: Notopia API
  license:
    name: MIT
    url: https://github.com/notopia-uit/notopia/blob/main/LICENSE
  contact:
    name: Notopia Support
    email: kevinnitro@duck.com

tags:
  - name: Document
    description: Operations related to documenting notes, collaboration.

paths:
  /document/documents/import:
    $ref: ./paths/documents_import.yaml
  /document/ws/documents/{documentId}:
    $ref: ./paths/ws_documents_{documentId}.yaml
  /document/documents/{documentId}/attachment-url:
    $ref: ./paths/documents_{documentId}_attachment-url.yaml

components:
  securitySchemes:
    Oauth2:
      $ref: ../common/components/securitySchemes/Oauth2.yaml

externalDocs:
  url: https://notopia-uit.github.io/notopia
