// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: folder.sql

package pgsqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"go.opentelemetry.io/otel"
)

const checkFolderExists = `-- name: CheckFolderExists :one
SELECT
  EXISTS (
    SELECT
      1
    FROM
      folders
    WHERE
      id = $1
  )
`

func (q *Queries) CheckFolderExists(ctx context.Context, id uuid.UUID) (bool, error) {
	ctx, span := otel.Tracer("Queries").Start(ctx, "CheckFolderExists")
	defer span.End()
	row := q.db.QueryRow(ctx, checkFolderExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countFoldersInWorkspaceByIDs = `-- name: CountFoldersInWorkspaceByIDs :one
SELECT
  COUNT(*)
FROM
  folders
WHERE
  workspace_id = $1
  AND id = ANY($2::uuid[])
`

type CountFoldersInWorkspaceByIDsParams struct {
	WorkspaceID uuid.UUID
	IDs         []uuid.UUID
}

func (q *Queries) CountFoldersInWorkspaceByIDs(ctx context.Context, arg *CountFoldersInWorkspaceByIDsParams) (int64, error) {
	ctx, span := otel.Tracer("Queries").Start(ctx, "CountFoldersInWorkspaceByIDs")
	defer span.End()
	row := q.db.QueryRow(ctx, countFoldersInWorkspaceByIDs, arg.WorkspaceID, arg.IDs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getFolder = `-- name: GetFolder :one
SELECT
  id, name, icon, workspace_id, parent_id, created_at, updated_at, trashed_by, trashed_at
FROM
  folders
WHERE
  id = $1
FOR UPDATE -- :if $2
`

var _getFolderDynQ = dynCompile(getFolder)

type GetFolderParams struct {
	ID        uuid.UUID
	ForUpdate bool
}

func (q *Queries) GetFolder(ctx context.Context, arg GetFolderParams) (*Folder, error) {
	ctx, span := otel.Tracer("Queries").Start(ctx, "GetFolder")
	defer span.End()
	dynQuery, dynArgs := _getFolderDynQ.Build([]any{arg.ID, arg.ForUpdate})
	row := q.db.QueryRow(ctx, dynQuery, dynArgs...)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Icon,
		&i.WorkspaceID,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TrashedBy,
		&i.TrashedAt,
	)
	return &i, err
}

const getFolders = `-- name: GetFolders :many
SELECT
  id, name, icon, workspace_id, parent_id, created_at, updated_at, trashed_by, trashed_at
FROM
  folders
WHERE
  id = ANY($1::uuid[]) -- :if $1
  AND workspace_id = $2::uuid -- :if $2
  AND ( -- :if $3
    trashed_by = $3::text -- :if $3
    OR trashed_by IS NULL -- :if $3
  ) -- :if $3
  AND trashed_by IS NOT NULL -- :if $4
ORDER BY
  created_at DESC
FOR UPDATE -- :if $5
`

var _getFoldersDynQ = dynCompile(getFolders)

type GetFoldersParams struct {
	IDs         *[]uuid.UUID
	WorkspaceID *uuid.UUID
	TrashedBy   *string
	TrashedOnly bool
	ForUpdate   bool
}

func (q *Queries) GetFolders(ctx context.Context, arg *GetFoldersParams) ([]*Folder, error) {
	ctx, span := otel.Tracer("Queries").Start(ctx, "GetFolders")
	defer span.End()
	dynQuery, dynArgs := _getFoldersDynQ.Build([]any{arg.IDs, arg.WorkspaceID, arg.TrashedBy, arg.TrashedOnly, arg.ForUpdate})
	rows, err := q.db.Query(ctx, dynQuery, dynArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Folder
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.WorkspaceID,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TrashedBy,
			&i.TrashedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFoldersByWorkspaceID = `-- name: GetFoldersByWorkspaceID :many
SELECT
  id, name, icon, workspace_id, parent_id, created_at, updated_at, trashed_by, trashed_at
FROM
  folders
WHERE
  workspace_id = $1
ORDER BY
  created_at DESC
FOR UPDATE -- :if $2
`

var _getFoldersByWorkspaceIDDynQ = dynCompile(getFoldersByWorkspaceID)

type GetFoldersByWorkspaceIDParams struct {
	WorkspaceID uuid.UUID
	ForUpdate   bool
}

func (q *Queries) GetFoldersByWorkspaceID(ctx context.Context, arg GetFoldersByWorkspaceIDParams) ([]*Folder, error) {
	ctx, span := otel.Tracer("Queries").Start(ctx, "GetFoldersByWorkspaceID")
	defer span.End()
	dynQuery, dynArgs := _getFoldersByWorkspaceIDDynQ.Build([]any{arg.WorkspaceID, arg.ForUpdate})
	rows, err := q.db.Query(ctx, dynQuery, dynArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Folder
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.WorkspaceID,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TrashedBy,
			&i.TrashedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getParentIDsByFolderID = `-- name: GetParentIDsByFolderID :many
WITH RECURSIVE parent_folders(id, parent_id) AS (
  SELECT
    id,
    parent_id
  FROM
    folders
  WHERE
    id = $1::uuid
  UNION ALL
  SELECT
    id,
    parent_id
  FROM
    folders
    INNER JOIN parent_folders AS pf ON id = pf.parent_id
)
SELECT
  id
FROM
  parent_folders
WHERE
  id != $1::uuid
FOR UPDATE -- :if $2
`

var _getParentIDsByFolderIDDynQ = dynCompile(getParentIDsByFolderID)

type GetParentIDsByFolderIDParams struct {
	ID        uuid.UUID
	ForUpdate bool
}

func (q *Queries) GetParentIDsByFolderID(ctx context.Context, arg GetParentIDsByFolderIDParams) ([]uuid.UUID, error) {
	ctx, span := otel.Tracer("Queries").Start(ctx, "GetParentIDsByFolderID")
	defer span.End()
	dynQuery, dynArgs := _getParentIDsByFolderIDDynQ.Build([]any{arg.ID, arg.ForUpdate})
	rows, err := q.db.Query(ctx, dynQuery, dynArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecursiveChildren = `-- name: GetRecursiveChildren :many
WITH RECURSIVE child_folders AS (
  SELECT
    f.id, f.name, f.icon, f.workspace_id, f.parent_id, f.created_at, f.updated_at, f.trashed_by, f.trashed_at
  FROM
    folders AS f
  WHERE
    id = $1::uuid
  UNION ALL
  SELECT
    f.id, f.name, f.icon, f.workspace_id, f.parent_id, f.created_at, f.updated_at, f.trashed_by, f.trashed_at
  FROM
    folders AS f
    INNER JOIN child_folders AS cf ON f.parent_id = cf.id
)
SELECT
  id, name, icon, workspace_id, parent_id, created_at, updated_at, trashed_by, trashed_at
FROM
  child_folders
WHERE
  id != $1::uuid -- :if $2
FOR UPDATE -- :if $3
`

var _getRecursiveChildrenDynQ = dynCompile(getRecursiveChildren)

type GetRecursiveChildrenParams struct {
	ID          uuid.UUID
	ExcludeRoot bool
	ForUpdate   bool
}

type GetRecursiveChildrenRow struct {
	ID          uuid.UUID
	Name        string
	Icon        *string
	WorkspaceID uuid.UUID
	ParentID    *uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	TrashedBy   *string
	TrashedAt   *time.Time
}

func (q *Queries) GetRecursiveChildren(ctx context.Context, arg GetRecursiveChildrenParams) ([]*GetRecursiveChildrenRow, error) {
	ctx, span := otel.Tracer("Queries").Start(ctx, "GetRecursiveChildren")
	defer span.End()
	dynQuery, dynArgs := _getRecursiveChildrenDynQ.Build([]any{arg.ID, arg.ExcludeRoot, arg.ForUpdate})
	rows, err := q.db.Query(ctx, dynQuery, dynArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetRecursiveChildrenRow
	for rows.Next() {
		var i GetRecursiveChildrenRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.WorkspaceID,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TrashedBy,
			&i.TrashedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkspaceIDByFolderID = `-- name: GetWorkspaceIDByFolderID :one
SELECT
  workspace_id
FROM
  folders
WHERE
  id = $1
`

func (q *Queries) GetWorkspaceIDByFolderID(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	ctx, span := otel.Tracer("Queries").Start(ctx, "GetWorkspaceIDByFolderID")
	defer span.End()
	row := q.db.QueryRow(ctx, getWorkspaceIDByFolderID, id)
	var workspace_id uuid.UUID
	err := row.Scan(&workspace_id)
	return workspace_id, err
}

type InsertTempFoldersParams struct {
	ID          uuid.UUID
	Name        string
	Icon        *string
	WorkspaceID uuid.UUID
	ParentID    *uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	TrashedBy   *string
	TrashedAt   *time.Time
}

const permanentlyDeleteFolderByID = `-- name: PermanentlyDeleteFolderByID :exec
DELETE FROM
  folders
WHERE
  id = $1
`

func (q *Queries) PermanentlyDeleteFolderByID(ctx context.Context, id uuid.UUID) error {
	ctx, span := otel.Tracer("Queries").Start(ctx, "PermanentlyDeleteFolderByID")
	defer span.End()
	_, err := q.db.Exec(ctx, permanentlyDeleteFolderByID, id)
	return err
}

const permanentlyDeleteFoldersByIDs = `-- name: PermanentlyDeleteFoldersByIDs :exec
DELETE FROM
  folders
WHERE
  id = ANY($1::uuid[])
`

func (q *Queries) PermanentlyDeleteFoldersByIDs(ctx context.Context, ids []uuid.UUID) error {
	ctx, span := otel.Tracer("Queries").Start(ctx, "PermanentlyDeleteFoldersByIDs")
	defer span.End()
	_, err := q.db.Exec(ctx, permanentlyDeleteFoldersByIDs, ids)
	return err
}

const saveFolder = `-- name: SaveFolder :exec
INSERT INTO folders (
  id,
  name,
  icon,
  workspace_id,
  parent_id,
  created_at,
  updated_at,
  trashed_by,
  trashed_at
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  icon = EXCLUDED.icon,
  parent_id = EXCLUDED.parent_id,
  updated_at = EXCLUDED.updated_at,
  trashed_by = EXCLUDED.trashed_by,
  trashed_at = EXCLUDED.trashed_at
`

type SaveFolderParams struct {
	ID          uuid.UUID
	Name        string
	Icon        *string
	WorkspaceID uuid.UUID
	ParentID    *uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	TrashedBy   *string
	TrashedAt   *time.Time
}

func (q *Queries) SaveFolder(ctx context.Context, arg *SaveFolderParams) error {
	ctx, span := otel.Tracer("Queries").Start(ctx, "SaveFolder")
	defer span.End()
	_, err := q.db.Exec(ctx, saveFolder,
		arg.ID,
		arg.Name,
		arg.Icon,
		arg.WorkspaceID,
		arg.ParentID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.TrashedBy,
		arg.TrashedAt,
	)
	return err
}

const saveFromTempFolders = `-- name: SaveFromTempFolders :exec
INSERT INTO folders (
  id,
  name,
  icon,
  workspace_id,
  parent_id,
  created_at,
  updated_at,
  trashed_by,
  trashed_at
)
SELECT
  id,
  name,
  icon,
  workspace_id,
  parent_id,
  created_at,
  updated_at,
  trashed_by,
  trashed_at
FROM
  temp_folders
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  icon = EXCLUDED.icon,
  parent_id = EXCLUDED.parent_id,
  updated_at = EXCLUDED.updated_at,
  trashed_by = EXCLUDED.trashed_by,
  trashed_at = EXCLUDED.trashed_at
`

func (q *Queries) SaveFromTempFolders(ctx context.Context) error {
	ctx, span := otel.Tracer("Queries").Start(ctx, "SaveFromTempFolders")
	defer span.End()
	_, err := q.db.Exec(ctx, saveFromTempFolders)
	return err
}
