// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: folder_read.sql

package pgsqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"go.opentelemetry.io/otel"
)

const readGetFolder = `-- name: ReadGetFolder :one
SELECT
  id, name, icon, workspace_id, parent_id, created_at, updated_at, trashed_by, trashed_at
FROM
  folders
WHERE
  id = $1
  AND workspace_id = $2::uuid -- :if $2
  AND parent_id = $3::uuid -- :if $3
  AND ( -- :if $4
    trashed_by = $4::text -- :if $4
    OR trashed_by IS NULL -- :if $4
  ) -- :if $4
  AND trashed_by IS NULL -- :if $5
  AND trashed_by IS NOT NULL -- :if $6
`

var _readGetFolderDynQ = dynCompile(readGetFolder)

type ReadGetFolderParams struct {
	ID             uuid.UUID
	WorkspaceID    *uuid.UUID
	ParentID       *uuid.UUID
	TrashedBy      *string
	OnlyNonTrashed bool
	OnlyTrashed    bool
}

// TODO: Check not use params
func (q *Queries) ReadGetFolder(ctx context.Context, arg *ReadGetFolderParams) (*Folder, error) {
	ctx, span := otel.Tracer("Queries").Start(ctx, "ReadGetFolder")
	defer span.End()
	dynQuery, dynArgs := _readGetFolderDynQ.Build([]any{arg.ID, arg.WorkspaceID, arg.ParentID, arg.TrashedBy, arg.OnlyNonTrashed, arg.OnlyTrashed})
	row := q.db.QueryRow(ctx, dynQuery, dynArgs...)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Icon,
		&i.WorkspaceID,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TrashedBy,
		&i.TrashedAt,
	)
	return &i, err
}

const readGetFolderByID = `-- name: ReadGetFolderByID :one
SELECT
  id, name, icon, workspace_id, parent_id, created_at, updated_at, trashed_by, trashed_at
FROM
  folders
WHERE
  id = $1
  AND trashed_at IS NULL
`

func (q *Queries) ReadGetFolderByID(ctx context.Context, id uuid.UUID) (*Folder, error) {
	ctx, span := otel.Tracer("Queries").Start(ctx, "ReadGetFolderByID")
	defer span.End()
	row := q.db.QueryRow(ctx, readGetFolderByID, id)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Icon,
		&i.WorkspaceID,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TrashedBy,
		&i.TrashedAt,
	)
	return &i, err
}

const readGetRecursiveFolderByParentID = `-- name: ReadGetRecursiveFolderByParentID :many

WITH RECURSIVE subfolders AS (
  SELECT
    id, name, icon, workspace_id, parent_id, created_at, updated_at, trashed_by, trashed_at,
    1 AS depth
  FROM
    folders
  WHERE
    parent_id = $1::uuid
    AND CASE
      WHEN $2::bool = FALSE
      THEN trashed_at IS NULL
      ELSE TRUE
    END
  UNION ALL
  SELECT
    f.id, f.name, f.icon, f.workspace_id, f.parent_id, f.created_at, f.updated_at, f.trashed_by, f.trashed_at,
    s.depth + 1 AS depth
  FROM
    folders AS f
    INNER JOIN subfolders s ON f.parent_id = s.id
  WHERE
    s.depth < COALESCE($3::int, 9999)
    AND CASE
      WHEN $2::bool = FALSE
      THEN f.trashed_at IS NULL
      ELSE TRUE
    END
)
SELECT
  id, name, icon, workspace_id, parent_id, created_at, updated_at, trashed_by, trashed_at, depth
FROM
  subfolders
`

type ReadGetRecursiveFolderByParentIDParams struct {
	ParentID       uuid.UUID
	IncludeTrashed bool
	Depth          *int32
}

type ReadGetRecursiveFolderByParentIDRow struct {
	ID          uuid.UUID
	Name        string
	Icon        *string
	WorkspaceID uuid.UUID
	ParentID    *uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	TrashedBy   *string
	TrashedAt   *time.Time
	Depth       int32
}

// TODO: Should give sqlc dynamic a try, if it run nicely, then it would be more performant
func (q *Queries) ReadGetRecursiveFolderByParentID(ctx context.Context, arg *ReadGetRecursiveFolderByParentIDParams) ([]*ReadGetRecursiveFolderByParentIDRow, error) {
	ctx, span := otel.Tracer("Queries").Start(ctx, "ReadGetRecursiveFolderByParentID")
	defer span.End()
	rows, err := q.db.Query(ctx, readGetRecursiveFolderByParentID, arg.ParentID, arg.IncludeTrashed, arg.Depth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ReadGetRecursiveFolderByParentIDRow
	for rows.Next() {
		var i ReadGetRecursiveFolderByParentIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.WorkspaceID,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TrashedBy,
			&i.TrashedAt,
			&i.Depth,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readGetRootFolderIDsByWorkspaceID = `-- name: ReadGetRootFolderIDsByWorkspaceID :many
SELECT
  id
FROM
  folders
WHERE
  workspace_id = $1
  AND parent_id IS NULL
`

func (q *Queries) ReadGetRootFolderIDsByWorkspaceID(ctx context.Context, workspaceID uuid.UUID) ([]uuid.UUID, error) {
	ctx, span := otel.Tracer("Queries").Start(ctx, "ReadGetRootFolderIDsByWorkspaceID")
	defer span.End()
	rows, err := q.db.Query(ctx, readGetRootFolderIDsByWorkspaceID, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readGetTrashedFolderByWorkspaceID = `-- name: ReadGetTrashedFolderByWorkspaceID :many
SELECT
  id, name, icon, workspace_id, parent_id, created_at, updated_at, trashed_by, trashed_at
FROM
  folders
WHERE
  workspace_id = $1
  AND trashed_at IS NOT NULL
`

func (q *Queries) ReadGetTrashedFolderByWorkspaceID(ctx context.Context, workspaceID uuid.UUID) ([]*Folder, error) {
	ctx, span := otel.Tracer("Queries").Start(ctx, "ReadGetTrashedFolderByWorkspaceID")
	defer span.End()
	rows, err := q.db.Query(ctx, readGetTrashedFolderByWorkspaceID, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Folder
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.WorkspaceID,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TrashedBy,
			&i.TrashedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
