// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: note.sql

package pgsqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"go.opentelemetry.io/otel"
)

const countNotesInWorkspaceByIDs = `-- name: CountNotesInWorkspaceByIDs :one
SELECT
  COUNT(*)
FROM
  notes AS n
INNER JOIN
  folders f
  ON n.folder_id = f.id
WHERE
  f.workspace_id = $1
  AND n.id = ANY($2::uuid[])
`

type CountNotesInWorkspaceByIDsParams struct {
	WorkspaceID uuid.UUID
	IDs         []uuid.UUID
}

func (q *Queries) CountNotesInWorkspaceByIDs(ctx context.Context, arg *CountNotesInWorkspaceByIDsParams) (int64, error) {
	ctx, span := otel.Tracer("Queries").Start(ctx, "CountNotesInWorkspaceByIDs")
	defer span.End()
	row := q.db.QueryRow(ctx, countNotesInWorkspaceByIDs, arg.WorkspaceID, arg.IDs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getNoteByID = `-- name: GetNoteByID :one
SELECT
  id, name, icon, folder_id, tags, size, created_at, updated_at, trashed_by, trashed_at
FROM
  notes
WHERE
  id = $1
FOR UPDATE -- :if $2
`

var _getNoteByIDDynQ = dynCompile(getNoteByID)

type GetNoteByIDParams struct {
	ID        uuid.UUID
	ForUpdate bool
}

func (q *Queries) GetNoteByID(ctx context.Context, arg GetNoteByIDParams) (*Note, error) {
	ctx, span := otel.Tracer("Queries").Start(ctx, "GetNoteByID")
	defer span.End()
	dynQuery, dynArgs := _getNoteByIDDynQ.Build([]any{arg.ID, arg.ForUpdate})
	row := q.db.QueryRow(ctx, dynQuery, dynArgs...)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Icon,
		&i.FolderID,
		&i.Tags,
		&i.Size,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TrashedBy,
		&i.TrashedAt,
	)
	return &i, err
}

const getNotes = `-- name: GetNotes :many
SELECT
  id, name, icon, folder_id, tags, size, created_at, updated_at, trashed_by, trashed_at
FROM
  notes
WHERE
  id = ANY($1::uuid[]) -- :if $1
  AND folder_id IN (
    SELECT id FROM folders WHERE workspace_id = $2::uuid
  ) -- :if $2
  AND ( -- :if $3
    trashed_by = $3::text -- :if $3
    OR trashed_by IS NULL -- :if $3
  ) -- :if $3
  AND trashed_by IS NOT NULL -- :if $4
FOR UPDATE -- :if $5
`

var _getNotesDynQ = dynCompile(getNotes)

type GetNotesParams struct {
	IDs         *[]uuid.UUID
	WorkspaceID *uuid.UUID
	TrashedBy   *string
	TrashedOnly bool
	ForUpdate   bool
}

func (q *Queries) GetNotes(ctx context.Context, arg *GetNotesParams) ([]*Note, error) {
	ctx, span := otel.Tracer("Queries").Start(ctx, "GetNotes")
	defer span.End()
	dynQuery, dynArgs := _getNotesDynQ.Build([]any{arg.IDs, arg.WorkspaceID, arg.TrashedBy, arg.TrashedOnly, arg.ForUpdate})
	rows, err := q.db.Query(ctx, dynQuery, dynArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.FolderID,
			&i.Tags,
			&i.Size,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TrashedBy,
			&i.TrashedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecursiveChildrenFromFolder = `-- name: GetRecursiveChildrenFromFolder :many
WITH RECURSIVE subfolders AS (
  SELECT
    id
  FROM
    folders
  WHERE
    id = $1::uuid
  UNION ALL
  SELECT
    f.id
  FROM
    folders f
  INNER JOIN
    subfolders sf
    ON f.parent_id = sf.id
)
SELECT
  n.id, n.name, n.icon, n.folder_id, n.tags, n.size, n.created_at, n.updated_at, n.trashed_by, n.trashed_at
FROM
  notes n
INNER JOIN
  subfolders sf
  ON n.folder_id = sf.id
FOR UPDATE -- :if $2
`

var _getRecursiveChildrenFromFolderDynQ = dynCompile(getRecursiveChildrenFromFolder)

type GetRecursiveChildrenFromFolderParams struct {
	FolderID  uuid.UUID
	ForUpdate bool
}

func (q *Queries) GetRecursiveChildrenFromFolder(ctx context.Context, arg GetRecursiveChildrenFromFolderParams) ([]*Note, error) {
	ctx, span := otel.Tracer("Queries").Start(ctx, "GetRecursiveChildrenFromFolder")
	defer span.End()
	dynQuery, dynArgs := _getRecursiveChildrenFromFolderDynQ.Build([]any{arg.FolderID, arg.ForUpdate})
	rows, err := q.db.Query(ctx, dynQuery, dynArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.FolderID,
			&i.Tags,
			&i.Size,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TrashedBy,
			&i.TrashedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkspaceIDByNoteID = `-- name: GetWorkspaceIDByNoteID :one
SELECT
  f.workspace_id
FROM
  notes AS n
INNER JOIN
  folders f
  ON n.folder_id = f.id
WHERE
  n.id = $1
`

func (q *Queries) GetWorkspaceIDByNoteID(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	ctx, span := otel.Tracer("Queries").Start(ctx, "GetWorkspaceIDByNoteID")
	defer span.End()
	row := q.db.QueryRow(ctx, getWorkspaceIDByNoteID, id)
	var workspace_id uuid.UUID
	err := row.Scan(&workspace_id)
	return workspace_id, err
}

const getWorkspaceIDsByNoteIDs = `-- name: GetWorkspaceIDsByNoteIDs :many
SELECT
  n.id,
  f.workspace_id
FROM
  notes AS n
INNER JOIN
  folders f
  ON n.folder_id = f.id
WHERE
  n.id = ANY($1::uuid[])
`

type GetWorkspaceIDsByNoteIDsRow struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) GetWorkspaceIDsByNoteIDs(ctx context.Context, ids []uuid.UUID) ([]*GetWorkspaceIDsByNoteIDsRow, error) {
	ctx, span := otel.Tracer("Queries").Start(ctx, "GetWorkspaceIDsByNoteIDs")
	defer span.End()
	rows, err := q.db.Query(ctx, getWorkspaceIDsByNoteIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetWorkspaceIDsByNoteIDsRow
	for rows.Next() {
		var i GetWorkspaceIDsByNoteIDsRow
		if err := rows.Scan(&i.ID, &i.WorkspaceID); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

type InsertTempNotesParams struct {
	ID        uuid.UUID
	Name      string
	Icon      *string
	FolderID  uuid.UUID
	Tags      []string
	Size      int32
	CreatedAt time.Time
	UpdatedAt time.Time
	TrashedBy *string
	TrashedAt *time.Time
}

const permanentlyDeleteNoteByID = `-- name: PermanentlyDeleteNoteByID :exec
DELETE FROM
  notes
WHERE
  id = $1
`

func (q *Queries) PermanentlyDeleteNoteByID(ctx context.Context, id uuid.UUID) error {
	ctx, span := otel.Tracer("Queries").Start(ctx, "PermanentlyDeleteNoteByID")
	defer span.End()
	_, err := q.db.Exec(ctx, permanentlyDeleteNoteByID, id)
	return err
}

const permanentlyDeleteNotesByIDs = `-- name: PermanentlyDeleteNotesByIDs :exec
DELETE FROM
  notes
WHERE
  id = ANY($1::uuid[])
`

func (q *Queries) PermanentlyDeleteNotesByIDs(ctx context.Context, ids []uuid.UUID) error {
	ctx, span := otel.Tracer("Queries").Start(ctx, "PermanentlyDeleteNotesByIDs")
	defer span.End()
	_, err := q.db.Exec(ctx, permanentlyDeleteNotesByIDs, ids)
	return err
}

const saveFromTempNotes = `-- name: SaveFromTempNotes :exec
INSERT INTO notes (
  id,
  name,
  icon,
  folder_id,
  tags,
  size,
  created_at,
  updated_at,
  trashed_by,
  trashed_at
)
SELECT
  id,
  name,
  icon,
  folder_id,
  tags,
  size,
  created_at,
  updated_at,
  trashed_by,
  trashed_at
FROM
  temp_notes
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  icon = EXCLUDED.icon,
  folder_id = EXCLUDED.folder_id,
  tags = EXCLUDED.tags,
  size = EXCLUDED.size,
  updated_at = EXCLUDED.updated_at,
  trashed_by = EXCLUDED.trashed_by,
  trashed_at = EXCLUDED.trashed_at
`

func (q *Queries) SaveFromTempNotes(ctx context.Context) error {
	ctx, span := otel.Tracer("Queries").Start(ctx, "SaveFromTempNotes")
	defer span.End()
	_, err := q.db.Exec(ctx, saveFromTempNotes)
	return err
}

const saveNote = `-- name: SaveNote :exec
INSERT INTO notes (
  id,
  name,
  icon,
  folder_id,
  tags,
  size,
  created_at,
  updated_at,
  trashed_by,
  trashed_at
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  icon = EXCLUDED.icon,
  folder_id = EXCLUDED.folder_id,
  tags = EXCLUDED.tags,
  size = EXCLUDED.size,
  updated_at = EXCLUDED.updated_at,
  trashed_by = EXCLUDED.trashed_by,
  trashed_at = EXCLUDED.trashed_at
`

type SaveNoteParams struct {
	ID        uuid.UUID
	Name      string
	Icon      *string
	FolderID  uuid.UUID
	Tags      []string
	Size      int32
	CreatedAt time.Time
	UpdatedAt time.Time
	TrashedBy *string
	TrashedAt *time.Time
}

func (q *Queries) SaveNote(ctx context.Context, arg *SaveNoteParams) error {
	ctx, span := otel.Tracer("Queries").Start(ctx, "SaveNote")
	defer span.End()
	_, err := q.db.Exec(ctx, saveNote,
		arg.ID,
		arg.Name,
		arg.Icon,
		arg.FolderID,
		arg.Tags,
		arg.Size,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.TrashedBy,
		arg.TrashedAt,
	)
	return err
}
