// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: note_read.sql

package pgsqlc

import (
	"context"

	"github.com/google/uuid"
	"go.opentelemetry.io/otel"
)

const readCountNoteBacklinks = `-- name: ReadCountNoteBacklinks :one
SELECT
  COUNT(*)
FROM
  note_links
WHERE
  target_id = $1
`

func (q *Queries) ReadCountNoteBacklinks(ctx context.Context, noteID uuid.UUID) (int64, error) {
	ctx, span := otel.Tracer("Queries").Start(ctx, "ReadCountNoteBacklinks")
	defer span.End()
	row := q.db.QueryRow(ctx, readCountNoteBacklinks, noteID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const readCountNoteOutgoingLinks = `-- name: ReadCountNoteOutgoingLinks :one
SELECT
  COUNT(*)
FROM
  note_links
WHERE
  source_id = $1
`

func (q *Queries) ReadCountNoteOutgoingLinks(ctx context.Context, noteID uuid.UUID) (int64, error) {
	ctx, span := otel.Tracer("Queries").Start(ctx, "ReadCountNoteOutgoingLinks")
	defer span.End()
	row := q.db.QueryRow(ctx, readCountNoteOutgoingLinks, noteID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const readGetNoteByID = `-- name: ReadGetNoteByID :one
SELECT
  id, name, icon, folder_id, tags, size, created_at, updated_at, trashed_by, trashed_at
FROM
  notes
WHERE
  id = $1
`

func (q *Queries) ReadGetNoteByID(ctx context.Context, id uuid.UUID) (*Note, error) {
	ctx, span := otel.Tracer("Queries").Start(ctx, "ReadGetNoteByID")
	defer span.End()
	row := q.db.QueryRow(ctx, readGetNoteByID, id)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Icon,
		&i.FolderID,
		&i.Tags,
		&i.Size,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TrashedBy,
		&i.TrashedAt,
	)
	return &i, err
}

const readGetNotes = `-- name: ReadGetNotes :many
SELECT
  id, name, icon, folder_id, tags, size, created_at, updated_at, trashed_by, trashed_at
FROM
  notes
WHERE
  id = ANY($1::uuid[]) -- :if $1
  AND folder_id IN ( -- :if $2
    SELECT id FROM folders WHERE workspace_id = $2::uuid -- :if $2
  ) -- :if $2
  AND ( -- :if $3
    trashed_by = $3::text -- :if $3
    OR trashed_by IS NULL -- :if $3
  ) -- :if $3
  AND trashed_by IS NULL -- :if $4
  AND trashed_by IS NOT NULL -- :if $5
`

var _readGetNotesDynQ = dynCompile(readGetNotes)

type ReadGetNotesParams struct {
	IDs            *[]uuid.UUID
	WorkspaceID    *uuid.UUID
	TrashedBy      *string
	NonTrashedOnly bool
	TrashedOnly    bool
}

// TODO: Check if backlinks or outgoing link need those params
func (q *Queries) ReadGetNotes(ctx context.Context, arg *ReadGetNotesParams) ([]*Note, error) {
	ctx, span := otel.Tracer("Queries").Start(ctx, "ReadGetNotes")
	defer span.End()
	dynQuery, dynArgs := _readGetNotesDynQ.Build([]any{arg.IDs, arg.WorkspaceID, arg.TrashedBy, arg.NonTrashedOnly, arg.TrashedOnly})
	rows, err := q.db.Query(ctx, dynQuery, dynArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.FolderID,
			&i.Tags,
			&i.Size,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TrashedBy,
			&i.TrashedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readGetNotesByFolderIDs = `-- name: ReadGetNotesByFolderIDs :many
SELECT
  id, name, icon, folder_id, tags, size, created_at, updated_at, trashed_by, trashed_at
FROM
  notes
WHERE
  folder_id = ANY($1::uuid[])
  AND trashed_at IS NULL -- :if $2
`

var _readGetNotesByFolderIDsDynQ = dynCompile(readGetNotesByFolderIDs)

type ReadGetNotesByFolderIDsParams struct {
	FolderIds    []uuid.UUID
	ExcludeTrash bool
}

func (q *Queries) ReadGetNotesByFolderIDs(ctx context.Context, arg ReadGetNotesByFolderIDsParams) ([]*Note, error) {
	ctx, span := otel.Tracer("Queries").Start(ctx, "ReadGetNotesByFolderIDs")
	defer span.End()
	dynQuery, dynArgs := _readGetNotesByFolderIDsDynQ.Build([]any{arg.FolderIds, arg.ExcludeTrash})
	rows, err := q.db.Query(ctx, dynQuery, dynArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.FolderID,
			&i.Tags,
			&i.Size,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TrashedBy,
			&i.TrashedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readGetNotesByIDs = `-- name: ReadGetNotesByIDs :many
SELECT
  id, name, icon, folder_id, tags, size, created_at, updated_at, trashed_by, trashed_at
FROM
  notes
WHERE
  id = ANY($1::uuid[])
`

func (q *Queries) ReadGetNotesByIDs(ctx context.Context, ids []uuid.UUID) ([]*Note, error) {
	ctx, span := otel.Tracer("Queries").Start(ctx, "ReadGetNotesByIDs")
	defer span.End()
	rows, err := q.db.Query(ctx, readGetNotesByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.FolderID,
			&i.Tags,
			&i.Size,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TrashedBy,
			&i.TrashedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readGetNotesInWorkspace = `-- name: ReadGetNotesInWorkspace :many
SELECT
  n.id, n.name, n.icon, n.folder_id, n.tags, n.size, n.created_at, n.updated_at, n.trashed_by, n.trashed_at
FROM
  notes AS n
INNER JOIN
  folders f
  ON n.folder_id = f.id
WHERE
  f.workspace_id = $1
  AND n.trashed_at IS NULL -- :if $2
`

var _readGetNotesInWorkspaceDynQ = dynCompile(readGetNotesInWorkspace)

type ReadGetNotesInWorkspaceParams struct {
	WorkspaceID  uuid.UUID
	ExcludeTrash bool
}

func (q *Queries) ReadGetNotesInWorkspace(ctx context.Context, arg ReadGetNotesInWorkspaceParams) ([]*Note, error) {
	ctx, span := otel.Tracer("Queries").Start(ctx, "ReadGetNotesInWorkspace")
	defer span.End()
	dynQuery, dynArgs := _readGetNotesInWorkspaceDynQ.Build([]any{arg.WorkspaceID, arg.ExcludeTrash})
	rows, err := q.db.Query(ctx, dynQuery, dynArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.FolderID,
			&i.Tags,
			&i.Size,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TrashedBy,
			&i.TrashedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readGetTrashedNotesByWorkspaceID = `-- name: ReadGetTrashedNotesByWorkspaceID :many
SELECT
  n.id, n.name, n.icon, n.folder_id, n.tags, n.size, n.created_at, n.updated_at, n.trashed_by, n.trashed_at
FROM
  notes AS n
INNER JOIN
  folders f
  ON n.folder_id = f.id
WHERE
  f.workspace_id = $1
  AND n.trashed_at IS NOT NULL
ORDER BY
  n.trashed_at DESC
`

func (q *Queries) ReadGetTrashedNotesByWorkspaceID(ctx context.Context, workspaceID uuid.UUID) ([]*Note, error) {
	ctx, span := otel.Tracer("Queries").Start(ctx, "ReadGetTrashedNotesByWorkspaceID")
	defer span.End()
	rows, err := q.db.Query(ctx, readGetTrashedNotesByWorkspaceID, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.FolderID,
			&i.Tags,
			&i.Size,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TrashedBy,
			&i.TrashedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
