// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: note_link.sql

package pgsqlc

import (
	"context"

	"github.com/google/uuid"
	"go.opentelemetry.io/otel"
)

const deleteObsoleteNoteLinks = `-- name: DeleteObsoleteNoteLinks :exec
DELETE FROM note_links AS nl
WHERE
  EXISTS (
    SELECT 1
    FROM temp_note_links AS tnl
    WHERE tnl.source_id = nl.source_id
  )
  AND NOT EXISTS (
    SELECT 1
    FROM temp_note_links AS tnl
    WHERE tnl.source_id = nl.source_id
    AND tnl.target_id = nl.target_id
  )
`

func (q *Queries) DeleteObsoleteNoteLinks(ctx context.Context) error {
	ctx, span := otel.Tracer("Queries").Start(ctx, "DeleteObsoleteNoteLinks")
	defer span.End()
	_, err := q.db.Exec(ctx, deleteObsoleteNoteLinks)
	return err
}

const getNoteOutgoingLinks = `-- name: GetNoteOutgoingLinks :many
SELECT
  target_id
FROM
  note_links
WHERE
  source_id = $1::uuid
`

func (q *Queries) GetNoteOutgoingLinks(ctx context.Context, sourceID uuid.UUID) ([]uuid.UUID, error) {
	ctx, span := otel.Tracer("Queries").Start(ctx, "GetNoteOutgoingLinks")
	defer span.End()
	rows, err := q.db.Query(ctx, getNoteOutgoingLinks, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var target_id uuid.UUID
		if err := rows.Scan(&target_id); err != nil {
			return nil, err
		}
		items = append(items, target_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotesOutgoingLinks = `-- name: GetNotesOutgoingLinks :many
SELECT
  source_id,
  ARRAY_AGG(target_id)::uuid[] AS target_ids
FROM
  note_links
WHERE
  source_id = ANY($1::uuid[])
GROUP BY
  source_id
`

type GetNotesOutgoingLinksRow struct {
	SourceID  uuid.UUID
	TargetIDs []uuid.UUID
}

func (q *Queries) GetNotesOutgoingLinks(ctx context.Context, sourceIds []uuid.UUID) ([]*GetNotesOutgoingLinksRow, error) {
	ctx, span := otel.Tracer("Queries").Start(ctx, "GetNotesOutgoingLinks")
	defer span.End()
	rows, err := q.db.Query(ctx, getNotesOutgoingLinks, sourceIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetNotesOutgoingLinksRow
	for rows.Next() {
		var i GetNotesOutgoingLinksRow
		if err := rows.Scan(&i.SourceID, &i.TargetIDs); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

type InsertTempNoteLinksParams struct {
	SourceID uuid.UUID
	TargetID uuid.UUID
}

const saveFromTempNoteLinks = `-- name: SaveFromTempNoteLinks :exec
INSERT INTO note_links (
  source_id,
  target_id
)
SELECT
  source_id,
  target_id
FROM
  temp_note_links
ON CONFLICT DO NOTHING
`

func (q *Queries) SaveFromTempNoteLinks(ctx context.Context) error {
	ctx, span := otel.Tracer("Queries").Start(ctx, "SaveFromTempNoteLinks")
	defer span.End()
	_, err := q.db.Exec(ctx, saveFromTempNoteLinks)
	return err
}
