// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: temp_tables.sql

package pgsqlc

import (
	"context"
)

const createTempTableFolders = `-- name: CreateTempTableFolders :exec
CREATE TEMP TABLE temp_folders (
  id UUID PRIMARY KEY,
  name TEXT NOT NULL,
  icon TEXT,
  workspace_id UUID NOT NULL,
  parent_id UUID,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
  trashed_by trashed_by,
  trashed_at TIMESTAMPTZ
) ON COMMIT DROP
`

func (q *Queries) CreateTempTableFolders(ctx context.Context) error {
	_, err := q.db.Exec(ctx, createTempTableFolders)
	return err
}

const createTempTableNotes = `-- name: CreateTempTableNotes :exec
CREATE TEMP TABLE temp_notes (
  id UUID PRIMARY KEY,
  name TEXT NOT NULL,
  icon TEXT,
  folder_id UUID NOT NULL,
  tags TEXT[],
  size INTEGER DEFAULT 0 NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
  trashed_by trashed_by,
  trashed_at TIMESTAMPTZ
) ON COMMIT DROP
`

func (q *Queries) CreateTempTableNotes(ctx context.Context) error {
	_, err := q.db.Exec(ctx, createTempTableNotes)
	return err
}
