// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspace_read.sql

package pgsqlc

import (
	"context"

	"github.com/google/uuid"
	"go.opentelemetry.io/otel"
)

const readCheckSlugExists = `-- name: ReadCheckSlugExists :one
SELECT EXISTS(
  SELECT
    1
  FROM
    workspaces
  WHERE
    slug = $1::text
    AND deleted_at IS NULL
) AS exists
`

func (q *Queries) ReadCheckSlugExists(ctx context.Context, slug string) (bool, error) {
	ctx, span := otel.Tracer("Queries").Start(ctx, "ReadCheckSlugExists")
	defer span.End()
	row := q.db.QueryRow(ctx, readCheckSlugExists, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const readGetWorkspaceBySlug = `-- name: ReadGetWorkspaceBySlug :one
SELECT
  id, slug, name, created_at, updated_at, deleted_at
FROM
  workspaces
WHERE
  slug = $1::text
  AND deleted_at IS NULL
`

func (q *Queries) ReadGetWorkspaceBySlug(ctx context.Context, slug string) (*Workspace, error) {
	ctx, span := otel.Tracer("Queries").Start(ctx, "ReadGetWorkspaceBySlug")
	defer span.End()
	row := q.db.QueryRow(ctx, readGetWorkspaceBySlug, slug)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const readGetWorkspacesByIDs = `-- name: ReadGetWorkspacesByIDs :many
SELECT
  id, slug, name, created_at, updated_at, deleted_at
FROM
  workspaces
WHERE
  id = ANY($1::uuid[])
  AND deleted_at IS NULL
`

func (q *Queries) ReadGetWorkspacesByIDs(ctx context.Context, ids []uuid.UUID) ([]*Workspace, error) {
	ctx, span := otel.Tracer("Queries").Start(ctx, "ReadGetWorkspacesByIDs")
	defer span.End()
	rows, err := q.db.Query(ctx, readGetWorkspacesByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Workspace
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
