// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspace.sql

package pgsqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"go.opentelemetry.io/otel"
)

const checkSlugExists = `-- name: CheckSlugExists :one
SELECT EXISTS(
  SELECT
    1
  FROM
    workspaces
  WHERE
    slug = $1::text
    AND deleted_at IS NULL
) AS exists
`

func (q *Queries) CheckSlugExists(ctx context.Context, slug string) (bool, error) {
	ctx, span := otel.Tracer("Queries").Start(ctx, "CheckSlugExists")
	defer span.End()
	row := q.db.QueryRow(ctx, checkSlugExists, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT
  id, slug, name, created_at, updated_at, deleted_at
FROM
  workspaces
WHERE
  1 = 1
  AND slug = $1::text -- :if $1
  AND id = $2::uuid -- :if $2
  AND deleted_at IS NULL
FOR UPDATE -- :if $3
`

var _getWorkspaceDynQ = dynCompile(getWorkspace)

type GetWorkspaceParams struct {
	Slug      *string
	ID        *uuid.UUID
	ForUpdate bool
}

func (q *Queries) GetWorkspace(ctx context.Context, arg *GetWorkspaceParams) (*Workspace, error) {
	ctx, span := otel.Tracer("Queries").Start(ctx, "GetWorkspace")
	defer span.End()
	dynQuery, dynArgs := _getWorkspaceDynQ.Build([]any{arg.Slug, arg.ID, arg.ForUpdate})
	row := q.db.QueryRow(ctx, dynQuery, dynArgs...)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const getWorkspaceIDBySlug = `-- name: GetWorkspaceIDBySlug :one
SELECT
  id
FROM
  workspaces
WHERE
  slug = $1::text
  AND deleted_at IS NULL
`

func (q *Queries) GetWorkspaceIDBySlug(ctx context.Context, slug string) (uuid.UUID, error) {
	ctx, span := otel.Tracer("Queries").Start(ctx, "GetWorkspaceIDBySlug")
	defer span.End()
	row := q.db.QueryRow(ctx, getWorkspaceIDBySlug, slug)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const saveWorkspace = `-- name: SaveWorkspace :exec
INSERT INTO workspaces (
  id,
  slug,
  name,
  created_at,
  updated_at,
  deleted_at
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6
)
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug,
  name = EXCLUDED.name,
  updated_at = EXCLUDED.updated_at,
  deleted_at = EXCLUDED.deleted_at
`

type SaveWorkspaceParams struct {
	ID        uuid.UUID
	Slug      string
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt *time.Time
}

func (q *Queries) SaveWorkspace(ctx context.Context, arg *SaveWorkspaceParams) error {
	ctx, span := otel.Tracer("Queries").Start(ctx, "SaveWorkspace")
	defer span.End()
	_, err := q.db.Exec(ctx, saveWorkspace,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	return err
}
