syntax = "proto3";

package note;

import "buf/validate/validate.proto";

service NoteService {
  rpc CheckNoteExistence(CheckNoteExistenceRequest) returns (CheckNoteExistenceResponse);
  rpc GetNoteWorkspaceId(GetNoteWorkspaceIdRequest) returns (GetNoteWorkspaceIdResponse);
}

message CheckNoteExistenceRequest {
  string note_id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
}

message CheckNoteExistenceResponse {
  bool exists = 1 [(buf.validate.field).required = true];
}

message GetNoteWorkspaceIdRequest {
  string note_id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
}

message GetNoteWorkspaceIdResponse {
  string workspace_id = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.uuid = true
  ];
}
