## yaml-language-server: $schema=https://www.schemastore.org/openapi-3.X.json
# vim: ft=yaml.openapi
openapi: 3.0.4

servers:
  - url: http://api.notopia.localhost

info:
  description: >
    Notopia API - A comprehensive note-taking service API.
  version: 0.0.0
  title: Notopia API
  license:
    name: MIT
    url: https://github.com/notopia-uit/notopia/blob/main/LICENSE
  contact:
    name: Notopia Support
    email: kevinnitro@duck.com
  x-apiName: note

tags:
  - name: Workspace
    description: Workspace
  - name: Folder
    description: Folder in workspace
  - name: Note
    description: Note in workspace's root folder or in a folder

paths:
  /note/folders:
    $ref: ./paths/folders.yaml
  /note/folders/{folderId}:
    $ref: ./paths/folders_{folderId}.yaml
  /note/folders/{folderId}/rename:
    $ref: ./paths/folders_{folderId}_rename.yaml

  /note/notes:
    $ref: ./paths/notes.yaml
  /note/notes/generate-daily:
    $ref: ./paths/notes_generate-daily.yaml
  /note/notes/{noteId}:
    $ref: ./paths/notes_{noteId}.yaml
  /note/notes/{noteId}/graph:
    $ref: ./paths/notes_{noteId}_graph.yaml
  /note/notes/{noteId}/links:
    $ref: ./paths/notes_{noteId}_links.yaml
  /note/notes/{noteId}/publish:
    $ref: ./paths/notes_{noteId}_publish.yaml
  /note/notes/{noteId}/rename:
    $ref: ./paths/notes_{noteId}_rename.yaml
  /note/notes/{noteId}/unpublish:
    $ref: ./paths/notes_{noteId}_unpublish.yaml

  /note/workspaces:
    $ref: ./paths/workspaces.yaml
  /note/workspaces-by-slug/{workspaceSlug}:
    $ref: ./paths/workspaces-by-slug_{workspaceSlug}.yaml
  /note/workspaces-by-slug/{workspaceSlug}_exists:
    $ref: ./paths/workspaces-by-slug_{workspaceSlug}_exists.yaml
  /note/workspaces/{workspaceId}:
    $ref: ./paths/workspaces_{workspaceId}.yaml
  /note/workspaces/{workspaceId}/events:
    $ref: ./paths/workspaces_{workspaceId}_events.yaml
  /note/workspaces/{workspaceId}/graph:
    $ref: ./paths/workspaces_{workspaceId}_graph.yaml
  /note/workspaces/{workspaceId}/members:
    $ref: ./paths/workspaces_{workspaceId}_members.yaml
  /note/workspaces/{workspaceId}/move-items:
    $ref: ./paths/workspaces_{workspaceId}_move-items.yaml
  /note/workspaces/{workspaceId}/permanently-delete-items:
    $ref: ./paths/workspaces_{workspaceId}_permanently-delete-items.yaml
  /note/workspaces/{workspaceId}/publish:
    $ref: ./paths/workspaces_{workspaceId}_publish.yaml
  /note/workspaces/{workspaceId}/rename:
    $ref: ./paths/workspaces_{workspaceId}_rename.yaml
  /note/workspaces/{workspaceId}/restore-trashed-items:
    $ref: ./paths/workspaces_{workspaceId}_restore-trashed-items.yaml
  /note/workspaces/{workspaceId}/show-trash:
    $ref: ./paths/workspaces_{workspaceId}_show-trash.yaml
  /note/workspaces/{workspaceId}/trash-items:
    $ref: ./paths/workspaces_{workspaceId}_trash-items.yaml
  /note/workspaces/{workspaceId}/tree:
    $ref: ./paths/workspaces_{workspaceId}_tree.yaml
  /note/workspaces/{workspaceId}/unpublish:
    $ref: ./paths/workspaces_{workspaceId}_unpublish.yaml

components:
  securitySchemes:
    Oauth2:
      $ref: ../common/components/securitySchemes/Oauth2.yaml

externalDocs:
  url: https://notopia-uit.github.io/notopia
