## yaml-language-server: $schema=https://www.schemastore.org/openapi-3.X.json
# vim: ft=yaml.openapi
openapi: 3.0.4

servers:
  - url: http://api.notopia.localhost

info:
  description: >
    Notopia API - A comprehensive note-taking service API.
  version: 0.0.0
  title: Notopia API
  license:
    name: MIT
    url: https://github.com/notopia-uit/notopia/blob/main/LICENSE
  contact:
    name: Notopia Support
    email: kevinnitro@duck.com
  x-apiName: note

tags:
  - name: Workspace
    description: Workspace
  - name: Folder
    description: Folder in workspace
  - name: Note
    description: Note in workspace's root folder or in a folder

paths:
  /note/folders:
    $ref: ./paths/folders.yaml
  /note/folders/{folderId}/rename:
    $ref: ./paths/folders_{folderId}_rename.yaml

  /note/notes:
    $ref: ./paths/notes.yaml
  /note/notes/generate-daily:
    $ref: ./paths/notes_generate-daily.yaml
  /note/notes/{noteId}:
    $ref: ./paths/notes_{noteId}.yaml
  /note/notes/{noteId}/graph:
    $ref: ./paths/notes_{noteId}_graph.yaml
  /note/notes/{noteId}/links:
    $ref: ./paths/notes_{noteId}_links.yaml
  /note/notes/{noteId}/publish:
    $ref: ./paths/notes_{noteId}_publish.yaml
  /note/notes/{noteId}/rename:
    $ref: ./paths/notes_{noteId}_rename.yaml
  /note/notes/{noteId}/unpublish:
    $ref: ./paths/notes_{noteId}_unpublish.yaml

  /note/workspaces:
    $ref: ./paths/workspaces.yaml
  /note/workspaces/{workspaceSlug}:
    $ref: ./paths/workspaces_{workspaceSlug}.yaml
  /note/workspaces/{workspaceSlug}/events:
    $ref: ./paths/workspaces_{workspaceSlug}_events.yaml
  /note/workspaces/{workspaceSlug}/graph:
    $ref: ./paths/workspaces_{workspaceSlug}_graph.yaml
  /note/workspaces/{workspaceSlug}/members:
    $ref: ./paths/workspaces_{workspaceSlug}_members.yaml
  /note/workspaces/{workspaceSlug}/move-items:
    $ref: ./paths/workspaces_{workspaceSlug}_move-items.yaml
  /note/workspaces/{workspaceSlug}/publish:
    $ref: ./paths/workspaces_{workspaceSlug}_publish.yaml
  /note/workspaces/{workspaceSlug}/rename:
    $ref: ./paths/workspaces_{workspaceSlug}_rename.yaml
  /note/workspaces/{workspaceSlug}/restore-trashed-items:
    $ref: ./paths/workspaces_{workspaceSlug}_restore-trashed-items.yaml
  /note/workspaces/{workspaceSlug}/show-trash:
    $ref: ./paths/workspaces_{workspaceSlug}_show-trash.yaml
  /note/workspaces/{workspaceSlug}/trash-items:
    $ref: ./paths/workspaces_{workspaceSlug}_trash-items.yaml
  /note/workspaces/{workspaceSlug}/tree:
    $ref: ./paths/workspaces_{workspaceSlug}_tree.yaml
  /note/workspaces/{workspaceSlug}/unpublish:
    $ref: ./paths/workspaces_{workspaceSlug}_unpublish.yaml
  /note/workspaces/{workspaceSlug}/exists:
    $ref: ./paths/workspaces_{workspaceSlug}_exists.yaml

components:
  securitySchemes:
    Oauth2:
      $ref: ../common/components/securitySchemes/Oauth2.yaml

externalDocs:
  url: https://notopia-uit.github.io/notopia
