server:
  http_listen_port: 3200
  grpc_listen_port: 4317

distributor:
  rate_limit_bytes: 5242880
  log_received_spans:
    enabled: true
  log_received_traces:
    enabled: true

ingester:
  trace_idle_period: 10s
  trace_timeout: 10s
  max_block_bytes: 268435456

metrics_generator:
  registry:
    external_labels:
      cluster: notopia
  storage:
    path: /var/tempo/wal
    wal:
      checkpointduration: 5m
      completedblockretention: 10m

storage:
  trace:
    backend: local
    wal:
      path: /var/tempo/wal
    local:
      path: /var/tempo/blocks

querier:
  max_concurrent_queries: 20

query_frontend:
  cache_control_header: 'public, max-age=300'

memberlist:
  node_name: tempo
  retransmit_factor: 4
  dead_node_reclaim_time: 10s
