# vim:ft=yaml.docker-compose:
# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-go/master/schema/compose-spec.json
services:
  alloy:
    container_name: notopia-alloy
    image: grafana/alloy:v1.13.2
    command:
      - run
      - /etc/alloy/config.alloy
      - --server.http.listen-addr=0.0.0.0:12345
    environment:
      TZ: Asia/Ho_Chi_Minh
    ports:
      - 4317:4317
      - 4318:4318
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      traefik.enable: 'true'
      traefik.http.routers.alloy.rule: Host(`alloy.notopia.localhost`)
      traefik.http.routers.alloy.entrypoints: web
      traefik.http.services.alloy.loadbalancer.server.port: '12345'
    profiles:
      - monitoring
    restart: unless-stopped
