# vim:ft=yaml.docker-compose:
# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-go/master/schema/compose-spec.json
services:
  loki:
    container_name: notopia-loki
    image: grafana/loki:3.7.2
    command:
      - -config.file=/etc/loki/config.yaml
      - -config.expand-env=true
    environment:
      TZ: Asia/Ho_Chi_Minh
    volumes:
      - ./loki/config.yaml:/etc/loki/config.yaml:ro
    labels:
      traefik.enable: 'true'
      traefik.http.routers.loki.rule: Host(`loki.notopia.localhost`)
      traefik.http.routers.loki.entrypoints: web
      traefik.http.services.loki.loadbalancer.server.port: '3100'
    profiles:
      - monitoring
    restart: unless-stopped
