// This file is auto-generated by @hey-api/openapi-ts

import { type InfiniteData, infiniteQueryOptions, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { createNote, deleteNote, getNote, listNotes, type Options, patchNote, updateNote, wsEditsDocument } from '../sdk.gen';
import type { CreateNoteData, CreateNoteError, CreateNoteResponse, DeleteNoteData, DeleteNoteError, DeleteNoteResponse, GetNoteData, GetNoteError, GetNoteResponse, ListNotesData, ListNotesError, ListNotesResponse, PatchNoteData, PatchNoteError, PatchNoteResponse, UpdateNoteData, UpdateNoteError, UpdateNoteResponse, WsEditsDocumentData, WsEditsDocumentError } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const wsEditsDocumentQueryKey = (options: Options<WsEditsDocumentData>) => createQueryKey('wsEditsDocument', options);

/**
 * WebSocket for editing a document
 *
 * Establish a WebSocket connection for real-time collaborative editing of a document.
 */
export const wsEditsDocumentOptions = (options: Options<WsEditsDocumentData>) => queryOptions<unknown, WsEditsDocumentError, unknown, ReturnType<typeof wsEditsDocumentQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await wsEditsDocument({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: wsEditsDocumentQueryKey(options)
});

export const listNotesQueryKey = (options?: Options<ListNotesData>) => createQueryKey('listNotes', options);

/**
 * List notes
 *
 * Retrieve a paginated list of all notes with optional filtering and sorting
 */
export const listNotesOptions = (options?: Options<ListNotesData>) => queryOptions<ListNotesResponse, ListNotesError, ListNotesResponse, ReturnType<typeof listNotesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listNotes({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listNotesQueryKey(options)
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = { ...queryKey[0] };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const listNotesInfiniteQueryKey = (options?: Options<ListNotesData>): QueryKey<Options<ListNotesData>> => createQueryKey('listNotes', options, true);

/**
 * List notes
 *
 * Retrieve a paginated list of all notes with optional filtering and sorting
 */
export const listNotesInfiniteOptions = (options?: Options<ListNotesData>) => infiniteQueryOptions<ListNotesResponse, ListNotesError, InfiniteData<ListNotesResponse>, QueryKey<Options<ListNotesData>>, number | Pick<QueryKey<Options<ListNotesData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<ListNotesData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                page: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await listNotes({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listNotesInfiniteQueryKey(options)
});

/**
 * Create note
 *
 * Create a new note
 */
export const createNoteMutation = (options?: Partial<Options<CreateNoteData>>): UseMutationOptions<CreateNoteResponse, CreateNoteError, Options<CreateNoteData>> => {
    const mutationOptions: UseMutationOptions<CreateNoteResponse, CreateNoteError, Options<CreateNoteData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createNote({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete note
 *
 * Delete a note by its unique identifier
 */
export const deleteNoteMutation = (options?: Partial<Options<DeleteNoteData>>): UseMutationOptions<DeleteNoteResponse, DeleteNoteError, Options<DeleteNoteData>> => {
    const mutationOptions: UseMutationOptions<DeleteNoteResponse, DeleteNoteError, Options<DeleteNoteData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteNote({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getNoteQueryKey = (options: Options<GetNoteData>) => createQueryKey('getNote', options);

/**
 * Get note
 *
 * Retrieve a single note by its unique identifier
 */
export const getNoteOptions = (options: Options<GetNoteData>) => queryOptions<GetNoteResponse, GetNoteError, GetNoteResponse, ReturnType<typeof getNoteQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getNote({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getNoteQueryKey(options)
});

/**
 * Patch note
 *
 * Update specific fields of a note (only provided fields will be updated)
 */
export const patchNoteMutation = (options?: Partial<Options<PatchNoteData>>): UseMutationOptions<PatchNoteResponse, PatchNoteError, Options<PatchNoteData>> => {
    const mutationOptions: UseMutationOptions<PatchNoteResponse, PatchNoteError, Options<PatchNoteData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await patchNote({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Put note
 *
 * Replace an existing note with new data (all fields are required)
 */
export const updateNoteMutation = (options?: Partial<Options<UpdateNoteData>>): UseMutationOptions<UpdateNoteResponse, UpdateNoteError, Options<UpdateNoteData>> => {
    const mutationOptions: UseMutationOptions<UpdateNoteResponse, UpdateNoteError, Options<UpdateNoteData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await updateNote({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
