// Package share provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package share

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Document defines model for Document.
type Document struct {
	// Content BlockNote model
	Content DocumentContent    `json:"content"`
	Id      openapi_types.UUID `json:"id"`
}

// DocumentCommittedEvent defines model for DocumentCommittedEvent.
type DocumentCommittedEvent struct {
	// Content BlockNote model
	Content         DocumentContent      `json:"content"`
	Id              openapi_types.UUID   `json:"id"`
	OutgoingLinkIds []openapi_types.UUID `json:"outgoingLinkIds"`
	Tags            []string             `json:"tags"`
	UserId          string               `json:"userId"`
}

// DocumentContent BlockNote model
type DocumentContent = []map[string]interface{}

// NoteCreatedEvent defines model for NoteCreatedEvent.
type NoteCreatedEvent struct {
	Icon *string            `json:"icon,omitempty"`
	Id   openapi_types.UUID `json:"id"`
	Name string             `json:"name"`
}

// NoteDeletedEvent defines model for NoteDeletedEvent.
type NoteDeletedEvent struct {
	Id openapi_types.UUID `json:"id"`
}

// NoteSearch defines model for NoteSearch.
type NoteSearch struct {
	Id   openapi_types.UUID `json:"id"`
	Name string             `json:"name"`

	// PlainTextContent Plain text content
	PlainTextContent *string   `json:"plainTextContent,omitempty"`
	Tags             *[]string `json:"tags,omitempty"`
}

// NoteUpdatedEvent defines model for NoteUpdatedEvent.
type NoteUpdatedEvent struct {
	FolderId  openapi_types.UUID `json:"folderId"`
	Icon      *string            `json:"icon"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`
	Tags      []string           `json:"tags"`
	UpdatedAt time.Time          `json:"updatedAt"`
}

// UserDeletedEvent defines model for UserDeletedEvent.
type UserDeletedEvent struct {
	// Id User ID from Authentik (need to change subject mode to User's ID instead of hashed)
	Id Id `json:"id"`
}

// Id User ID from Authentik (need to change subject mode to User's ID instead of hashed)
type Id = string
