// Package note provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package note

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/nullable"
	"github.com/oapi-codegen/runtime"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	Oauth2Scopes = "oauth2.Scopes"
)

// Defines values for OrderQuery.
const (
	OrderQueryAsc  OrderQuery = "asc"
	OrderQueryDesc OrderQuery = "desc"
)

// Defines values for ListNotesParamsOrder.
const (
	ListNotesParamsOrderAsc  ListNotesParamsOrder = "asc"
	ListNotesParamsOrderDesc ListNotesParamsOrder = "desc"
)

// Defines values for ListNotesParamsSortBy.
const (
	CreatedAt ListNotesParamsSortBy = "createdAt"
	Title     ListNotesParamsSortBy = "title"
	UpdatedAt ListNotesParamsSortBy = "updatedAt"
)

// Error defines model for Error.
type Error struct {
	// Code Error code
	Code string `json:"code"`

	// Message Human-readable error message
	Message string `json:"message"`

	// MoreInfo URL with more information about the error
	MoreInfo *string `json:"more_info,omitempty"`
}

// Note defines model for Note.
type Note struct {
	// CreatedAt Timestamp when the note was created
	CreatedAt *time.Time          `json:"createdAt,omitempty"`
	Id        *openapi_types.UUID `json:"id,omitempty"`

	// Title Title of the note
	Title *string `json:"title,omitempty"`

	// UpdatedAt Timestamp when the note was last updated
	UpdatedAt nullable.Nullable[time.Time] `json:"updatedAt,omitempty"`
}

// NoteRequired defines model for NoteRequired.
type NoteRequired struct {
	// CreatedAt Timestamp when the note was created
	CreatedAt *time.Time          `json:"createdAt,omitempty"`
	Id        *openapi_types.UUID `json:"id,omitempty"`

	// Title Title of the note
	Title string `json:"title"`

	// UpdatedAt Timestamp when the note was last updated
	UpdatedAt nullable.Nullable[time.Time] `json:"updatedAt,omitempty"`
}

// Pagination defines model for Pagination.
type Pagination struct {
	// HasNext Whether there is a next page
	HasNext bool `json:"hasNext"`

	// HasPrev Whether there is a previous page
	HasPrev bool `json:"hasPrev"`

	// Limit Number of items per page
	Limit int `json:"limit"`

	// Page Current page number
	Page int `json:"page"`

	// Total Total number of items
	Total int `json:"total"`

	// TotalPages Total number of pages
	TotalPages int `json:"totalPages"`
}

// LimitQuery defines model for limitQuery.
type LimitQuery = int

// NoteIdPath defines model for noteIdPath.
type NoteIdPath = openapi_types.UUID

// OrderQuery defines model for orderQuery.
type OrderQuery string

// PageQuery defines model for pageQuery.
type PageQuery = int

// BadRequestError defines model for BadRequestError.
type BadRequestError = Error

// CreateNoteResponse defines model for CreateNoteResponse.
type CreateNoteResponse struct {
	// CreatedAt Timestamp when the note was created
	CreatedAt *time.Time          `json:"createdAt,omitempty"`
	Id        *openapi_types.UUID `json:"id,omitempty"`

	// Title Title of the note
	Title *string `json:"title,omitempty"`

	// UpdatedAt Timestamp when the note was last updated
	UpdatedAt nullable.Nullable[time.Time] `json:"updatedAt,omitempty"`
}

// ForbiddenError defines model for ForbiddenError.
type ForbiddenError = Error

// GetNoteResponse defines model for GetNoteResponse.
type GetNoteResponse struct {
	// CreatedAt Timestamp when the note was created
	CreatedAt *time.Time          `json:"createdAt,omitempty"`
	Id        *openapi_types.UUID `json:"id,omitempty"`

	// Title Title of the note
	Title string `json:"title"`

	// UpdatedAt Timestamp when the note was last updated
	UpdatedAt nullable.Nullable[time.Time] `json:"updatedAt,omitempty"`
}

// InternalServerError defines model for InternalServerError.
type InternalServerError = Error

// ListNotesResponse defines model for ListNotesResponse.
type ListNotesResponse struct {
	Data       []Note `json:"data"`
	Pagination struct {
		// HasNext Whether there is a next page
		HasNext bool `json:"hasNext"`

		// HasPrev Whether there is a previous page
		HasPrev bool `json:"hasPrev"`

		// Limit Number of items per page
		Limit int `json:"limit"`

		// Page Current page number
		Page int `json:"page"`

		// Total Total number of items
		Total int `json:"total"`

		// TotalPages Total number of pages
		TotalPages int `json:"totalPages"`
	} `json:"pagination"`
}

// NotFoundError defines model for NotFoundError.
type NotFoundError = Error

// PatchNoteResponse defines model for PatchNoteResponse.
type PatchNoteResponse struct {
	// CreatedAt Timestamp when the note was created
	CreatedAt *time.Time          `json:"createdAt,omitempty"`
	Id        *openapi_types.UUID `json:"id,omitempty"`

	// Title Title of the note
	Title *string `json:"title,omitempty"`

	// UpdatedAt Timestamp when the note was last updated
	UpdatedAt nullable.Nullable[time.Time] `json:"updatedAt,omitempty"`
}

// PutNoteResponse defines model for PutNoteResponse.
type PutNoteResponse struct {
	// CreatedAt Timestamp when the note was created
	CreatedAt *time.Time          `json:"createdAt,omitempty"`
	Id        *openapi_types.UUID `json:"id,omitempty"`

	// Title Title of the note
	Title string `json:"title"`

	// UpdatedAt Timestamp when the note was last updated
	UpdatedAt nullable.Nullable[time.Time] `json:"updatedAt,omitempty"`
}

// UnauthorizedError defines model for UnauthorizedError.
type UnauthorizedError = Error

// CreateNoteRequest defines model for CreateNoteRequest.
type CreateNoteRequest struct {
	// CreatedAt Timestamp when the note was created
	CreatedAt *time.Time          `json:"createdAt,omitempty"`
	Id        *openapi_types.UUID `json:"id,omitempty"`

	// Title Title of the note
	Title string `json:"title"`

	// UpdatedAt Timestamp when the note was last updated
	UpdatedAt nullable.Nullable[time.Time] `json:"updatedAt,omitempty"`
}

// PatchNoteRequest defines model for PatchNoteRequest.
type PatchNoteRequest struct {
	// CreatedAt Timestamp when the note was created
	CreatedAt *time.Time          `json:"createdAt,omitempty"`
	Id        *openapi_types.UUID `json:"id,omitempty"`

	// Title Title of the note
	Title *string `json:"title,omitempty"`

	// UpdatedAt Timestamp when the note was last updated
	UpdatedAt nullable.Nullable[time.Time] `json:"updatedAt,omitempty"`
}

// PutNoteRequest defines model for PutNoteRequest.
type PutNoteRequest struct {
	// CreatedAt Timestamp when the note was created
	CreatedAt *time.Time          `json:"createdAt,omitempty"`
	Id        *openapi_types.UUID `json:"id,omitempty"`

	// Title Title of the note
	Title string `json:"title"`

	// UpdatedAt Timestamp when the note was last updated
	UpdatedAt nullable.Nullable[time.Time] `json:"updatedAt,omitempty"`
}

// ListNotesParams defines parameters for ListNotes.
type ListNotesParams struct {
	// Page Page number for pagination
	Page *PageQuery `form:"page,omitempty" json:"page,omitempty"`

	// Limit Number of items per page
	Limit *LimitQuery `form:"limit,omitempty" json:"limit,omitempty"`

	// Order Sort order
	Order *ListNotesParamsOrder `form:"order,omitempty" json:"order,omitempty"`

	// SortBy Field to sort by
	SortBy *ListNotesParamsSortBy `form:"sortBy,omitempty" json:"sortBy,omitempty"`

	// Search Search notes by title or content
	Search *string `form:"search,omitempty" json:"search,omitempty"`
}

// ListNotesParamsOrder defines parameters for ListNotes.
type ListNotesParamsOrder string

// ListNotesParamsSortBy defines parameters for ListNotes.
type ListNotesParamsSortBy string

// CreateNoteJSONBody defines parameters for CreateNote.
type CreateNoteJSONBody struct {
	// CreatedAt Timestamp when the note was created
	CreatedAt *time.Time          `json:"createdAt,omitempty"`
	Id        *openapi_types.UUID `json:"id,omitempty"`

	// Title Title of the note
	Title string `json:"title"`

	// UpdatedAt Timestamp when the note was last updated
	UpdatedAt nullable.Nullable[time.Time] `json:"updatedAt,omitempty"`
}

// PatchNoteJSONBody defines parameters for PatchNote.
type PatchNoteJSONBody struct {
	// CreatedAt Timestamp when the note was created
	CreatedAt *time.Time          `json:"createdAt,omitempty"`
	Id        *openapi_types.UUID `json:"id,omitempty"`

	// Title Title of the note
	Title *string `json:"title,omitempty"`

	// UpdatedAt Timestamp when the note was last updated
	UpdatedAt nullable.Nullable[time.Time] `json:"updatedAt,omitempty"`
}

// UpdateNoteJSONBody defines parameters for UpdateNote.
type UpdateNoteJSONBody struct {
	// CreatedAt Timestamp when the note was created
	CreatedAt *time.Time          `json:"createdAt,omitempty"`
	Id        *openapi_types.UUID `json:"id,omitempty"`

	// Title Title of the note
	Title string `json:"title"`

	// UpdatedAt Timestamp when the note was last updated
	UpdatedAt nullable.Nullable[time.Time] `json:"updatedAt,omitempty"`
}

// CreateNoteJSONRequestBody defines body for CreateNote for application/json ContentType.
type CreateNoteJSONRequestBody CreateNoteJSONBody

// PatchNoteJSONRequestBody defines body for PatchNote for application/json ContentType.
type PatchNoteJSONRequestBody PatchNoteJSONBody

// UpdateNoteJSONRequestBody defines body for UpdateNote for application/json ContentType.
type UpdateNoteJSONRequestBody UpdateNoteJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List notes
	// (GET /note/notes)
	ListNotes(c *gin.Context, params ListNotesParams)
	// Create note
	// (POST /note/notes)
	CreateNote(c *gin.Context)
	// Delete note
	// (DELETE /note/notes/{noteId})
	DeleteNote(c *gin.Context, noteId NoteIdPath)
	// Get note
	// (GET /note/notes/{noteId})
	GetNote(c *gin.Context, noteId NoteIdPath)
	// Patch note
	// (PATCH /note/notes/{noteId})
	PatchNote(c *gin.Context, noteId NoteIdPath)
	// Put note
	// (PUT /note/notes/{noteId})
	UpdateNote(c *gin.Context, noteId NoteIdPath)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ListNotes operation middleware
func (siw *ServerInterfaceWrapper) ListNotes(c *gin.Context) {

	var err error

	c.Set(Oauth2Scopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListNotesParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", c.Request.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "order" -------------

	err = runtime.BindQueryParameter("form", true, false, "order", c.Request.URL.Query(), &params.Order)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter order: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "sortBy" -------------

	err = runtime.BindQueryParameter("form", true, false, "sortBy", c.Request.URL.Query(), &params.SortBy)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sortBy: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameter("form", true, false, "search", c.Request.URL.Query(), &params.Search)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter search: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListNotes(c, params)
}

// CreateNote operation middleware
func (siw *ServerInterfaceWrapper) CreateNote(c *gin.Context) {

	c.Set(Oauth2Scopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateNote(c)
}

// DeleteNote operation middleware
func (siw *ServerInterfaceWrapper) DeleteNote(c *gin.Context) {

	var err error

	// ------------- Path parameter "noteId" -------------
	var noteId NoteIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "noteId", c.Param("noteId"), &noteId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter noteId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(Oauth2Scopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteNote(c, noteId)
}

// GetNote operation middleware
func (siw *ServerInterfaceWrapper) GetNote(c *gin.Context) {

	var err error

	// ------------- Path parameter "noteId" -------------
	var noteId NoteIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "noteId", c.Param("noteId"), &noteId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter noteId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(Oauth2Scopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetNote(c, noteId)
}

// PatchNote operation middleware
func (siw *ServerInterfaceWrapper) PatchNote(c *gin.Context) {

	var err error

	// ------------- Path parameter "noteId" -------------
	var noteId NoteIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "noteId", c.Param("noteId"), &noteId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter noteId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(Oauth2Scopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PatchNote(c, noteId)
}

// UpdateNote operation middleware
func (siw *ServerInterfaceWrapper) UpdateNote(c *gin.Context) {

	var err error

	// ------------- Path parameter "noteId" -------------
	var noteId NoteIdPath

	err = runtime.BindStyledParameterWithOptions("simple", "noteId", c.Param("noteId"), &noteId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter noteId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(Oauth2Scopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateNote(c, noteId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/note/notes", wrapper.ListNotes)
	router.POST(options.BaseURL+"/note/notes", wrapper.CreateNote)
	router.DELETE(options.BaseURL+"/note/notes/:noteId", wrapper.DeleteNote)
	router.GET(options.BaseURL+"/note/notes/:noteId", wrapper.GetNote)
	router.PATCH(options.BaseURL+"/note/notes/:noteId", wrapper.PatchNote)
	router.PUT(options.BaseURL+"/note/notes/:noteId", wrapper.UpdateNote)
}

type BadRequestErrorJSONResponse Error

type CreateNoteResponseJSONResponse struct {
	// CreatedAt Timestamp when the note was created
	CreatedAt *time.Time          `json:"createdAt,omitempty"`
	Id        *openapi_types.UUID `json:"id,omitempty"`

	// Title Title of the note
	Title *string `json:"title,omitempty"`

	// UpdatedAt Timestamp when the note was last updated
	UpdatedAt nullable.Nullable[time.Time] `json:"updatedAt,omitempty"`
}

type ForbiddenErrorJSONResponse Error

type GetNoteResponseJSONResponse struct {
	// CreatedAt Timestamp when the note was created
	CreatedAt *time.Time          `json:"createdAt,omitempty"`
	Id        *openapi_types.UUID `json:"id,omitempty"`

	// Title Title of the note
	Title string `json:"title"`

	// UpdatedAt Timestamp when the note was last updated
	UpdatedAt nullable.Nullable[time.Time] `json:"updatedAt,omitempty"`
}

type InternalServerErrorJSONResponse Error

type ListNotesResponseJSONResponse struct {
	Data       []Note `json:"data"`
	Pagination struct {
		// HasNext Whether there is a next page
		HasNext bool `json:"hasNext"`

		// HasPrev Whether there is a previous page
		HasPrev bool `json:"hasPrev"`

		// Limit Number of items per page
		Limit int `json:"limit"`

		// Page Current page number
		Page int `json:"page"`

		// Total Total number of items
		Total int `json:"total"`

		// TotalPages Total number of pages
		TotalPages int `json:"totalPages"`
	} `json:"pagination"`
}

type NotFoundErrorJSONResponse Error

type PatchNoteResponseJSONResponse struct {
	// CreatedAt Timestamp when the note was created
	CreatedAt *time.Time          `json:"createdAt,omitempty"`
	Id        *openapi_types.UUID `json:"id,omitempty"`

	// Title Title of the note
	Title *string `json:"title,omitempty"`

	// UpdatedAt Timestamp when the note was last updated
	UpdatedAt nullable.Nullable[time.Time] `json:"updatedAt,omitempty"`
}

type PutNoteResponseJSONResponse struct {
	// CreatedAt Timestamp when the note was created
	CreatedAt *time.Time          `json:"createdAt,omitempty"`
	Id        *openapi_types.UUID `json:"id,omitempty"`

	// Title Title of the note
	Title string `json:"title"`

	// UpdatedAt Timestamp when the note was last updated
	UpdatedAt nullable.Nullable[time.Time] `json:"updatedAt,omitempty"`
}

type UnauthorizedErrorJSONResponse Error

type ListNotesRequestObject struct {
	Params ListNotesParams
}

type ListNotesResponseObject interface {
	VisitListNotesResponse(w http.ResponseWriter) error
}

type ListNotes200JSONResponse struct{ ListNotesResponseJSONResponse }

func (response ListNotes200JSONResponse) VisitListNotesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListNotes400JSONResponse struct{ BadRequestErrorJSONResponse }

func (response ListNotes400JSONResponse) VisitListNotesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ListNotes401JSONResponse struct{ UnauthorizedErrorJSONResponse }

func (response ListNotes401JSONResponse) VisitListNotesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ListNotes500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response ListNotes500JSONResponse) VisitListNotesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateNoteRequestObject struct {
	Body *CreateNoteJSONRequestBody
}

type CreateNoteResponseObject interface {
	VisitCreateNoteResponse(w http.ResponseWriter) error
}

type CreateNote201JSONResponse struct{ CreateNoteResponseJSONResponse }

func (response CreateNote201JSONResponse) VisitCreateNoteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateNote400JSONResponse struct{ BadRequestErrorJSONResponse }

func (response CreateNote400JSONResponse) VisitCreateNoteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateNote401JSONResponse struct{ UnauthorizedErrorJSONResponse }

func (response CreateNote401JSONResponse) VisitCreateNoteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateNote500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response CreateNote500JSONResponse) VisitCreateNoteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteNoteRequestObject struct {
	NoteId NoteIdPath `json:"noteId"`
}

type DeleteNoteResponseObject interface {
	VisitDeleteNoteResponse(w http.ResponseWriter) error
}

type DeleteNote204Response struct {
}

func (response DeleteNote204Response) VisitDeleteNoteResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteNote400JSONResponse struct{ BadRequestErrorJSONResponse }

func (response DeleteNote400JSONResponse) VisitDeleteNoteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type DeleteNote401JSONResponse struct{ UnauthorizedErrorJSONResponse }

func (response DeleteNote401JSONResponse) VisitDeleteNoteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteNote403JSONResponse struct{ ForbiddenErrorJSONResponse }

func (response DeleteNote403JSONResponse) VisitDeleteNoteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type DeleteNote404JSONResponse struct{ NotFoundErrorJSONResponse }

func (response DeleteNote404JSONResponse) VisitDeleteNoteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteNote500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response DeleteNote500JSONResponse) VisitDeleteNoteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetNoteRequestObject struct {
	NoteId NoteIdPath `json:"noteId"`
}

type GetNoteResponseObject interface {
	VisitGetNoteResponse(w http.ResponseWriter) error
}

type GetNote200JSONResponse struct{ GetNoteResponseJSONResponse }

func (response GetNote200JSONResponse) VisitGetNoteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetNote400JSONResponse struct{ BadRequestErrorJSONResponse }

func (response GetNote400JSONResponse) VisitGetNoteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetNote401JSONResponse struct{ UnauthorizedErrorJSONResponse }

func (response GetNote401JSONResponse) VisitGetNoteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetNote403JSONResponse struct{ ForbiddenErrorJSONResponse }

func (response GetNote403JSONResponse) VisitGetNoteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetNote404JSONResponse struct{ NotFoundErrorJSONResponse }

func (response GetNote404JSONResponse) VisitGetNoteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetNote500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response GetNote500JSONResponse) VisitGetNoteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PatchNoteRequestObject struct {
	NoteId NoteIdPath `json:"noteId"`
	Body   *PatchNoteJSONRequestBody
}

type PatchNoteResponseObject interface {
	VisitPatchNoteResponse(w http.ResponseWriter) error
}

type PatchNote200JSONResponse struct{ PatchNoteResponseJSONResponse }

func (response PatchNote200JSONResponse) VisitPatchNoteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PatchNote400JSONResponse struct{ BadRequestErrorJSONResponse }

func (response PatchNote400JSONResponse) VisitPatchNoteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PatchNote401JSONResponse struct{ UnauthorizedErrorJSONResponse }

func (response PatchNote401JSONResponse) VisitPatchNoteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PatchNote403JSONResponse struct{ ForbiddenErrorJSONResponse }

func (response PatchNote403JSONResponse) VisitPatchNoteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type PatchNote404JSONResponse struct{ NotFoundErrorJSONResponse }

func (response PatchNote404JSONResponse) VisitPatchNoteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PatchNote500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response PatchNote500JSONResponse) VisitPatchNoteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UpdateNoteRequestObject struct {
	NoteId NoteIdPath `json:"noteId"`
	Body   *UpdateNoteJSONRequestBody
}

type UpdateNoteResponseObject interface {
	VisitUpdateNoteResponse(w http.ResponseWriter) error
}

type UpdateNote200JSONResponse struct{ PutNoteResponseJSONResponse }

func (response UpdateNote200JSONResponse) VisitUpdateNoteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateNote400JSONResponse struct{ BadRequestErrorJSONResponse }

func (response UpdateNote400JSONResponse) VisitUpdateNoteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateNote401JSONResponse struct{ UnauthorizedErrorJSONResponse }

func (response UpdateNote401JSONResponse) VisitUpdateNoteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type UpdateNote403JSONResponse struct{ ForbiddenErrorJSONResponse }

func (response UpdateNote403JSONResponse) VisitUpdateNoteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type UpdateNote404JSONResponse struct{ NotFoundErrorJSONResponse }

func (response UpdateNote404JSONResponse) VisitUpdateNoteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateNote500JSONResponse struct {
	InternalServerErrorJSONResponse
}

func (response UpdateNote500JSONResponse) VisitUpdateNoteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List notes
	// (GET /note/notes)
	ListNotes(ctx context.Context, request ListNotesRequestObject) (ListNotesResponseObject, error)
	// Create note
	// (POST /note/notes)
	CreateNote(ctx context.Context, request CreateNoteRequestObject) (CreateNoteResponseObject, error)
	// Delete note
	// (DELETE /note/notes/{noteId})
	DeleteNote(ctx context.Context, request DeleteNoteRequestObject) (DeleteNoteResponseObject, error)
	// Get note
	// (GET /note/notes/{noteId})
	GetNote(ctx context.Context, request GetNoteRequestObject) (GetNoteResponseObject, error)
	// Patch note
	// (PATCH /note/notes/{noteId})
	PatchNote(ctx context.Context, request PatchNoteRequestObject) (PatchNoteResponseObject, error)
	// Put note
	// (PUT /note/notes/{noteId})
	UpdateNote(ctx context.Context, request UpdateNoteRequestObject) (UpdateNoteResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// ListNotes operation middleware
func (sh *strictHandler) ListNotes(ctx *gin.Context, params ListNotesParams) {
	var request ListNotesRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListNotes(ctx, request.(ListNotesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListNotes")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(ListNotesResponseObject); ok {
		if err := validResponse.VisitListNotesResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateNote operation middleware
func (sh *strictHandler) CreateNote(ctx *gin.Context) {
	var request CreateNoteRequestObject

	var body CreateNoteJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateNote(ctx, request.(CreateNoteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateNote")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(CreateNoteResponseObject); ok {
		if err := validResponse.VisitCreateNoteResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteNote operation middleware
func (sh *strictHandler) DeleteNote(ctx *gin.Context, noteId NoteIdPath) {
	var request DeleteNoteRequestObject

	request.NoteId = noteId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteNote(ctx, request.(DeleteNoteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteNote")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(DeleteNoteResponseObject); ok {
		if err := validResponse.VisitDeleteNoteResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetNote operation middleware
func (sh *strictHandler) GetNote(ctx *gin.Context, noteId NoteIdPath) {
	var request GetNoteRequestObject

	request.NoteId = noteId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetNote(ctx, request.(GetNoteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetNote")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetNoteResponseObject); ok {
		if err := validResponse.VisitGetNoteResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// PatchNote operation middleware
func (sh *strictHandler) PatchNote(ctx *gin.Context, noteId NoteIdPath) {
	var request PatchNoteRequestObject

	request.NoteId = noteId

	var body PatchNoteJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.PatchNote(ctx, request.(PatchNoteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PatchNote")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(PatchNoteResponseObject); ok {
		if err := validResponse.VisitPatchNoteResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateNote operation middleware
func (sh *strictHandler) UpdateNote(ctx *gin.Context, noteId NoteIdPath) {
	var request UpdateNoteRequestObject

	request.NoteId = noteId

	var body UpdateNoteJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateNote(ctx, request.(UpdateNoteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateNote")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(UpdateNoteResponseObject); ok {
		if err := validResponse.VisitUpdateNoteResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}
