# yaml-language-server: $schema=https://www.schemastore.org/loki.json
auth_enabled: false

analytics:
  reporting_enabled: false

server:
  http_listen_port: 3100

common:
  replication_factor: 1
  path_prefix: /tmp/loki
  storage:
    filesystem:
      chunks_directory: /tmp/loki/chunks
      rules_directory: /tmp/loki/rules
  ring:
    kvstore:
      store: inmemory

ingester:
  chunk_idle_period: 3m
  max_chunk_age: 1h

limits_config:
  ingestion_rate_mb: 16
  ingestion_burst_size_mb: 24

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h
