// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               unknown
// source: authorization.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { handleUnaryCall, Metadata, UntypedServiceImplementation } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "authorization";

export enum WorkspaceRole {
  WORKSPACE_ROLE_UNSPECIFIED = 0,
  WORKSPACE_ROLE_OWNER = 1,
  WORKSPACE_ROLE_EDITOR = 2,
  WORKSPACE_ROLE_VIEWER = 3,
  UNRECOGNIZED = -1,
}

export enum WorkspacePermission {
  WORKSPACE_PERMISSION_UNSPECIFIED = 0,
  WORKSPACE_PERMISSION_READ = 1,
  WORKSPACE_PERMISSION_EDIT = 2,
  WORKSPACE_PERMISSION_DELETE = 3,
  UNRECOGNIZED = -1,
}

export enum WorkspaceItemPermission {
  WORKSPACE_ITEM_PERMISSION_UNSPECIFIED = 0,
  WORKSPACE_ITEM_PERMISSION_READ = 1,
  WORKSPACE_ITEM_PERMISSION_WRITE = 2,
  WORKSPACE_ITEM_PERMISSION_DELETE = 3,
  UNRECOGNIZED = -1,
}

export interface UserWorkspace {
  id: string;
  role: WorkspaceRole;
}

export interface GetUserWorkspacesRequest {
  userId: string;
}

export interface GetUserWorkspacesResponse {
  workspaces: UserWorkspace[];
}

export interface CreateWorkspaceWithOwnerRequest {
  ownerId: string;
  workspaceId: string;
}

export interface CreateWorkspaceWithOwnerResponse {
}

export interface WorkspaceMember {
  id: string;
  role: WorkspaceRole;
}

export interface UpdateWorkspaceMembersRequest {
  userId: string;
  workspaceId: string;
  members: WorkspaceMember[];
}

export interface UpdateWorkspaceMembersResponse {
}

export interface LeaveWorkspaceRequest {
  userId: string;
  workspaceId: string;
}

export interface LeaveWorkspaceResponse {
}

export interface GetWorkspaceMembersRequest {
  userId: string;
  workspaceId: string;
}

export interface GetWorkspaceMembersResponse {
  members: WorkspaceMember[];
}

export interface HasWorkspacePermissionRequest {
  memberId: string;
  workspaceId: string;
  permission: WorkspacePermission;
}

export interface HasWorkspacePermissionResponse {
  hasPermission: boolean;
}

export interface HasWorkspaceItemPermissionRequest {
  memberId: string;
  workspaceId: string;
  permission: WorkspaceItemPermission;
}

export interface HasWorkspaceItemPermissionResponse {
  hasPermission: boolean;
}

export interface GetUserWorkspaceItemPermissionsRequest {
  memberId: string;
  workspaceId: string;
}

export interface GetUserWorkspaceItemPermissionsResponse {
  canRead: boolean;
  canWrite: boolean;
  canDelete: boolean;
}

export interface DeleteWorkspaceRequest {
  userId: string;
  workspaceId: string;
}

export interface DeleteWorkspaceResponse {
}

export const AUTHORIZATION_PACKAGE_NAME = "authorization";

function createBaseUserWorkspace(): UserWorkspace {
  return { id: "", role: 0 };
}

export const UserWorkspace: MessageFns<UserWorkspace> = {
  encode(message: UserWorkspace, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.role !== 0) {
      writer.uint32(16).int32(message.role);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UserWorkspace {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUserWorkspace();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.role = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetUserWorkspacesRequest(): GetUserWorkspacesRequest {
  return { userId: "" };
}

export const GetUserWorkspacesRequest: MessageFns<GetUserWorkspacesRequest> = {
  encode(message: GetUserWorkspacesRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetUserWorkspacesRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetUserWorkspacesRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetUserWorkspacesResponse(): GetUserWorkspacesResponse {
  return { workspaces: [] };
}

export const GetUserWorkspacesResponse: MessageFns<GetUserWorkspacesResponse> = {
  encode(message: GetUserWorkspacesResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.workspaces) {
      UserWorkspace.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetUserWorkspacesResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetUserWorkspacesResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.workspaces.push(UserWorkspace.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCreateWorkspaceWithOwnerRequest(): CreateWorkspaceWithOwnerRequest {
  return { ownerId: "", workspaceId: "" };
}

export const CreateWorkspaceWithOwnerRequest: MessageFns<CreateWorkspaceWithOwnerRequest> = {
  encode(message: CreateWorkspaceWithOwnerRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.ownerId !== "") {
      writer.uint32(10).string(message.ownerId);
    }
    if (message.workspaceId !== "") {
      writer.uint32(18).string(message.workspaceId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateWorkspaceWithOwnerRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateWorkspaceWithOwnerRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.ownerId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.workspaceId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseCreateWorkspaceWithOwnerResponse(): CreateWorkspaceWithOwnerResponse {
  return {};
}

export const CreateWorkspaceWithOwnerResponse: MessageFns<CreateWorkspaceWithOwnerResponse> = {
  encode(_: CreateWorkspaceWithOwnerResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateWorkspaceWithOwnerResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateWorkspaceWithOwnerResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseWorkspaceMember(): WorkspaceMember {
  return { id: "", role: 0 };
}

export const WorkspaceMember: MessageFns<WorkspaceMember> = {
  encode(message: WorkspaceMember, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.role !== 0) {
      writer.uint32(16).int32(message.role);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WorkspaceMember {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWorkspaceMember();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.role = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseUpdateWorkspaceMembersRequest(): UpdateWorkspaceMembersRequest {
  return { userId: "", workspaceId: "", members: [] };
}

export const UpdateWorkspaceMembersRequest: MessageFns<UpdateWorkspaceMembersRequest> = {
  encode(message: UpdateWorkspaceMembersRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.workspaceId !== "") {
      writer.uint32(18).string(message.workspaceId);
    }
    for (const v of message.members) {
      WorkspaceMember.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateWorkspaceMembersRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateWorkspaceMembersRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.workspaceId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.members.push(WorkspaceMember.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseUpdateWorkspaceMembersResponse(): UpdateWorkspaceMembersResponse {
  return {};
}

export const UpdateWorkspaceMembersResponse: MessageFns<UpdateWorkspaceMembersResponse> = {
  encode(_: UpdateWorkspaceMembersResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateWorkspaceMembersResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateWorkspaceMembersResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseLeaveWorkspaceRequest(): LeaveWorkspaceRequest {
  return { userId: "", workspaceId: "" };
}

export const LeaveWorkspaceRequest: MessageFns<LeaveWorkspaceRequest> = {
  encode(message: LeaveWorkspaceRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.workspaceId !== "") {
      writer.uint32(18).string(message.workspaceId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LeaveWorkspaceRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLeaveWorkspaceRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.workspaceId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseLeaveWorkspaceResponse(): LeaveWorkspaceResponse {
  return {};
}

export const LeaveWorkspaceResponse: MessageFns<LeaveWorkspaceResponse> = {
  encode(_: LeaveWorkspaceResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LeaveWorkspaceResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLeaveWorkspaceResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetWorkspaceMembersRequest(): GetWorkspaceMembersRequest {
  return { userId: "", workspaceId: "" };
}

export const GetWorkspaceMembersRequest: MessageFns<GetWorkspaceMembersRequest> = {
  encode(message: GetWorkspaceMembersRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.workspaceId !== "") {
      writer.uint32(18).string(message.workspaceId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetWorkspaceMembersRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetWorkspaceMembersRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.workspaceId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetWorkspaceMembersResponse(): GetWorkspaceMembersResponse {
  return { members: [] };
}

export const GetWorkspaceMembersResponse: MessageFns<GetWorkspaceMembersResponse> = {
  encode(message: GetWorkspaceMembersResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.members) {
      WorkspaceMember.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetWorkspaceMembersResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetWorkspaceMembersResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.members.push(WorkspaceMember.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseHasWorkspacePermissionRequest(): HasWorkspacePermissionRequest {
  return { memberId: "", workspaceId: "", permission: 0 };
}

export const HasWorkspacePermissionRequest: MessageFns<HasWorkspacePermissionRequest> = {
  encode(message: HasWorkspacePermissionRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.memberId !== "") {
      writer.uint32(10).string(message.memberId);
    }
    if (message.workspaceId !== "") {
      writer.uint32(18).string(message.workspaceId);
    }
    if (message.permission !== 0) {
      writer.uint32(24).int32(message.permission);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HasWorkspacePermissionRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHasWorkspacePermissionRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.memberId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.workspaceId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.permission = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseHasWorkspacePermissionResponse(): HasWorkspacePermissionResponse {
  return { hasPermission: false };
}

export const HasWorkspacePermissionResponse: MessageFns<HasWorkspacePermissionResponse> = {
  encode(message: HasWorkspacePermissionResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.hasPermission !== false) {
      writer.uint32(8).bool(message.hasPermission);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HasWorkspacePermissionResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHasWorkspacePermissionResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.hasPermission = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseHasWorkspaceItemPermissionRequest(): HasWorkspaceItemPermissionRequest {
  return { memberId: "", workspaceId: "", permission: 0 };
}

export const HasWorkspaceItemPermissionRequest: MessageFns<HasWorkspaceItemPermissionRequest> = {
  encode(message: HasWorkspaceItemPermissionRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.memberId !== "") {
      writer.uint32(10).string(message.memberId);
    }
    if (message.workspaceId !== "") {
      writer.uint32(18).string(message.workspaceId);
    }
    if (message.permission !== 0) {
      writer.uint32(24).int32(message.permission);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HasWorkspaceItemPermissionRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHasWorkspaceItemPermissionRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.memberId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.workspaceId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.permission = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseHasWorkspaceItemPermissionResponse(): HasWorkspaceItemPermissionResponse {
  return { hasPermission: false };
}

export const HasWorkspaceItemPermissionResponse: MessageFns<HasWorkspaceItemPermissionResponse> = {
  encode(message: HasWorkspaceItemPermissionResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.hasPermission !== false) {
      writer.uint32(8).bool(message.hasPermission);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HasWorkspaceItemPermissionResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHasWorkspaceItemPermissionResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.hasPermission = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetUserWorkspaceItemPermissionsRequest(): GetUserWorkspaceItemPermissionsRequest {
  return { memberId: "", workspaceId: "" };
}

export const GetUserWorkspaceItemPermissionsRequest: MessageFns<GetUserWorkspaceItemPermissionsRequest> = {
  encode(message: GetUserWorkspaceItemPermissionsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.memberId !== "") {
      writer.uint32(10).string(message.memberId);
    }
    if (message.workspaceId !== "") {
      writer.uint32(18).string(message.workspaceId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetUserWorkspaceItemPermissionsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetUserWorkspaceItemPermissionsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.memberId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.workspaceId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetUserWorkspaceItemPermissionsResponse(): GetUserWorkspaceItemPermissionsResponse {
  return { canRead: false, canWrite: false, canDelete: false };
}

export const GetUserWorkspaceItemPermissionsResponse: MessageFns<GetUserWorkspaceItemPermissionsResponse> = {
  encode(message: GetUserWorkspaceItemPermissionsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.canRead !== false) {
      writer.uint32(8).bool(message.canRead);
    }
    if (message.canWrite !== false) {
      writer.uint32(16).bool(message.canWrite);
    }
    if (message.canDelete !== false) {
      writer.uint32(24).bool(message.canDelete);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetUserWorkspaceItemPermissionsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetUserWorkspaceItemPermissionsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.canRead = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.canWrite = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.canDelete = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseDeleteWorkspaceRequest(): DeleteWorkspaceRequest {
  return { userId: "", workspaceId: "" };
}

export const DeleteWorkspaceRequest: MessageFns<DeleteWorkspaceRequest> = {
  encode(message: DeleteWorkspaceRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.workspaceId !== "") {
      writer.uint32(18).string(message.workspaceId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteWorkspaceRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteWorkspaceRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.workspaceId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseDeleteWorkspaceResponse(): DeleteWorkspaceResponse {
  return {};
}

export const DeleteWorkspaceResponse: MessageFns<DeleteWorkspaceResponse> = {
  encode(_: DeleteWorkspaceResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteWorkspaceResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteWorkspaceResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

export interface AuthorizationServiceClient {
  getUserWorkspaces(request: GetUserWorkspacesRequest, metadata?: Metadata): Observable<GetUserWorkspacesResponse>;

  createWorkspaceWithOwner(
    request: CreateWorkspaceWithOwnerRequest,
    metadata?: Metadata,
  ): Observable<CreateWorkspaceWithOwnerResponse>;

  updateWorkspaceMembers(
    request: UpdateWorkspaceMembersRequest,
    metadata?: Metadata,
  ): Observable<UpdateWorkspaceMembersResponse>;

  getWorkspaceMembers(
    request: GetWorkspaceMembersRequest,
    metadata?: Metadata,
  ): Observable<GetWorkspaceMembersResponse>;

  leaveWorkspace(request: LeaveWorkspaceRequest, metadata?: Metadata): Observable<LeaveWorkspaceResponse>;

  hasWorkspacePermission(
    request: HasWorkspacePermissionRequest,
    metadata?: Metadata,
  ): Observable<HasWorkspacePermissionResponse>;

  hasWorkspaceItemPermission(
    request: HasWorkspaceItemPermissionRequest,
    metadata?: Metadata,
  ): Observable<HasWorkspaceItemPermissionResponse>;

  getUserWorkspaceItemPermissions(
    request: GetUserWorkspaceItemPermissionsRequest,
    metadata?: Metadata,
  ): Observable<GetUserWorkspaceItemPermissionsResponse>;

  deleteWorkspace(request: DeleteWorkspaceRequest, metadata?: Metadata): Observable<DeleteWorkspaceResponse>;
}

export interface AuthorizationServiceController {
  getUserWorkspaces(
    request: GetUserWorkspacesRequest,
    metadata?: Metadata,
  ): Promise<GetUserWorkspacesResponse> | Observable<GetUserWorkspacesResponse> | GetUserWorkspacesResponse;

  createWorkspaceWithOwner(
    request: CreateWorkspaceWithOwnerRequest,
    metadata?: Metadata,
  ):
    | Promise<CreateWorkspaceWithOwnerResponse>
    | Observable<CreateWorkspaceWithOwnerResponse>
    | CreateWorkspaceWithOwnerResponse;

  updateWorkspaceMembers(
    request: UpdateWorkspaceMembersRequest,
    metadata?: Metadata,
  ):
    | Promise<UpdateWorkspaceMembersResponse>
    | Observable<UpdateWorkspaceMembersResponse>
    | UpdateWorkspaceMembersResponse;

  getWorkspaceMembers(
    request: GetWorkspaceMembersRequest,
    metadata?: Metadata,
  ): Promise<GetWorkspaceMembersResponse> | Observable<GetWorkspaceMembersResponse> | GetWorkspaceMembersResponse;

  leaveWorkspace(
    request: LeaveWorkspaceRequest,
    metadata?: Metadata,
  ): Promise<LeaveWorkspaceResponse> | Observable<LeaveWorkspaceResponse> | LeaveWorkspaceResponse;

  hasWorkspacePermission(
    request: HasWorkspacePermissionRequest,
    metadata?: Metadata,
  ):
    | Promise<HasWorkspacePermissionResponse>
    | Observable<HasWorkspacePermissionResponse>
    | HasWorkspacePermissionResponse;

  hasWorkspaceItemPermission(
    request: HasWorkspaceItemPermissionRequest,
    metadata?: Metadata,
  ):
    | Promise<HasWorkspaceItemPermissionResponse>
    | Observable<HasWorkspaceItemPermissionResponse>
    | HasWorkspaceItemPermissionResponse;

  getUserWorkspaceItemPermissions(
    request: GetUserWorkspaceItemPermissionsRequest,
    metadata?: Metadata,
  ):
    | Promise<GetUserWorkspaceItemPermissionsResponse>
    | Observable<GetUserWorkspaceItemPermissionsResponse>
    | GetUserWorkspaceItemPermissionsResponse;

  deleteWorkspace(
    request: DeleteWorkspaceRequest,
    metadata?: Metadata,
  ): Promise<DeleteWorkspaceResponse> | Observable<DeleteWorkspaceResponse> | DeleteWorkspaceResponse;
}

export function AuthorizationServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "getUserWorkspaces",
      "createWorkspaceWithOwner",
      "updateWorkspaceMembers",
      "getWorkspaceMembers",
      "leaveWorkspace",
      "hasWorkspacePermission",
      "hasWorkspaceItemPermission",
      "getUserWorkspaceItemPermissions",
      "deleteWorkspace",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AuthorizationService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AuthorizationService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const AUTHORIZATION_SERVICE_NAME = "AuthorizationService";

export type AuthorizationServiceService = typeof AuthorizationServiceService;
export const AuthorizationServiceService = {
  getUserWorkspaces: {
    path: "/authorization.AuthorizationService/GetUserWorkspaces" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetUserWorkspacesRequest): Buffer =>
      Buffer.from(GetUserWorkspacesRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetUserWorkspacesRequest => GetUserWorkspacesRequest.decode(value),
    responseSerialize: (value: GetUserWorkspacesResponse): Buffer =>
      Buffer.from(GetUserWorkspacesResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetUserWorkspacesResponse => GetUserWorkspacesResponse.decode(value),
  },
  createWorkspaceWithOwner: {
    path: "/authorization.AuthorizationService/CreateWorkspaceWithOwner" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: CreateWorkspaceWithOwnerRequest): Buffer =>
      Buffer.from(CreateWorkspaceWithOwnerRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CreateWorkspaceWithOwnerRequest =>
      CreateWorkspaceWithOwnerRequest.decode(value),
    responseSerialize: (value: CreateWorkspaceWithOwnerResponse): Buffer =>
      Buffer.from(CreateWorkspaceWithOwnerResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): CreateWorkspaceWithOwnerResponse =>
      CreateWorkspaceWithOwnerResponse.decode(value),
  },
  updateWorkspaceMembers: {
    path: "/authorization.AuthorizationService/UpdateWorkspaceMembers" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: UpdateWorkspaceMembersRequest): Buffer =>
      Buffer.from(UpdateWorkspaceMembersRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): UpdateWorkspaceMembersRequest => UpdateWorkspaceMembersRequest.decode(value),
    responseSerialize: (value: UpdateWorkspaceMembersResponse): Buffer =>
      Buffer.from(UpdateWorkspaceMembersResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): UpdateWorkspaceMembersResponse =>
      UpdateWorkspaceMembersResponse.decode(value),
  },
  getWorkspaceMembers: {
    path: "/authorization.AuthorizationService/GetWorkspaceMembers" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetWorkspaceMembersRequest): Buffer =>
      Buffer.from(GetWorkspaceMembersRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetWorkspaceMembersRequest => GetWorkspaceMembersRequest.decode(value),
    responseSerialize: (value: GetWorkspaceMembersResponse): Buffer =>
      Buffer.from(GetWorkspaceMembersResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetWorkspaceMembersResponse => GetWorkspaceMembersResponse.decode(value),
  },
  leaveWorkspace: {
    path: "/authorization.AuthorizationService/LeaveWorkspace" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: LeaveWorkspaceRequest): Buffer =>
      Buffer.from(LeaveWorkspaceRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): LeaveWorkspaceRequest => LeaveWorkspaceRequest.decode(value),
    responseSerialize: (value: LeaveWorkspaceResponse): Buffer =>
      Buffer.from(LeaveWorkspaceResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): LeaveWorkspaceResponse => LeaveWorkspaceResponse.decode(value),
  },
  hasWorkspacePermission: {
    path: "/authorization.AuthorizationService/HasWorkspacePermission" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: HasWorkspacePermissionRequest): Buffer =>
      Buffer.from(HasWorkspacePermissionRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): HasWorkspacePermissionRequest => HasWorkspacePermissionRequest.decode(value),
    responseSerialize: (value: HasWorkspacePermissionResponse): Buffer =>
      Buffer.from(HasWorkspacePermissionResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): HasWorkspacePermissionResponse =>
      HasWorkspacePermissionResponse.decode(value),
  },
  hasWorkspaceItemPermission: {
    path: "/authorization.AuthorizationService/HasWorkspaceItemPermission" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: HasWorkspaceItemPermissionRequest): Buffer =>
      Buffer.from(HasWorkspaceItemPermissionRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): HasWorkspaceItemPermissionRequest =>
      HasWorkspaceItemPermissionRequest.decode(value),
    responseSerialize: (value: HasWorkspaceItemPermissionResponse): Buffer =>
      Buffer.from(HasWorkspaceItemPermissionResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): HasWorkspaceItemPermissionResponse =>
      HasWorkspaceItemPermissionResponse.decode(value),
  },
  getUserWorkspaceItemPermissions: {
    path: "/authorization.AuthorizationService/GetUserWorkspaceItemPermissions" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetUserWorkspaceItemPermissionsRequest): Buffer =>
      Buffer.from(GetUserWorkspaceItemPermissionsRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetUserWorkspaceItemPermissionsRequest =>
      GetUserWorkspaceItemPermissionsRequest.decode(value),
    responseSerialize: (value: GetUserWorkspaceItemPermissionsResponse): Buffer =>
      Buffer.from(GetUserWorkspaceItemPermissionsResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetUserWorkspaceItemPermissionsResponse =>
      GetUserWorkspaceItemPermissionsResponse.decode(value),
  },
  deleteWorkspace: {
    path: "/authorization.AuthorizationService/DeleteWorkspace" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: DeleteWorkspaceRequest): Buffer =>
      Buffer.from(DeleteWorkspaceRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): DeleteWorkspaceRequest => DeleteWorkspaceRequest.decode(value),
    responseSerialize: (value: DeleteWorkspaceResponse): Buffer =>
      Buffer.from(DeleteWorkspaceResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): DeleteWorkspaceResponse => DeleteWorkspaceResponse.decode(value),
  },
} as const;

export interface AuthorizationServiceServer extends UntypedServiceImplementation {
  getUserWorkspaces: handleUnaryCall<GetUserWorkspacesRequest, GetUserWorkspacesResponse>;
  createWorkspaceWithOwner: handleUnaryCall<CreateWorkspaceWithOwnerRequest, CreateWorkspaceWithOwnerResponse>;
  updateWorkspaceMembers: handleUnaryCall<UpdateWorkspaceMembersRequest, UpdateWorkspaceMembersResponse>;
  getWorkspaceMembers: handleUnaryCall<GetWorkspaceMembersRequest, GetWorkspaceMembersResponse>;
  leaveWorkspace: handleUnaryCall<LeaveWorkspaceRequest, LeaveWorkspaceResponse>;
  hasWorkspacePermission: handleUnaryCall<HasWorkspacePermissionRequest, HasWorkspacePermissionResponse>;
  hasWorkspaceItemPermission: handleUnaryCall<HasWorkspaceItemPermissionRequest, HasWorkspaceItemPermissionResponse>;
  getUserWorkspaceItemPermissions: handleUnaryCall<
    GetUserWorkspaceItemPermissionsRequest,
    GetUserWorkspaceItemPermissionsResponse
  >;
  deleteWorkspace: handleUnaryCall<DeleteWorkspaceRequest, DeleteWorkspaceResponse>;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
