// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               unknown
// source: note.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { handleUnaryCall, Metadata, UntypedServiceImplementation } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { Timestamp } from "./google/protobuf/timestamp";

export const protobufPackage = "note";

export enum TrashedBy {
  TRASHED_BY_UNSPECIFIED = 0,
  TRASHED_BY_PURPOSE = 1,
  TRASHED_BY_PARENT = 2,
  UNRECOGNIZED = -1,
}

export interface Trashed {
  by: TrashedBy;
  at: Timestamp | undefined;
}

export interface GetNoteNameRequest {
  id: string;
}

export interface GetNoteNameResponse {
  name: string;
}

export interface GetNoteRequest {
  id: string;
  excludeTrashed: boolean;
  userId: string;
}

export interface GetNoteResponse {
  id: string;
  name: string;
  icon?: string | undefined;
  folderId: string;
  tags: string[];
  updatedAt: Timestamp | undefined;
  trashed?: Trashed | undefined;
}

export interface GetWorkspaceIdByNoteIdRequest {
  noteId: string;
}

export interface GetWorkspaceIdByNoteIdResponse {
  workspaceId: string;
}

export const NOTE_PACKAGE_NAME = "note";

function createBaseTrashed(): Trashed {
  return { by: 0, at: undefined };
}

export const Trashed: MessageFns<Trashed> = {
  encode(message: Trashed, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.by !== 0) {
      writer.uint32(8).int32(message.by);
    }
    if (message.at !== undefined) {
      Timestamp.encode(message.at, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Trashed {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTrashed();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.by = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.at = Timestamp.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetNoteNameRequest(): GetNoteNameRequest {
  return { id: "" };
}

export const GetNoteNameRequest: MessageFns<GetNoteNameRequest> = {
  encode(message: GetNoteNameRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetNoteNameRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetNoteNameRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetNoteNameResponse(): GetNoteNameResponse {
  return { name: "" };
}

export const GetNoteNameResponse: MessageFns<GetNoteNameResponse> = {
  encode(message: GetNoteNameResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetNoteNameResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetNoteNameResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetNoteRequest(): GetNoteRequest {
  return { id: "", excludeTrashed: false, userId: "" };
}

export const GetNoteRequest: MessageFns<GetNoteRequest> = {
  encode(message: GetNoteRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.excludeTrashed !== false) {
      writer.uint32(16).bool(message.excludeTrashed);
    }
    if (message.userId !== "") {
      writer.uint32(26).string(message.userId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetNoteRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetNoteRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.excludeTrashed = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetNoteResponse(): GetNoteResponse {
  return { id: "", name: "", folderId: "", tags: [], updatedAt: undefined };
}

export const GetNoteResponse: MessageFns<GetNoteResponse> = {
  encode(message: GetNoteResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.icon !== undefined) {
      writer.uint32(26).string(message.icon);
    }
    if (message.folderId !== "") {
      writer.uint32(34).string(message.folderId);
    }
    for (const v of message.tags) {
      writer.uint32(42).string(v!);
    }
    if (message.updatedAt !== undefined) {
      Timestamp.encode(message.updatedAt, writer.uint32(50).fork()).join();
    }
    if (message.trashed !== undefined) {
      Trashed.encode(message.trashed, writer.uint32(58).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetNoteResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetNoteResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.icon = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.folderId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.tags.push(reader.string());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.updatedAt = Timestamp.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.trashed = Trashed.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetWorkspaceIdByNoteIdRequest(): GetWorkspaceIdByNoteIdRequest {
  return { noteId: "" };
}

export const GetWorkspaceIdByNoteIdRequest: MessageFns<GetWorkspaceIdByNoteIdRequest> = {
  encode(message: GetWorkspaceIdByNoteIdRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.noteId !== "") {
      writer.uint32(10).string(message.noteId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetWorkspaceIdByNoteIdRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetWorkspaceIdByNoteIdRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.noteId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

function createBaseGetWorkspaceIdByNoteIdResponse(): GetWorkspaceIdByNoteIdResponse {
  return { workspaceId: "" };
}

export const GetWorkspaceIdByNoteIdResponse: MessageFns<GetWorkspaceIdByNoteIdResponse> = {
  encode(message: GetWorkspaceIdByNoteIdResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.workspaceId !== "") {
      writer.uint32(10).string(message.workspaceId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetWorkspaceIdByNoteIdResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetWorkspaceIdByNoteIdResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.workspaceId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },
};

export interface NoteServiceClient {
  /** NOTE: maybe this will be replaced with batch get */

  getNoteName(request: GetNoteNameRequest, metadata?: Metadata): Observable<GetNoteNameResponse>;

  getNote(request: GetNoteRequest, metadata?: Metadata): Observable<GetNoteResponse>;

  /** NOTE: what, where is this used? */

  getWorkspaceIdByNoteId(
    request: GetWorkspaceIdByNoteIdRequest,
    metadata?: Metadata,
  ): Observable<GetWorkspaceIdByNoteIdResponse>;
}

export interface NoteServiceController {
  /** NOTE: maybe this will be replaced with batch get */

  getNoteName(
    request: GetNoteNameRequest,
    metadata?: Metadata,
  ): Promise<GetNoteNameResponse> | Observable<GetNoteNameResponse> | GetNoteNameResponse;

  getNote(
    request: GetNoteRequest,
    metadata?: Metadata,
  ): Promise<GetNoteResponse> | Observable<GetNoteResponse> | GetNoteResponse;

  /** NOTE: what, where is this used? */

  getWorkspaceIdByNoteId(
    request: GetWorkspaceIdByNoteIdRequest,
    metadata?: Metadata,
  ):
    | Promise<GetWorkspaceIdByNoteIdResponse>
    | Observable<GetWorkspaceIdByNoteIdResponse>
    | GetWorkspaceIdByNoteIdResponse;
}

export function NoteServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getNoteName", "getNote", "getWorkspaceIdByNoteId"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("NoteService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("NoteService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const NOTE_SERVICE_NAME = "NoteService";

export type NoteServiceService = typeof NoteServiceService;
export const NoteServiceService = {
  /** NOTE: maybe this will be replaced with batch get */
  getNoteName: {
    path: "/note.NoteService/GetNoteName" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetNoteNameRequest): Buffer => Buffer.from(GetNoteNameRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetNoteNameRequest => GetNoteNameRequest.decode(value),
    responseSerialize: (value: GetNoteNameResponse): Buffer => Buffer.from(GetNoteNameResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetNoteNameResponse => GetNoteNameResponse.decode(value),
  },
  getNote: {
    path: "/note.NoteService/GetNote" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetNoteRequest): Buffer => Buffer.from(GetNoteRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetNoteRequest => GetNoteRequest.decode(value),
    responseSerialize: (value: GetNoteResponse): Buffer => Buffer.from(GetNoteResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetNoteResponse => GetNoteResponse.decode(value),
  },
  /** NOTE: what, where is this used? */
  getWorkspaceIdByNoteId: {
    path: "/note.NoteService/GetWorkspaceIdByNoteId" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: GetWorkspaceIdByNoteIdRequest): Buffer =>
      Buffer.from(GetWorkspaceIdByNoteIdRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetWorkspaceIdByNoteIdRequest => GetWorkspaceIdByNoteIdRequest.decode(value),
    responseSerialize: (value: GetWorkspaceIdByNoteIdResponse): Buffer =>
      Buffer.from(GetWorkspaceIdByNoteIdResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetWorkspaceIdByNoteIdResponse =>
      GetWorkspaceIdByNoteIdResponse.decode(value),
  },
} as const;

export interface NoteServiceServer extends UntypedServiceImplementation {
  /** NOTE: maybe this will be replaced with batch get */
  getNoteName: handleUnaryCall<GetNoteNameRequest, GetNoteNameResponse>;
  getNote: handleUnaryCall<GetNoteRequest, GetNoteResponse>;
  /** NOTE: what, where is this used? */
  getWorkspaceIdByNoteId: handleUnaryCall<GetWorkspaceIdByNoteIdRequest, GetWorkspaceIdByNoteIdResponse>;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
}
