# yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
version: 1
metadata:
  name: Notopia - App Web
  labels:
    blueprint-group: notopia
    blueprints.goauthentik.io/description: |
      Notopia - App Web OAuth2 Provider and Application

entries:
  - model: authentik_blueprints.metaapplyblueprint
    attrs:
      identifiers:
        name: Notopia - Providers Oauth2

  - id: provider
    model: authentik_providers_oauth2.oauth2provider
    identifiers:
      client_id: app-web
    attrs:
      name: App Web
      client_secret: notopiauit
      client_type: confidential
      access_code_validity: minutes=10
      access_token_validity: days=30
      refresh_token_threshold: hours=1
      refresh_token_validity: days=90
      sub_mode: user_id
      authorization_flow:
        !Find [
          authentik_flows.flow,
          [slug, default-provider-authorization-implicit-consent],
        ]
      invalidation_flow:
        !Find [authentik_flows.flow, [slug, default-provider-invalidation-flow]]
      signing_key:
        !Find [
          authentik_crypto.certificatekeypair,
          [name, authentik Self-signed Certificate],
        ]
      property_mappings:
        - !Find [authentik_providers_oauth2.scopemapping, [scope_name, openid]]
        - !Find [authentik_providers_oauth2.scopemapping, [scope_name, profile]]
        - !Find [authentik_providers_oauth2.scopemapping, [scope_name, email]]
        - !Find [authentik_providers_oauth2.scopemapping, [scope_name, picture]]
      redirect_uris:
        - url: http://web.notopia.localhost/api/auth/oauth2/callback/authentik
          matching_mode: strict

  - model: authentik_core.application
    identifiers:
      slug: app-web
    attrs:
      name: App Web
      provider: !KeyOf provider
