# vim:ft=yaml.docker-compose:
# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-go/master/schema/compose-spec.json
services:
  dbgate:
    image: dbgate/dbgate:7.1.13-alpine
    container_name: notopia-dbgate
    environment:
      SKIP_ALL_AUTH: true

      CONNECTIONS: note_postgresql,note_redis,document_postgresql,authorization_postgresql

      LABEL_note_postgresql: Note PostgreSQL
      ENGINE_note_postgresql: postgres@dbgate-plugin-postgres
      URL_note_postgresql: postgres://${NOTE_POSTGRESQL_USER:-notopiauit}:${NOTE_POSTGRESQL_PASSWORD:-notopiauit}@note_postgresql:5432/${NOTE_POSTGRESQL_DB:-note}

      LABEL_note_redis: Note Redis
      ENGINE_note_redis: redis@dbgate-plugin-redis
      URL_note_redis: redis://note_redis:6379

      LABEL_document_postgresql: Document PostgreSQL
      ENGINE_document_postgresql: postgres@dbgate-plugin-postgres
      URL_document_postgresql: postgres://${DOCUMENT_POSTGRESQL_USER:-notopiauit}:${DOCUMENT_POSTGRESQL_PASSWORD:-notopiauit}@document_postgresql:5432/${DOCUMENT_POSTGRESQL_DB:-document}

      LABEL_authorization_postgresql: Authorization PostgreSQL
      ENGINE_authorization_postgresql: postgres@dbgate-plugin-postgres
      URL_authorization_postgresql: postgres://${AUTHORIZATION_POSTGRESQL_USER:-notopiauit}:${AUTHORIZATION_POSTGRESQL_PASSWORD:-notopiauit}@authorization_postgresql:5432/${AUTHORIZATION_POSTGRESQL_DB:-authorization}
    volumes:
      - dbgate_data:/root/.dbgate
    labels:
      traefik.enable: "true"
      traefik.http.routers.dbgate.rule: Host(`dbgate.notopia.localhost`)
      traefik.http.routers.dbgate.entrypoints: web
      traefik.http.services.dbgate.loadbalancer.server.port: "3000"
    profiles:
      - dev-ui
    restart: unless-stopped

volumes:
  dbgate_data:
