# vim:ft=yaml.docker-compose:
# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-go/master/schema/compose-spec.json
services:
  rustfs:
    container_name: notopia-rustfs
    image: rustfs/rustfs:1.0.0-alpha.94-glibc
    environment:
      RUSTFS_ACCESS_KEY: ${RUSTFS_ACCESS_KEY:-notopiauit}
      RUSTFS_SECRET_KEY: ${RUSTFS_SECRET_KEY:-notopiauit}
      RUSTFS_CONSOLE_ENABLE: 'true'
      RUSTFS_SERVER_DOMAINS: rustfs.notopia.localhost
    volumes:
      - rustfs:/data
      - rustfs_logs:/logs
    labels:
      traefik.enable: 'true'
      traefik.http.routers.rustfs-api.rule: Host(`rustfs-api.notopia.localhost`)
      traefik.http.routers.rustfs-api.entrypoints: web
      traefik.http.routers.rustfs-api.service: rustfs-api
      traefik.http.services.rustfs-api.loadbalancer.server.port: '9000'
      traefik.http.routers.rustfs-console.rule: Host(`rustfs.notopia.localhost`)
      traefik.http.routers.rustfs-console.entrypoints: web
      traefik.http.routers.rustfs-console.service: rustfs-console
      traefik.http.services.rustfs-console.loadbalancer.server.port: '9001'
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:9000/health
      start_period: 10s
      start_interval: 1s
    restart: unless-stopped
    depends_on:
      rustfs_volume_permission_helper:
        condition: service_completed_successfully

  rustfs_volume_permission_helper:
    image: alpine
    container_name: notopia-rustfs_volume_permission_helper
    volumes:
      - rustfs:/data
      - rustfs_logs:/logs
    command: > # language: sh
      sh -c "
        chown -R 10001:10001 /data /logs
        echo 'Volume Permissions fixed'
      "
    restart: 'no'

  rustfs_bucket:
    image: minio/mc:RELEASE.2025-08-13T08-35-41Z
    container_name: notopia-rustfs_bucket
    entrypoint: > # language: sh
      /bin/sh -c '
        until (/usr/bin/mc alias set rustfs http://rustfs:9000 ${RUSTFS_ACCESS_KEY:-notopiauit} ${RUSTFS_SECRET_KEY:-notopiauit}) do
          sleep 1;
        done
        /usr/bin/mc mb rustfs/document;
        /usr/bin/mc anonymous set public rustfs/document;
      '
    restart: 'no'
    depends_on:
      rustfs:
        condition: service_healthy

volumes:
  rustfs:
  rustfs_logs:
