// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: note.proto

package pb

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckNoteExistenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoteId        string                 `protobuf:"bytes,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckNoteExistenceRequest) Reset() {
	*x = CheckNoteExistenceRequest{}
	mi := &file_note_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckNoteExistenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckNoteExistenceRequest) ProtoMessage() {}

func (x *CheckNoteExistenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_note_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckNoteExistenceRequest.ProtoReflect.Descriptor instead.
func (*CheckNoteExistenceRequest) Descriptor() ([]byte, []int) {
	return file_note_proto_rawDescGZIP(), []int{0}
}

func (x *CheckNoteExistenceRequest) GetNoteId() string {
	if x != nil {
		return x.NoteId
	}
	return ""
}

type CheckNoteExistenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckNoteExistenceResponse) Reset() {
	*x = CheckNoteExistenceResponse{}
	mi := &file_note_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckNoteExistenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckNoteExistenceResponse) ProtoMessage() {}

func (x *CheckNoteExistenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_note_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckNoteExistenceResponse.ProtoReflect.Descriptor instead.
func (*CheckNoteExistenceResponse) Descriptor() ([]byte, []int) {
	return file_note_proto_rawDescGZIP(), []int{1}
}

func (x *CheckNoteExistenceResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

var File_note_proto protoreflect.FileDescriptor

const file_note_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"note.proto\x12\x04note\x1a\x1bbuf/validate/validate.proto\"A\n" +
	"\x19CheckNoteExistenceRequest\x12$\n" +
	"\anote_id\x18\x01 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\x06noteId\"<\n" +
	"\x1aCheckNoteExistenceResponse\x12\x1e\n" +
	"\x06exists\x18\x01 \x01(\bB\x06\xbaH\x03\xc8\x01\x01R\x06exists2f\n" +
	"\vNoteService\x12W\n" +
	"\x12CheckNoteExistence\x12\x1f.note.CheckNoteExistenceRequest\x1a .note.CheckNoteExistenceResponseBl\n" +
	"\bcom.noteB\tNoteProtoP\x01Z%github.com/notopia-uit/notopia/pkg/pb\xa2\x02\x03NXX\xaa\x02\x04Note\xca\x02\x04Note\xe2\x02\x10Note\\GPBMetadata\xea\x02\x04Noteb\x06proto3"

var (
	file_note_proto_rawDescOnce sync.Once
	file_note_proto_rawDescData []byte
)

func file_note_proto_rawDescGZIP() []byte {
	file_note_proto_rawDescOnce.Do(func() {
		file_note_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_note_proto_rawDesc), len(file_note_proto_rawDesc)))
	})
	return file_note_proto_rawDescData
}

var file_note_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_note_proto_goTypes = []any{
	(*CheckNoteExistenceRequest)(nil),  // 0: note.CheckNoteExistenceRequest
	(*CheckNoteExistenceResponse)(nil), // 1: note.CheckNoteExistenceResponse
}
var file_note_proto_depIdxs = []int32{
	0, // 0: note.NoteService.CheckNoteExistence:input_type -> note.CheckNoteExistenceRequest
	1, // 1: note.NoteService.CheckNoteExistence:output_type -> note.CheckNoteExistenceResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_note_proto_init() }
func file_note_proto_init() {
	if File_note_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_note_proto_rawDesc), len(file_note_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_note_proto_goTypes,
		DependencyIndexes: file_note_proto_depIdxs,
		MessageInfos:      file_note_proto_msgTypes,
	}.Build()
	File_note_proto = out.File
	file_note_proto_goTypes = nil
	file_note_proto_depIdxs = nil
}
