// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/goforj/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/notopia-uit/notopia/pkg/common/controller/http"
	"github.com/notopia-uit/notopia/pkg/note"
	"github.com/notopia-uit/notopia/pkg/note/app"
	"github.com/notopia-uit/notopia/pkg/note/component"
	"github.com/notopia-uit/notopia/pkg/note/config"
	"github.com/notopia-uit/notopia/pkg/note/controller"
	"github.com/notopia-uit/notopia/pkg/note/controller/grpc"
	http2 "github.com/notopia-uit/notopia/pkg/note/controller/http"
	"github.com/notopia-uit/notopia/pkg/note/infra/persistence"
	"github.com/notopia-uit/notopia/pkg/note/infra/persistence/pg"
	"github.com/notopia-uit/notopia/pkg/otel"
)

// Injectors from wire.go:

func InitializeServer(ctx context.Context) (*controller.Server, func(), error) {
	serviceName := _wireServiceNameValue
	validate := components.ProvideValidate()
	viper := config.NewViper()
	configConfig, err := config.New(validate, viper)
	if err != nil {
		return nil, nil, err
	}
	otlp := &configConfig.OTLP
	otlpLog := &otlp.Log
	serviceVersion := _wireServiceVersionValue
	resource, err := otel.NewResource(serviceName, serviceVersion)
	if err != nil {
		return nil, nil, err
	}
	loggerProvider, cleanup, err := otel.NewLoggerProvider(ctx, otlpLog, resource)
	if err != nil {
		return nil, nil, err
	}
	logger := otel.NewSlog(serviceName, loggerProvider)
	ginSlogHandlerFunc := http.NewGinSlogHandler(logger)
	otlpMeter := &otlp.Meter
	meterProvider, cleanup2, err := otel.NewMeterProvider(ctx, otlpMeter, resource)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	otlpTrace := &otlp.Trace
	tracerProvider, cleanup3, err := otel.NewTracerProvider(ctx, otlpTrace, resource)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	otelGinHandlerFunc := http.NewOtelGinHandler(serviceName, meterProvider, tracerProvider)
	engine := http.NewGin(ginSlogHandlerFunc, otelGinHandlerFunc)
	appApp := app.NewApp()
	strictHandler := http2.NewStrictHandler(appApp)
	serverInterface := http2.NewHandler(strictHandler)
	sql := &configConfig.Database
	pool, cleanup4, err := pg.NewPgPool(ctx, tracerProvider, sql)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	db := pg.NewStdlib(pool)
	persistencePg, err := persistence.NewPg(db, pool)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	healthManager := http2.NewHealthManager(persistencePg)
	server := &configConfig.Server
	httpServer, cleanup5, err := http2.New(ctx, engine, serverInterface, healthManager, server)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	handler := grpc.NewHandler(appApp)
	grpcServer, cleanup6, err := grpc.New(ctx, handler, server, tracerProvider, meterProvider, logger)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	controllerServer := controller.NewServer(httpServer, grpcServer, healthManager, persistencePg, logger)
	return controllerServer, func() {
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

var (
	_wireServiceNameValue    = note.ServiceName
	_wireServiceVersionValue = note.ServiceVersion
)
