# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redocly.com/docs/cli/ for more information.
common/components/securitySchemes/Oauth2.yaml:
  struct:
    - '#/flows/authorizationCode/x-usePkce'
note/components/examples/NoteGraph.json:
  no-invalid-media-type-examples:
    - '#//nodes/1/weight'
    - '#//nodes/3/weight'
    - '#//nodes/7/weight'
    - '#//nodes/8/weight'
    - '#//nodes/9/weight'
    - '#//nodes/10/weight'
    - '#//nodes/13/weight'
    - '#//nodes/26/weight'
    - '#//nodes/27/weight'
    - '#//nodes/29/weight'
    - '#//nodes/36/weight'
    - '#//nodes/38/weight'
    - '#//nodes/39/weight'
    - '#//nodes/42/weight'
    - '#//nodes/46/weight'
    - '#//nodes/47/weight'
    - '#//nodes/49/weight'
    - '#//nodes/53/weight'
    - '#//nodes/55/weight'
    - '#//nodes/60/weight'
    - '#//nodes/62/weight'
    - '#//nodes/63/weight'
    - '#//nodes/64/weight'
    - '#//nodes/68/weight'
    - '#//nodes/70/weight'
    - '#//nodes/71/weight'
    - '#//nodes/76/weight'
    - '#//nodes/79/weight'
    - '#//nodes/81/weight'
    - '#//nodes/84/weight'
    - '#//nodes/85/weight'
    - '#//nodes/87/weight'
    - '#//nodes/90/weight'
    - '#//nodes/97/weight'
    - '#//nodes/100/weight'
    - '#//nodes/101/weight'
    - '#//nodes/104/weight'
    - '#//nodes/105/weight'
    - '#//nodes/107/weight'
    - '#//nodes/112/weight'
    - '#//nodes/113/weight'
    - '#//nodes/118/weight'
    - '#//nodes/122/weight'
    - '#//nodes/123/weight'
    - '#//nodes/126/weight'
    - '#//nodes/127/weight'
    - '#//nodes/135/weight'
    - '#//nodes/136/weight'
    - '#//nodes/137/weight'
    - '#//nodes/140/weight'
    - '#//nodes/146/weight'
    - '#//nodes/147/weight'
    - '#//nodes/148/weight'
    - '#//nodes/155/weight'
    - '#//nodes/156/weight'
    - '#//nodes/158/weight'
    - '#//nodes/161/weight'
    - '#//nodes/166/weight'
    - '#//nodes/172/weight'
    - '#//nodes/174/weight'
    - '#//nodes/176/weight'
    - '#//nodes/177/weight'
    - '#//nodes/182/weight'
    - '#//nodes/184/weight'
    - '#//nodes/203/weight'
    - '#//nodes/204/weight'
    - '#//nodes/209/weight'
    - '#//nodes/211/weight'
    - '#//nodes/212/weight'
    - '#//nodes/218/weight'
    - '#//nodes/223/weight'
    - '#//nodes/228/weight'
    - '#//nodes/229/weight'
    - '#//nodes/232/weight'
    - '#//nodes/237/weight'
    - '#//nodes/238/weight'
    - '#//nodes/239/weight'
    - '#//nodes/241/weight'
    - '#//nodes/243/weight'
    - '#//nodes/244/weight'
    - '#//nodes/247/weight'
    - '#//nodes/248/weight'
    - '#//nodes/249/weight'
    - '#//nodes/253/weight'
    - '#//nodes/255/weight'
    - '#//nodes/259/weight'
    - '#//nodes/264/weight'
    - '#//nodes/265/weight'
    - '#//nodes/271/weight'
    - '#//nodes/273/weight'
    - '#//nodes/290/weight'
    - '#//nodes/294/weight'
    - '#//nodes/296/weight'
    - '#//nodes/301/weight'
    - '#//nodes/307/weight'
    - '#//nodes/308/weight'
    - '#//nodes/313/weight'
    - '#//nodes/314/weight'
    - '#//nodes/315/weight'
    - '#//nodes/318/weight'
    - '#//nodes/320/weight'
    - '#//nodes/324/weight'
    - '#//nodes/329/weight'
    - '#//nodes/330/weight'
    - '#//nodes/334/weight'
    - '#//nodes/335/weight'
    - '#//nodes/337/weight'
    - '#//nodes/339/weight'
    - '#//nodes/352/weight'
    - '#//nodes/354/weight'
    - '#//nodes/356/weight'
    - '#//nodes/358/weight'
    - '#//nodes/360/weight'
    - '#//nodes/363/weight'
    - '#//nodes/365/weight'
    - '#//nodes/374/weight'
    - '#//nodes/377/weight'
    - '#//nodes/378/weight'
    - '#//nodes/379/weight'
    - '#//nodes/385/weight'
    - '#//nodes/388/weight'
    - '#//nodes/393/weight'
    - '#//nodes/397/weight'
    - '#//nodes/401/weight'
    - '#//nodes/404/weight'
    - '#//nodes/420/weight'
    - '#//nodes/421/weight'
    - '#//nodes/425/weight'
    - '#//nodes/426/weight'
    - '#//nodes/430/weight'
    - '#//nodes/462/weight'
    - '#//nodes/464/weight'
    - '#//nodes/467/weight'
    - '#//nodes/477/weight'
    - '#//nodes/482/weight'
    - '#//nodes/485/weight'
    - '#//nodes/493/weight'
    - '#//nodes/494/weight'
    - '#//nodes/495/weight'
    - '#//nodes/497/weight'
    - '#//nodes/499/weight'
    - '#//nodes/501/weight'
    - '#//nodes/505/weight'
