name: CI

on:
  push:
    branches:
      - '*'
    paths-ignore: &pushPathsIgnore
      - README.md
      - .dockerignore
      - .editorconfig
      - .gitattributes
      - .gitignore
      - .harper-dictionary.txt
      - .lazy.lua
      - .wakatime-project
      - .nvim.lua
      - justfile
  pull_request:
    branches:
      - '*'
    paths-ignore: *pushPathsIgnore
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:
    inputs:
      publishWeb:
        description: Publish "web" container image
        required: true
        default: false
        type: boolean
      publishNote:
        description: Publish "note" container image
        required: true
        default: false
        type: boolean
      publishDocument:
        description: Publish "document" container image
        required: true
        default: false
        type: boolean
      publishNpmGroups:
        description: Publish packages npm group
        required: true
        default: false
        type: boolean
      forceNxRun:
        description: Force Nx to run many instead of affected
        required: false
        default: false
        type: boolean
      skipNxCache:
        description: Skip Nx cache
        required: false
        default: false
        type: boolean

env:
  MISE_OVERRIDE_CONFIG_FILENAMES: .mise.ci.toml
  IS_RENOVATE: ${{ startsWith(github.head_ref || github.ref_name, 'renovate/') }}
  SHOULD_CACHE: >-
    ${{
      (
        github.ref_name == 'main' ||
        github.base_ref == 'main'
      ) && (
        !startsWith(github.head_ref || github.ref_name, 'renovate/')
      )
    }}
  NX_PARALLEL: 2

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          cache: ${{ env.SHOULD_CACHE == 'true' }}

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: .tool-versions
          cache: ${{ env.SHOULD_CACHE == 'true' && 'pnpm' || '' }}

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: .tool-versions
          cache: ${{ env.SHOULD_CACHE == 'true' }}

      - name: Setup golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          install-only: true
          version-file: .tool-versions
          skip-save-cache: ${{ env.SHOULD_CACHE != 'true' }}

      - name: Setup Mise
        uses: jdx/mise-action@v3
        with:
          experimental: true
          cache: ${{ env.SHOULD_CACHE == 'true' }}

      - name: Cache Buf dependencies
        uses: actions/cache@v5
        with:
          path: ~/.cache/buf
          key: ${{ runner.os }}-buf-${{ hashFiles('**/buf.lock') }}
          restore-keys: ${{ runner.os }}-buf-

      - name: Derive SHAs for Nx Affected
        id: set-shas
        uses: nrwl/nx-set-shas@v4

      - name: Restore Nx Cache
        uses: actions/cache/restore@v5
        with:
          path: .nx
          key: ${{ runner.os }}-nx-${{ github.ref_name }}-${{ steps.set-shas.outputs.base }}
          restore-keys: |
            ${{ runner.os }}-nx-${{ github.ref_name }}-
            ${{ runner.os }}-nx-${{ github.event.repository.default_branch }}-

      - name: Restore Docs diagrams Cache
        uses: actions/cache/restore@v5
        with:
          path: docs/src/public/diagrams/
          key: docs-diagrams-

      - name: Install Node Dependencies
        run: pnpm install

      - name: Install Go Dependencies
        run: go mod download

      - name: Setup Git User
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          git config --global user.name github-actions[bot]
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Nx all
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx nx ${{ github.event.inputs.forceNxRun == 'true' && 'run-many' || 'affected' }} \
            --target lint \
            --target format:check \
            --target gen \
            --target bundle \
            --target build \
            --target test \
            ${{ github.ref == 'refs/heads/main' && '--target docker:build' || '' }} \
            ${{ github.ref == 'refs/heads/main' && '--target deploy' || '' }} \
            --parallel=${{env.NX_PARALLEL }} \
            ${{ github.event.inputs.skipNxCache == 'true' && '--skipNxCache' || '' }}

      - name: Check for changes after Build/Gen
        run: |
          git add .
          if ! git diff --staged --exit-code --color-words; then
            echo "ERROR: There are uncommitted changes after build/gen. Please commit the changes.";
            git status --short
            exit 1;
          fi

      - name: Github npm token
        if: >-
          ${{
            github.ref == 'refs/heads/main' &&
            github.event_name == 'workflow_dispatch' &&
            github.event.inputs.publishNpmGroups == 'true'
          }}
        run: npm config set //registry.npmjs.org/:_authToken=${{ github.token }} --global

      - name: Nx release
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx nx release \
            --dockerVersionScheme=${{ github.event_name == 'push' && 'development' || 'production' }} \
            ${{ (github.event_name == 'push' || github.event.inputs.publishWeb == 'true') && '--projects web' || '' }} \
            ${{ (github.event_name == 'push' || github.event.inputs.publishNote == 'true') && '--projects note' || '' }} \
            ${{ (github.event_name == 'push' || github.event.inputs.publishDocument == 'true') && '--projects document' || '' }} \
          npx nx release \
            ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.publishNpmGroups == 'true') && '--group npm' || '' }}

      - name: Cache Nx
        uses: actions/cache/save@v5
        if: ${{ env.SHOULD_CACHE == 'true' }}
        with:
          path: .nx
          key: ${{ runner.os }}-nx-${{ github.ref_name }}-${{ steps.set-shas.outputs.base }}

      - name: Cache Docs diagrams
        uses: actions/cache/save@v5
        if: ${{ env.SHOULD_CACHE == 'true' }}
        with:
          path: docs/src/public/diagrams/
          key: docs-diagrams-${{ hashFiles('docs/src/public/diagrams/**') }}
