name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:
    inputs:
      dry-run-release:
        description: Perform a Nx dry run release
        required: false
        default: true
        type: boolean

env:
  MISE_OVERRIDE_CONFIG_FILENAMES: .mise.ci.toml
  IS_PRIMARY_BRANCH: >-
    ${{
      github.ref == 'refs/heads/main' ||
      github.ref == 'refs/heads/dev' ||
      github.base_ref == 'main' ||
      github.base_ref == 'dev'
    }}
  IS_RENOVATE: ${{ startsWith(github.head_ref, 'renovate/') }}

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          cache: >-
            ${{
              env.IS_PRIMARY_BRANCH == 'true' &&
              env.IS_RENOVATE == 'false'
            }}

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: .tool-versions
          cache: >-
            ${{
              (env.IS_PRIMARY_BRANCH == 'true' && env.IS_RENOVATE == 'false')
              && 'pnpm'
              || ''
            }}

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: .tool-versions
          cache: >-
            ${{
              env.IS_PRIMARY_BRANCH == 'true' &&
              env.IS_RENOVATE == 'false'
            }}

      - name: Setup golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          install-only: true
          version-file: .tool-versions
          skip-save-cache: >-
            ${{
              env.IS_PRIMARY_BRANCH == 'true' &&
              env.IS_RENOVATE == 'false'
            }}

      - name: Setup Mise
        uses: jdx/mise-action@v3
        with:
          experimental: true
          cache: >-
            ${{
              env.IS_PRIMARY_BRANCH == 'true' &&
              env.IS_RENOVATE == 'false'
            }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Buf dependencies
        uses: actions/cache@v5
        with:
          path: ~/.cache/buf
          key: ${{ runner.os }}-buf-${{ hashFiles('**/buf.lock') }}
          restore-keys: ${{ runner.os }}-buf-

      - name: Derive SHAs for Nx Affected
        id: set-shas
        uses: nrwl/nx-set-shas@v4

      - name: Restore Nx Cache
        uses: actions/cache/restore@v5
        with:
          path: .nx
          key: ${{ runner.os }}-nx-${{ github.ref_name }}-${{ steps.set-shas.outputs.base }}
          restore-keys: |
            ${{ runner.os }}-nx-${{ github.ref_name }}-
            ${{ runner.os }}-nx-${{ github.event.repository.default_branch }}-

      - name: Restore Docs diagrams Cache
        uses: actions/cache/restore@v5
        with:
          path: docs/src/public/diagrams/
          key: docs-diagrams-

      - name: Install Node Dependencies
        run: pnpm install

      - name: Install Go Dependencies
        run: go mod download

      - name: Nx Affected Test
        run: |
          npx nx affected \
            --target test \
            --parallel=5 \
            --base=${{ steps.set-shas.outputs.base }} \
            --head=${{ steps.set-shas.outputs.head }} \
            | true

      - name: Nx Affected Build, Lint, Format Check, Gen, Bundle
        run: |
          npx nx affected \
            --target lint \
            --target format:check \
            --target gen \
            --target bundle \
            --target build \
            ${{ github.ref == 'refs/heads/main' && '--target docker:build' || '' }} \
            --parallel=4 \
            --base=${{ steps.set-shas.outputs.base }} \
            --head=${{ steps.set-shas.outputs.head }}

      - name: Check for Changes after Build/Gen
        run: |
          git add .
          if ! git diff --staged --exit-code --color=always; then
            echo "ERROR: There are uncommitted changes after build/gen. Please commit the changes.";
            git status --short --color=always
            exit 1;
          fi

      - name: Setup Git User
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions [Bot]"

      - name: Nx release
        if: ${{
          (github.ref == 'refs/heads/main' && github.event_name != 'workflow_dispatch') ||
          github.ref != 'refs/heads/main'
          }}
        run: |
          npx nx release \
            --dockerVersionScheme=production \
            ${{ (github.event.inputs.dry-run-release == 'true' || github.ref != 'refs/heads/main') && '--dry-run' || '' }}

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: npx nx affected -t deploy --parallel=4
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Nx
        uses: actions/cache/save@v5
        if: >-
          ${{
            env.IS_PRIMARY_BRANCH == 'true' &&
            env.IS_RENOVATE == 'false'
          }}
        with:
          path: .nx
          key: ${{ runner.os }}-nx-${{ github.ref_name }}-${{ steps.set-shas.outputs.base }}

      - name: Cache Docs diagrams
        uses: actions/cache/save@v5
        if: >-
          ${{
            env.IS_PRIMARY_BRANCH == 'true' &&
            env.IS_RENOVATE == 'false'
          }}
        with:
          path: docs/src/public/diagrams/
          key: docs-diagrams-${{ hashFiles('docs/src/public/diagrams/**') }}
