name: CI

on:
  push:
    branches:
      - "**"
    paths-ignore: &pushPathsIgnore
      - .agents/**/*
      - .dockerignore
      - .editorconfig
      - .gitattributes
      - .gitignore
      - .harper-dictionary.txt
      - .husky/**/*
      - .lazy.lua
      - .nvim.lua
      - .renovaterc.json
      - .vscode/**/*
      - .wakatime-project
      - README.md
      - deploy/**/*
      - justfile
      - mise.development.toml
      - mise.toml
  pull_request:
    branches:
      - "**"
    paths-ignore: *pushPathsIgnore
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:
    inputs:
      noRestoreDocsDiagramsCache:
        description: No restore docs diagrams cache
        required: true
        default: false
        type: boolean
      resetNxCache:
        description: Reset Nx cache
        required: true
        default: false
        type: boolean
      nxAllCmd:
        description: Nx All command to run
        required: true
        default: affected
        type: choice
        options:
          - affected
          - run-many
      skipNxCache:
        description: Skip Nx cache
        required: true
        default: false
        type: boolean
      releaseWeb:
        description: Release "web" container
        required: true
        default: false
        type: boolean
      releaseNote:
        description: Release "note" container
        required: true
        default: false
        type: boolean
      releaseDocument:
        description: Release "document" container
        required: true
        default: false
        type: boolean
      releaseSearchWorker:
        description: Release "search-worker" container
        required: true
        default: false
        type: boolean
      releaseNpm:
        description: Release NPM packages
        required: true
        default: false
        type: boolean
      releaseAll:
        description: Release all containers and npm packages (Use this or the above specific release options, not both)
        required: true
        default: false
        type: boolean
      releaseContainerType:
        type: choice
        description: Container Release Type
        options:
          - development
          - production
        default: development
        required: true

env:
  MISE_OVERRIDE_CONFIG_FILENAMES: .mise.ci.toml
  IS_RENOVATE: ${{ startsWith(github.head_ref || github.ref_name, 'renovate/') }}
  NX_CACHE_ACTION_SKIP_UPLOAD_CACHE: ${{ startsWith(github.head_ref || github.ref_name, 'renovate/') }}
  SHOULD_CACHE: >-
    ${{
      (
        github.ref_name == 'main' ||
        github.ref_name == 'dev' ||
        github.base_ref == 'main' ||
        github.base_ref == 'dev'
      ) && (
        !startsWith(github.head_ref || github.ref_name, 'renovate/')
      )
    }}
  SHOULD_RELEASE: >-
    ${{
      github.event_name == 'workflow_dispatch' &&
      github.ref_name == 'main' &&
      (
        github.event.inputs.releaseWeb == 'true' ||
        github.event.inputs.releaseNote == 'true' ||
        github.event.inputs.releaseDocument == 'true' ||
        github.event.inputs.releaseSearchWorker == 'true' ||
        github.event.inputs.releaseNpm == 'true' ||
        github.event.inputs.releaseAll == 'true'
      )
    }}
  NX_PARALLEL: 3

concurrency:
  group: ${{ github.ref == 'refs/heads/main' && format('{0}-{1}', github.workflow, github.ref) || github.run_id }}

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: write
      actions: write
      packages: write
      pages: write
      id-token: write
    steps:
      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v4

      # - name: Get token
      #   id: get-bot-token
      #   if: ${{ env.SHOULD_RELEASE == 'true' }}
      #   uses: actions/create-github-app-token@v2
      #   with:
      #     private-key: ${{ secrets.NOTOPIA_BOT_PRIVATE_KEY }}
      #     app-id: ${{ vars.NOTOPIA_BOT_APP_ID }}
      #     owner: ${{ github.repository_owner }}
      #     repositories: |
      #       ${{ github.event.repository.name }}
      #       infra

      - name: Setup Git User
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          git config --global user.name github-actions[bot]
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        if: ${{ env.SHOULD_RELEASE == 'true' }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
        id: setup-buildx
        if: ${{ env.SHOULD_RELEASE == 'true' }}

      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          cache: ${{ env.SHOULD_CACHE == 'true' }}

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: .tool-versions

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: .tool-versions
          cache: ${{ env.SHOULD_CACHE == 'true' }}

      - name: Setup golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          install-only: true
          version-file: .tool-versions
          skip-save-cache: ${{ env.SHOULD_CACHE == 'false' }}

      - name: Setup Mise
        uses: jdx/mise-action@v4
        with:
          experimental: true
          cache: ${{ env.SHOULD_CACHE == 'true' }}

      - name: Cache Buf dependencies
        uses: actions/cache@v5
        with:
          path: ~/.cache/buf
          key: ${{ runner.os }}-buf-${{ hashFiles('**/buf.lock') }}
          restore-keys: ${{ runner.os }}-buf-

      - name: Derive SHAs for Nx Affected
        id: set-shas
        uses: nrwl/nx-set-shas@v5

      - name: Restore Docs diagrams Cache
        uses: actions/cache/restore@v5
        if: ${{ github.event.inputs.noRestoreDocsDiagramsCache != 'true' }}
        with:
          path: docs/src/public/diagrams/
          key: docs-diagrams-

      - name: Install Node Dependencies
        run: pnpm install

      - name: Install Go Dependencies
        run: go mod download

      - name: Nx reset cache
        if: ${{ github.event.inputs.resetNxCache == 'true' }}
        run: pnpm exec nx reset

      - name: Nx all
        run: |
          nx-cache-action -- \
          pnpm exec nx ${{ github.event.inputs.nxAllCmd || 'affected' }} \
            --target lint \
            --target format:check \
            --target gen \
            --target bundle \
            --target build \
            --target test \
            --target typecheck \
            --parallel=${{env.NX_PARALLEL }} \
            --configuration 'production' \
            ${{ github.event.inputs.skipNxCache == 'true' && '--skipNxCache' || '' }}

      - name: Check for changes after Build/Gen
        run: |
          git add .
          if ! git diff --staged --color=always --exit-code; then
            echo 'ERROR: There are uncommitted changes after build/gen. Please commit the changes.';
            git status --short
            exit 1;
          fi

      - name: Nx Deploy Page
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          nx-cache-action -- \
          pnpm exec nx ${{ github.event.inputs.nxAllCmd || 'affected' }} \
            '--target deployPage' \
            --parallel=${{env.NX_PARALLEL }} \
            --configuration 'production' \
            ${{ github.event.inputs.skipNxCache == 'true' && '--skipNxCache' || '' }}

      - name: Github NPM Token
        if: >-
          ${{
            env.SHOULD_RELEASE == 'true' &&
            (github.event.inputs.releaseNpm == 'true' || github.event.inputs.releaseAll == 'true')
          }}
        run: npm config set '//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}' --global

      - name: Nx Release
        if: ${{ env.SHOULD_RELEASE == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUILDX_BUILDER: ${{ steps.setup-buildx.outputs.name }}
          DOCKER_BUILDKIT: 1
        run: |
          # Hey we haven't handle build for npm...
          echo 'Build Docker images'
          nx-cache-action -- \
          pnpm exec nx run-many \
              ${{ (github.event.inputs.releaseAll || github.event.inputs.releaseWeb == 'true') && '--projects web' || '' }} \
              ${{ (github.event.inputs.releaseAll || github.event.inputs.releaseNote == 'true') && '--projects note' || '' }} \
              ${{ (github.event.inputs.releaseAll || github.event.inputs.releaseDocument == 'true') && '--projects document' || '' }} \
              ${{ (github.event.inputs.releaseAll || github.event.inputs.releaseSearchWorker == 'true') && '--projects search-worker' || '' }} \
            --target docker:build \
            --parallel=${{env.NX_PARALLEL }} \
            --configuration production

          echo 'Built Docker images'
          docker images -a

          if [ "${{ github.event.inputs.releaseAll }}" = "true" ]; then
            nx-cache-action -- \
            pnpm exec nx release \
              --dockerVersionScheme=${{ github.event.inputs.releaseContainerType }} \
              --yes
          else
            nx-cache-action -- \
            pnpm exec nx release \
              --dockerVersionScheme=${{ github.event.inputs.releaseContainerType }} \
              ${{ github.event.inputs.releaseWeb == 'true' && '--projects web' || '' }} \
              ${{ github.event.inputs.releaseNote == 'true' && '--projects note' || '' }} \
              ${{ github.event.inputs.releaseDocument == 'true' && '--projects document' || '' }} \
              ${{ github.event.inputs.releaseSearchWorker == 'true' && '--projects search-worker' || '' }} \
              ${{ github.event.inputs.releaseNpm == 'true' && '--groups npm' || '' }} \
              --yes
          fi

      # - name: Dispatch Update Deploy
      #   uses: benc-uk/workflow-dispatch@v1
      #   if: ${{ env.SHOULD_RELEASE == 'true' }}
      #   with:
      #     workflow: update.yaml
      #     repo: ${{ github.repository_owner }}/infra
      #     token: ${{ steps.get-bot-token.outputs.token }}

      - name: Cache Docs diagrams
        uses: actions/cache/save@v5
        if: ${{ env.SHOULD_CACHE == 'true' }}
        with:
          path: docs/src/public/diagrams/
          key: docs-diagrams-${{ hashFiles('docs/src/public/diagrams/**') }}
